/**
 * Colofón de los tratados: «Fuentes, versiones y aviso de derechos».
 * Texto de la versión corregida (Reina-Valera 1909, dominio público), sin retoques de prosa.
 * Firma del autor: solo «Alejandro Sirit». Se muestra completo al cierre de cada tratado.
 */
export type BloqueColofon = { tipo: "h" | "p" | "li"; texto: string };

export const COLOFON_TITULO = "Fuentes, versiones y aviso de derechos";

export const COLOFON_TRATADOS: readonly BloqueColofon[] = [
  { tipo: "p", texto: "Editorial Cielo Efata · Alejandro Sirit · 2026" },
  { tipo: "p", texto: "Este aviso va en el verso de la portada (créditos) y se repite, completo, al cierre de cada tratado. No es un dictamen de abogado. Es la página de derechos de la casa. Antes de una tirada comercial grande, un abogado en Canadá puede revisarla. El derecho de autor en Canadá es federal (Copyright Act), también para quien publica desde Quebec." },
  { tipo: "h", texto: "1. Versión castellana" },
  { tipo: "p", texto: "Cita de iglesia: Reina-Valera 1909, de dominio público. Se cita tal como la trae esa edición, con su ortografía (á, ó, fué). No requiere permiso ni aviso de titular." },
  { tipo: "p", texto: "No se usan, en estos tratados, NVI, LBLA, NBLA, DHH, TLA, RVR1995 ni RVR2020. Esas versiones tienen otro titular y otro aviso." },
  { tipo: "h", texto: "2. Texto hebreo" },
  { tipo: "p", texto: "Lectura base del Antiguo Testamento: texto masorético del Códice de Leningrado, en la presentación de la Biblia Hebraica Stuttgartensia." },
  { tipo: "p", texto: "Biblia Hebraica Stuttgartensia, ed. Karl Elliger y Wilhelm Rudolph; quinta edición mejorada, ed. Adrian Schenker. © 1977 y 1997 Deutsche Bibelgesellschaft, Stuttgart." },
  { tipo: "p", texto: "En el tratado se cita el versículo, con su lema y su número de Strong, para interpretarlo. No se copia el aparato crítico de la BHS, ni la masora, ni el libro hebreo seguido. La Deutsche Bibelgesellschaft pide permiso escrito para otros usos, salvo el extracto en publicaciones gratuitas de una iglesia. Un libro que se vende no es ese caso. Antes de imprimir columnas hebreas largas, se escribe a la Deutsche Bibelgesellschaft (die-bibel.de/lizenzen)." },
  { tipo: "h", texto: "3. Septuaginta" },
  { tipo: "p", texto: "El griego antiguo de los Setenta es el texto que se compara, versículo a versículo, cuando el número de capítulo no coincide con el masorético (Jeremías) o cuando el Nuevo Testamento cita el Antiguo." },
  { tipo: "p", texto: "No se reproduce la edición:" },
  { tipo: "p", texto: "Septuaginta, ed. Alfred Rahlfs; editio altera, rev. Robert Hanhart. © 2006 Deutsche Bibelgesellschaft, Stuttgart." },
  { tipo: "p", texto: "Si en algún lugar se vierte el griego al inglés de apoyo, esa versión es la de Sir Lancelot C. L. Brenton (1851), de dominio público, y se dice. No se usa la Septuaginta Deutsch (© 2008 Deutsche Bibelgesellschaft)." },
  { tipo: "h", texto: "4. Nuevo Testamento griego" },
  { tipo: "p", texto: "Texto que manda en la cita: Textus Receptus. Ediciones de dominio público: Robert Estienne (Stephanus), 1550; hermanos Elzevir, 1624; F. H. A. Scrivener, 1894, tal como lo fijó la Cambridge University Press para la Revised Version y como lo transmite la Reina-Valera." },
  { tipo: "p", texto: "No se reproduce el Novum Testamentum Graece, 28.ª edición (Nestle-Aland, © 2012 Deutsche Bibelgesellschaft), ni The Greek New Testament de las Sociedades Bíblicas Unidas (© 2014 Deutsche Bibelgesellschaft). Cuando se nombra al Sinaítico, al Vaticano, al Alejandrino o al papiro P46, se nombra un testigo, no se copia una edición crítica." },
  { tipo: "h", texto: "5. Rollos del Mar Muerto" },
  { tipo: "p", texto: "Se cita la lectura publicada, por sigla y versículo, solo donde hay variante que cambia o confirma el sentido. No se reproducen láminas, columnas enteras ni páginas de Discoveries in the Judaean Desert." },
  { tipo: "p", texto: "Siglas que esta serie sí usa:" },
  { tipo: "li", texto: "1QIsaª, Gran Rollo de Isaías. En 53:5 coincide en el sentido con el texto masorético. En 53:11 lee «verá la luz», con la Septuaginta; la BHS no trae el objeto." },
  { tipo: "li", texto: "4Q76 (4QXIIª), para Malaquías 3:10, en la sustancia del texto masorético." },
  { tipo: "li", texto: "4QJerª y 4QJerᶜ, afines al texto masorético de Jeremías; 4QJerᵇ y 4QJerᵈ, afines a la edición breve que está detrás de la Septuaginta. No se alega una lectura distinta de Jeremías 29:11." },
  { tipo: "p", texto: "El Nuevo Testamento no está en Qumrán. No se inventa un rollo para un versículo del Nuevo Testamento." },
  { tipo: "h", texto: "6. Strong" },
  { tipo: "p", texto: "Números, lemas y glosa breve: James Strong, The Exhaustive Concordance of the Bible (1890), dominio público. A veces se precisa con Joseph Henry Thayer, Greek-English Lexicon of the New Testament (1889), y con Francis Brown, S. R. Driver y Charles A. Briggs, A Hebrew and English Lexicon of the Old Testament (1906), también de dominio público." },
  { tipo: "p", texto: "No se copia un léxico moderno con titular vivo (BDAG revisado, HALOT, ni los diccionarios de software)." },
  { tipo: "h", texto: "7. Comentaristas que sí se citan, y cómo" },
  { tipo: "p", texto: "Solo se cita entre comillas lo que está en dominio público, con autor, obra, pasaje y edición. La versión inglesa es la de la Calvin Translation Society (siglo XIX), alojada en la Christian Classics Ethereal Library (ccel.org). Al lado va la versión castellana de la casa, marcada como versión, no como si Calvino hubiera escrito en español." },
  { tipo: "p", texto: "Se usan, y no otros, salvo que el cierre de un tomo nombre la página:" },
  { tipo: "li", texto: "Juan Calvino, Commentary on a Harmony of the Evangelists, Matthew, Mark, and Luke, trad. William Pringle. Mateo 6:31–34." },
  { tipo: "li", texto: "Juan Calvino, Commentary on the Epistle to the Romans. Romanos 8:28–32." },
  { tipo: "li", texto: "Juan Calvino, Commentary on Isaiah, vol. 4. Isaías 53:5." },
  { tipo: "li", texto: "Juan Calvino, Commentary on Philippians, Colossians, and Thessalonians. Filipenses 4:13." },
  { tipo: "li", texto: "Juan Calvino, Commentary on Jeremiah and Lamentations, vol. 3. Jeremías 29." },
  { tipo: "li", texto: "Juan Calvino, Commentary on Zechariah and Malachi. Malaquías 3:10." },
  { tipo: "li", texto: "Juan Calvino, Commentary on Timothy, Titus, and Philemon. 2 Timoteo 1:7." },
  { tipo: "li", texto: "Juan Calvino, Institutes of the Christian Religion, trad. Henry Beveridge (1845), libro IV, sobre atar y desatar (Mateo 18:18)." },
  { tipo: "li", texto: "Albert Barnes, Notes on the New Testament. Mateo 18:18. Dominio público." },
  { tipo: "li", texto: "Matthew Henry, Commentary on the Whole Bible. Dominio público. Solo si el tomo lo nombra." },
  { tipo: "li", texto: "Joseph Barber Lightfoot, Saint Paul's Epistle to the Philippians (1868 y reediciones del siglo XIX). Dominio público. Solo en el tratado de Filipenses 2." },
  { tipo: "li", texto: "J. C. Ryle, Expository Thoughts on the Gospels. Dominio público." },
  { tipo: "p", texto: "No se cita entre comillas a autores con obra vigente: John MacArthur, J. I. Packer, Timothy Keller, D. A. Carson, ni ningún comentarista vivo. Nombrarlos como polo de estilo, sin frase suya, no es cita. Una frase de ellos exigiría derecho de cita (Copyright Act, s. 29.1: crítica o reseña, con fuente y nombre del autor) y sería breve. Estos tratados no la necesitan." },
  { tipo: "h", texto: "8. Obra de la casa" },
  { tipo: "p", texto: "El tratado, la prosa, el orden V.E.R.D.A.D. y el cierre dogmático son de Alejandro Sirit, Editorial Cielo Efata, 2026. Todos los derechos reservados. No se cede el texto a una plataforma para que lo reimprima como si fuera suyo." },
  { tipo: "p", texto: "La Escritura no es del autor. El comentario sí." },
  { tipo: "h", texto: "9. Qué no afirma esta página" },
  { tipo: "p", texto: "No afirma que la BHS o la Rahlfs-Hanhart sean de dominio público. No reproduce aparato crítico, masora, láminas de Qumrán ni comentarios de autor vivo. No es licencia para terceros: quien copie este tratado copia una obra reservada, aunque las citas bíblicas tengan su propio titular." },
  { tipo: "h", texto: "10. Créditos breves para el verso de la portada" },
  { tipo: "p", texto: "Texto bíblico en castellano: Reina-Valera 1909, de dominio público." },
  { tipo: "p", texto: "Hebreo: texto masorético, Códice de Leningrado, según la Biblia Hebraica Stuttgartensia © 1977/1997 Deutsche Bibelgesellschaft, Stuttgart. Se cita el versículo; no se reproduce la edición." },
  { tipo: "p", texto: "Griego del Nuevo Testamento: Textus Receptus (Stephanus 1550; Scrivener 1894), dominio público." },
  { tipo: "p", texto: "Griego del Antiguo Testamento: Septuaginta, comparación por versículo. No se reproduce la edición de Rahlfs-Hanhart © 2006 Deutsche Bibelgesellschaft." },
  { tipo: "p", texto: "Rollos: 1QIsaª, 4Q76, 4QJer, por la lectura publicada del versículo." },
  { tipo: "p", texto: "Léxico: Strong (1890), Thayer (1889), Brown-Driver-Briggs (1906), dominio público." },
  { tipo: "p", texto: "Comentaristas citados: Juan Calvino (Calvin Translation Society, siglo XIX); Albert Barnes; y, solo si el tomo los nombra, Matthew Henry, J. B. Lightfoot y J. C. Ryle. Dominio público. Christian Classics Ethereal Library, ccel.org." },
  { tipo: "p", texto: "Tratado © 2026 Alejandro Sirit, Editorial Cielo Efata. Todos los derechos reservados." },
  { tipo: "p", texto: "El cierre dogmático que firma Alejandro Sirit es doctrina de esta casa. No es dictamen de la Deutsche Bibelgesellschaft." },
];
