/** Párrafo de decisión de cada aula, sin el resto del cuerpo.
 * La ficha de /estudios lo muestra. El aula completo se carga al abrir la clase.
 */
export const DECISION_AULA: Record<string, string> = {
  "romanos-1": "Esta semana, nombra delante de alguien de confianza de qué evangelio te has avergonzado —qué has recortado para no ofender, o qué has convertido en técnica— y cree en voz alta el que Pablo no recorta. Un acto. No una lista. El domingo, que te pregunten si todavía estás negociando el poder como si fuera consejo.",
  "marcos-1": "Esta semana, nombra delante de alguien de confianza de qué te estás volviendo —con nombre, no con niebla— y cree el evangelio en voz alta. Un paso. No una lista. El que añade un tercer verbo para aplazar el mandato todavía no ha oído a Galilea.",
  "juan-3": "Esta semana, deja de negociar el nuevo nacimiento como metáfora. Ora con alguien que ya cree, y pregunta en serio si has nacido de lo alto. Si la respuesta es niebla, no añadas un curso: pide el milagro que el viento da donde quiere, y no te administres un rito para no nacer.",
  "hechos-2": "Si aún no has sido bautizado en el nombre de Jesucristo, habla esta semana con quien pueda administrarlo. Si ya lo fuiste, di a alguien el siguiente acto de obediencia, no un sentimiento. El que se queda en la emoción del sermón ha oído a Pedro como se oye un concierto.",
  "juan-1": "Lee Juan 1:1–18 entero, en voz alta, dos veces esta semana. Escribe una frase: qué afirma de Cristo que tú habías dejado blando. El tratado del mes sostiene este mismo prólogo. El capítulo espera. No memorices el himno: óyelo hasta que el tabernáculo te deje sin un Jesús de diciembre.",
  "isaias-53": "Confiesa esta semana, a Dios y a una persona, un pecado que has llamado «herida» para no llamarlo rebelión. Nómbralo bajo la llaga del Siervo, sin eufemismo. Luego el capítulo entero. El tratado no sustituye a Isaías 53. Lo sirve, y se sienta atrás.",
  "romanos-3": "Esta semana, deja de mezclar tu hoja de servicios con la justificación. Di a alguien: soy justificado por la fe en Jesús, sin la ley. Luego lee 3:21–26 dentro de 3:9–31. El tratado del mes sostiene este mismo párrafo, y el capítulo se lee entero.",
  "2-pedro-1": "Elige un eslabón para esta semana. Escríbelo en el cuaderno y dilo a alguien de confianza. Uno. Costealo. El que elige siete no ha elegido ninguno. El que no lo dice a un testigo lo ha dejado en el eslogan.",
  "2-corintios-5": "Esta semana, habla como embajador una vez: di a alguien concreto que Dios llama a reconciliarse, no a recablearse. Un nombre. Un ruego. No un hilo. El que se queda en el 17 sin el 21 ha convertido la nueva creación en un espejo.",
  "filipenses-2": "Cede un derecho esta semana —uno que te estaba inflando— y no lo anuncies. Hazlo porque el himno manda. Evodia y Síntique no necesitan otro taller: necesitan este Cristo. El que anuncia el despojo ya lo ha convertido en teatro.",
  "santiago-1": "Lo que este texto te mostró, hazlo antes de siete días. Anótalo. Dilo a un testigo. Si se queda en el cuaderno sin acto, volviste a mirarte y te fuiste. Queda prohibido un «hoy muero a…» que el pasaje no conjuga. El verbo aquí es hacer, no morir a un ego genérico.",
  "romanos-12": "Nombra un molde de este siglo al que te estás adaptando. Preséntalo esta semana: un no concreto, dicho a alguien. El cuerpo es el altar. El que se queda en la emoción del culto sin un no ha oído Romanos 12 como se oye un himno, no como se oye un ruego.",
  "juan-14": "Esta semana, deja de suavizar «nadie viene». Di a una persona, sin grosería y sin rebaja, que el Padre se alcanza por Jesús. El que busca un mapa todavía no ha oído a Tomás. El que ha oído, habla, o sigue de noche con un vocabulario inclusivo.",
  "salmo-23": "Donde ahora tienes miedo, nombra al Pastor en segunda persona esta semana: «tú estás conmigo». Dilo a alguien que camine el mismo valle. El que reza el salmo para que el valle se vaya aún no ha llegado al «tú». El que ha llegado, no niega la sombra: la atraviesa.",
  "genesis-3": "El indicativo no es «fuisteis informados». Dios cubre, pone enemistad y anuncia la simiente. Nadie mortifica para unirse: se mortifica porque ha sido hallado y vestido.\n\nQueda prohibido «hoy muero a la fruta», porque ese verbo no está. El verbo de 3:1 es la glosa: el אַף que puso el mandato entre comillas. Se toma un mandato de esta semana que se ha suavizado, y se le quita la partícula.\n\n«Hoy muero a las hojas de higuera» sí se conjuga: 3:7 las nombra. El escondite de 3:8 también, y la acusación de 3:12. Se leen y se nombran; no se importa un ego genérico.\n\nUn acto, no una lista: leer Génesis 3 entero, en voz alta; confesar delante de un testigo la negociación; quitar el אַף de un mandato que esta semana se ha puesto entre comillas. C.R.I.S.O.L.™, expuesto en El Altar del Espejo, guarda este eslabón: no es un método segundo.",
  "salmo-22": "El indicativo es «me has oído». El imperativo es proclamar, no «hoy muero a mis sentimientos de abandono» sin el verbo del texto. Lee el salmo entero, en voz alta, y di a alguien la alabanza que el abandonado promete a la asamblea. Quien se quede en el versículo 1 como amuleto de abandono aún no ha llegado al 24.",
  "marcos-7": "El sordo de Marcos 7 no «murió hoy a su sordera»: fue abierto. Esa es la gramática de la gracia. Un acto: lee Marcos 7 entero, en voz alta, y nombra delante de alguien lo que aún no oyes. Mañana se vuelve. El oído no se abre una sola vez. El que convierte Éfata en marca y deja al sordo cerrado ha tomado el nombre del milagro en vano.",
  "apocalipsis-5": "El indicativo es «ha vencido» y «tomó el libro». El imperativo del anciano es el nuestro: no llores. Un acto: cesa esta semana una lectura de la historia que pone el cetro en el César, y di a alguien que el rollo está en las manos atravesadas. El llanto por el libro cerrado termina cuando se adora al que lo tomó.",
  "1-corintios-12-14": "Esta semana, nombra un don —el tuyo o el que envidias— y ponlo al servicio de un hermano concreto, no de un escenario. Un acto. El que busca lengua para ser visto, o silencio para no servir, todavía no ha oído a Corinto.",
  "galatas-5": "Elige un nombre del fruto que el texto ha desnudado —uno, no nueve— y nombra delante de un testigo dónde la carne lo estaba sustituyendo. Anda. El que elige los nueve no ha elegido ninguno. El que no lo dice lo ha dejado en el cartel.",
  "2-corintios-12": "Nombra el aguijón que has tratado como prueba de que Dios no basta. Esta semana, deja de rogar solo para que se quite, y oye la palabra que permanece: bástate mi gracia. Dilo a alguien. El que convierte el 9 en un lema y niega la flaqueza aún no ha sido respondido: ha sido entretenido.",
  "viajes-de-pablo": "Esta semana, nombra un envío concreto —una Palabra que debías anunciar, un hermano que debías confirmar— y no lo midas por la facilidad. El que espera un mapa sin Listra todavía no ha sido apartado: ha sido entretenido.",
  "1-corintios-1-2": "Esta semana, nombra una frase tuya —en el púlpito, en la mesa, en la red— que estaba luciendo más que el madero. Quítala. El que se reforma el estilo y no se arrodilla ante la locura de la cruz todavía está en el ágora.",
  "teologia-de-la-cruz": "Esta semana, nombra una jactancia —oficio, púlpito, herida bien contada— que estabas usando para no quedar en «lo que no es». Déjala. Gloríate en el Señor. El que se queda en el desprecio de los sabios y no se queda en Cristo aún no ha oído el 30.",
  "teologia-de-la-gloria": "Nombra un «ya» que te estabas coronando —un ministerio que ya llegó, una herida que ya te hace rey, un escenario que ya te aplaude—. Esta semana, bájalo. El que se niega a ser último todavía está saciado. El texto pide espectáculo al mundo, no trono.",
  "romanos-8-17": "Esta semana, nombra un padecimiento que habías tratado como prueba de que no eres hijo. Somételo al εἴπερ: padece con él, no contra la adopción. Dilo a alguien que gima contigo. El que se corona sin gemir todavía no es coheredero, sino un espectador del 17."
};

export function decisionAula(slug: string) {
  return DECISION_AULA[slug];
}
