/** Índice de aulas: título y cita. El cuerpo vive en studies.ts y solo se carga al abrir la clase. */
export type IndiceEstudio = { slug: string; title: string; ref: string; busca: string };

export const ESTUDIOS_INDICE: IndiceEstudio[] = [
  { slug: "2-pedro-1", title: "Añadid a vuestra fe", ref: "2 Pedro 1:1–11", busca: "Pedro pide añadir a la fe, a costa propia, una cadena de siete eslabones. No es un cartel de virtudes. Es lo que el capítulo 2 va a exigir cuando desenmascare a quienes prometen libertad siendo esclavos de corrupción. Di" },
  { slug: "filipenses-2", title: "El himno del Siervo", ref: "Filipenses 2:5–11", busca: "El himno humilla al yo antes de exaltarlo. Forma de siervo, muerte de cruz, el Nombre sobre todo nombre. Filipenses 2 no se escribió para que el seminario aplaudiera la kénosis. Se escribió para que Evodia y Síntique dej" },
  { slug: "santiago-1", title: "Pronto para oír", ref: "Santiago 1:19–27", busca: "El oyente que se mira y se va. Oír y no hacer es engaño de sí, no un retraso inocente. El altar no es el sentimiento de haber oído, ni la liturgia de un estudio bien anotado. Es el hombre que permanece en la ley perfecta" },
  { slug: "marcos-7", title: "Éfata", ref: "Marcos 7:31–37", busca: "El párrafo entero, no el vocablo extraído como piedra preciosa. Lo toman aparte. Dedos en los oídos. Saliva. Gemido al cielo. Un mandato. Al momento: oídos abiertos, lengua desatada, hablaba bien. El oído precede a la le" },
  { slug: "apocalipsis-5", title: "El Cordero y el rollo", ref: "Apocalipsis 5", busca: "Juan llora porque nadie es digno. El anciano manda: no llores. Se anuncia un León. Se ve un Cordero. En pie, como inmolado. Toma el libro. La creación entera canta. El observador registra la paradoja y no la resuelve ant" },
  { slug: "1-corintios-12-14", title: "Los dones del Espíritu", ref: "1 Corintios 12–14", busca: "Pablo no abre un catálogo de poderes para que Corinto se exhiba. Abre un cuerpo. Hay diversidad de dones, y un solo Espíritu; diversidad de ministerios, y un solo Señor; diversidad de operaciones, y un solo Dios. El que " },
  { slug: "galatas-5", title: "El fruto del Espíritu", ref: "Gálatas 5:22–23", busca: "Pablo no ofrece un cartel de virtudes para que el yo se mida y se apruebe. Ofrece un fruto. Singular. Nueve nombres, un solo árbol. El que se lleva «amor, gozo, paz» como lema de clima interior aún no ha visto el 16: and" },
  { slug: "2-corintios-12", title: "Bástate mi gracia", ref: "2 Corintios 12:1–10", busca: "Pablo no exhibe un viaje al tercer cielo para que Corinto aplaudiera. Exhibe un aguijón que no se quita. Tres veces rogó. La respuesta no es la extracción, sino la palabra. Bástate mi gracia. El que se lleva el 9 como co" },
  { slug: "viajes-de-pablo", title: "Los viajes de Pablo", ref: "Hechos 13–14", busca: "Lucas no escribe un itinerario de turismo apostólico. Escribe un envío. El Espíritu Santo habla en Antioquía; apartan a Bernabé y a Saulo; les imponen las manos; bajan a Seleucia. El que se lleva «viajes de Pablo» como m" },
  { slug: "1-corintios-1-2", title: "La retórica de Pablo", ref: "1 Corintios 1–2", busca: "Pablo no desprecia las palabras. Desprecia la sabiduría de palabras que deja vana la cruz. Corinto se partía por nombres —Pablo, Apolos, Cefas, Cristo— y medía el púlpito por el brillo. El que se lleva «no con sabiduría»" },
  { slug: "teologia-de-la-cruz", title: "Teología de la cruz", ref: "1 Corintios 1:18–31", busca: "Pablo no ofrece una «teología de la cruz» como lema de escuela. Ofrece un tajo. La palabra de la cruz parte a la humanidad: locura para los que se pierden, poder para los que se salvan. El que se lleva el 18 como consign" },
  { slug: "teologia-de-la-gloria", title: "Teología de la gloria", ref: "1 Corintios 4:8–13", busca: "Pablo no escribe un tratado contra el espectáculo: lo desnuda. Corinto ya se saciaba, ya era rica, ya reinaba —sin los apóstoles—. El que se lleva «teología de la gloria» como lema de combate aún no ha visto el 9: Dios e" },
  { slug: "romanos-8-17", title: "Herederos y padecimiento", ref: "Romanos 8:17", busca: "Pablo no ofrece una herencia sin cruz. Si hijos, también herederos; coherederos con Cristo, si es que padecemos juntamente con él. El que se lleva «hijos» como lema de identidad aún no ha oído el εἴπερ: si es que. El que" },
];

export function indiceEstudio(slug: string) {
  return ESTUDIOS_INDICE.find((s) => s.slug === slug);
}
