/** Índice de aulas: título y cita. El cuerpo vive en studies.ts y solo se carga al abrir la clase. */
export type IndiceEstudio = { slug: string; title: string; ref: string; busca: string };

export const ESTUDIOS_INDICE: IndiceEstudio[] = [
  { slug: "romanos-1", title: "No me avergüenzo", ref: "Romanos 1:16–17", busca: "Pablo no pide permiso para hablar ni abre con una disculpa por el escándalo de la cruz. Declara un evangelio del que no se avergüenza, y lo llama poder —δύναμις— de Dios, no consejo ni técnica de crecimiento. El alcance " },
  { slug: "marcos-1", title: "Arrepentíos", ref: "Marcos 1:14–15", busca: "Marcos no abre con un consuelo. Abre con un preso —Juan— y con un mandato. Jesús no pregunta cómo te sientes ni ofrece una técnica de estudio. Anuncia que el tiempo se ha cumplido y pide dos verbos: volveos y creed. El r" },
  { slug: "juan-3", title: "Nacer de nuevo", ref: "Juan 3:1–8", busca: "Nicodemo ya sabe y ya enseña. Viene de noche, con el oficio intacto y la pregunta a medias. Jesús no le mejora el currículo: le pide nacer ἄνωθεν —de lo alto, de nuevo—. El reino no se ve por erudición. Hay que nacer. El" },
  { slug: "hechos-2", title: "¿Qué haremos?", ref: "Hechos 2:36–41", busca: "El sermón atraviesa el corazón. No preguntan qué sentir: preguntan qué hacer. Pedro no suaviza: arrepentíos, bautícese cada uno en el nombre de Jesucristo para perdón de los pecados, y recibiréis el don del Espíritu Sant" },
  { slug: "juan-1", title: "El Verbo se hizo carne", ref: "Juan 1:1–18", busca: "El prólogo no es un villancico ni un poema para abrir el libro. Es la tesis: eternidad, creación, rechazo, tabernáculo y el Unigénito que declara al Padre. «En el principio» evoca Génesis 1, y no por casualidad. El Verbo" },
  { slug: "isaias-53", title: "Herido por nuestras rebeliones", ref: "Isaías 53", busca: "El Siervo no es un poema de resiliencia. Carga lo que no es suyo. Hay herida, molido, cargo y resultado: paz, curación, justificación de muchos. Jehová quiso quebrantarlo. El silencio ante los trasquiladores no es estoic" },
  { slug: "romanos-3", title: "Justicia de Dios, sin la ley", ref: "Romanos 3:21–26", busca: "Toda boca se cerró (3:19). Entonces —pero ahora— se manifiesta δικαιοσύνη θεοῦ, sin la ley como escalera, en la sangre de Cristo, para que Dios sea justo y justificador. El «aparte» no despide a Moisés: lo pone a testifi" },
  { slug: "2-pedro-1", title: "Añadid a vuestra fe", ref: "2 Pedro 1:1–11", busca: "Pedro pide añadir a la fe, a costa propia, una cadena de siete eslabones. No es un cartel de virtudes. Es lo que el capítulo 2 va a exigir cuando desenmascare a quienes prometen libertad siendo esclavos de corrupción. Di" },
  { slug: "2-corintios-5", title: "Nueva criatura", ref: "2 Corintios 5:17–21", busca: "Nueva criatura no es un yo recableado ni un tatuaje de conversión. Es reconciliación. Dios estaba en Cristo reconciliando al mundo a sí, no imputándole sus pecados, y nos hizo embajadores. Nadie llega al versículo 17 sin" },
  { slug: "filipenses-2", title: "El himno del Siervo", ref: "Filipenses 2:5–11", busca: "El himno humilla al yo antes de exaltarlo. Forma de siervo, muerte de cruz, el Nombre sobre todo nombre. Filipenses 2 no se escribió para que el seminario aplaudiera la kénosis. Se escribió para que Evodia y Síntique dej" },
  { slug: "santiago-1", title: "Pronto para oír", ref: "Santiago 1:19–27", busca: "El oyente que se mira y se va. Oír y no hacer es engaño de sí, no un retraso inocente. El altar no es el sentimiento de haber oído, ni la liturgia de un estudio bien anotado. Es el hombre que permanece en la ley perfecta" },
  { slug: "romanos-12", title: "No os conforméis", ref: "Romanos 12:1–2", busca: "La mente nueva es culto a Dios, no un recableado interior de moda. El cuerpo se presenta. El siglo presiona. Hay un no y un sí. El «así que» no es un giro moralista, sino consecuencia de once capítulos de misericordia. N" },
  { slug: "juan-14", title: "El único camino", ref: "Juan 14:1–6", busca: "Jesús no señala un camino. Él es el camino, la verdad y la vida. Tomás pregunta y recibe una persona, no un mapa. «No se turbe vuestro corazón»: el Padre tiene casa, y ir al Padre es el asunto, no un atajo espiritual gen" },
  { slug: "salmo-23", title: "Nada me faltará", ref: "Salmo 23", busca: "El valle se atraviesa con el Pastor, no se medita para que desaparezca. El «tú» llega en el valle: de tercera persona —Jehová es mi pastor— a segunda —tú estás conmigo—. La mesa es en presencia de enemigos. El bien y el " },
  { slug: "genesis-3", title: "La primera hermenéutica invertida", ref: "Génesis 3", busca: "El capítulo no arranca con una caída: arranca con una conversación sobre un texto. Hay cuatro bocas —la serpiente, la mujer, el hombre y Jehová Dios— y el verbo decisivo del versículo 1 no es «comer», sino «dijo». La pri" },
  { slug: "salmo-22", title: "El justo rodeado", ref: "Salmo 22", busca: "Se oye el salmo entero: queja, confianza, proclamación. Cambio de persona. Inclusión. El «yo» no es un diario suelto. Hay abandono, manos y pies, sorteo de vestiduras, voto de alabanza ante la asamblea. Quien se lleva so" },
  { slug: "marcos-7", title: "Éfata", ref: "Marcos 7:31–37", busca: "El párrafo entero, no el vocablo extraído como piedra preciosa. Lo toman aparte. Dedos en los oídos. Saliva. Gemido al cielo. Un mandato. Al momento: oídos abiertos, lengua desatada, hablaba bien. El oído precede a la le" },
  { slug: "apocalipsis-5", title: "El Cordero y el rollo", ref: "Apocalipsis 5", busca: "Juan llora porque nadie es digno. El anciano manda: no llores. Se anuncia un León. Se ve un Cordero. En pie, como inmolado. Toma el libro. La creación entera canta. El observador registra la paradoja y no la resuelve ant" },
  { slug: "1-corintios-12-14", title: "Los dones del Espíritu", ref: "1 Corintios 12–14", busca: "Pablo no abre un catálogo de poderes para que Corinto se exhiba. Abre un cuerpo. Hay diversidad de dones, y un solo Espíritu; diversidad de ministerios, y un solo Señor; diversidad de operaciones, y un solo Dios. El que " },
  { slug: "galatas-5", title: "El fruto del Espíritu", ref: "Gálatas 5:22–23", busca: "Pablo no ofrece un cartel de virtudes para que el yo se mida y se apruebe. Ofrece un fruto. Singular. Nueve nombres, un solo árbol. El que se lleva «amor, gozo, paz» como lema de clima interior aún no ha visto el 16: and" },
  { slug: "2-corintios-12", title: "Bástate mi gracia", ref: "2 Corintios 12:1–10", busca: "Pablo no exhibe un viaje al tercer cielo para que Corinto aplaudiera. Exhibe un aguijón que no se quita. Tres veces rogó. La respuesta no es la extracción, sino la palabra. Bástate mi gracia. El que se lleva el 9 como co" },
  { slug: "viajes-de-pablo", title: "Los viajes de Pablo", ref: "Hechos 13–14", busca: "Lucas no escribe un itinerario de turismo apostólico. Escribe un envío. El Espíritu Santo habla en Antioquía; apartan a Bernabé y a Saulo; les imponen las manos; bajan a Seleucia. El que se lleva «viajes de Pablo» como m" },
  { slug: "1-corintios-1-2", title: "La retórica de Pablo", ref: "1 Corintios 1–2", busca: "Pablo no desprecia las palabras. Desprecia la sabiduría de palabras que deja vana la cruz. Corinto se partía por nombres —Pablo, Apolos, Cefas, Cristo— y medía el púlpito por el brillo. El que se lleva «no con sabiduría»" },
  { slug: "teologia-de-la-cruz", title: "Teología de la cruz", ref: "1 Corintios 1:18–31", busca: "Pablo no ofrece una «teología de la cruz» como lema de escuela. Ofrece un tajo. La palabra de la cruz parte a la humanidad: locura para los que se pierden, poder para los que se salvan. El que se lleva el 18 como consign" },
  { slug: "teologia-de-la-gloria", title: "Teología de la gloria", ref: "1 Corintios 4:8–13", busca: "Pablo no escribe un tratado contra el espectáculo: lo desnuda. Corinto ya se saciaba, ya era rica, ya reinaba —sin los apóstoles—. El que se lleva «teología de la gloria» como lema de combate aún no ha visto el 9: Dios e" },
  { slug: "romanos-8-17", title: "Herederos y padecimiento", ref: "Romanos 8:17", busca: "Pablo no ofrece una herencia sin cruz. Si hijos, también herederos; coherederos con Cristo, si es que padecemos juntamente con él. El que se lleva «hijos» como lema de identidad aún no ha oído el εἴπερ: si es que. El que" },
];

export function indiceEstudio(slug: string) {
  return ESTUDIOS_INDICE.find((s) => s.slug === slug);
}
