export type StrongEntry = {
  strong: string;
  gloss: string;
  lemma: string;
};

const G: Record<string, StrongEntry> = {
  ἐφφαθά: { strong: "G2188", lemma: "ἐφφαθά", gloss: "sé abierto (arameo)" },
  διανοίχθητι: { strong: "G1272", lemma: "διανοίγω", gloss: "abrir de parte a parte" },
  δύναμις: { strong: "G1411", lemma: "δύναμις", gloss: "poder, fuerza" },
  θεοῦ: { strong: "G2316", lemma: "θεός", gloss: "Dios" },
  θεὸς: { strong: "G2316", lemma: "θεός", gloss: "Dios" },
  θεόν: { strong: "G2316", lemma: "θεός", gloss: "Dios" },
  δικαιοσύνη: { strong: "G1343", lemma: "δικαιοσύνη", gloss: "justicia" },
  πίστεως: { strong: "G4102", lemma: "πίστις", gloss: "fe, fidelidad" },
  πίστιν: { strong: "G4102", lemma: "πίστις", gloss: "fe, fidelidad" },
  μετανοεῖτε: { strong: "G3340", lemma: "μετανοέω", gloss: "arrepentirse, volverse" },
  μετανοήσατε: { strong: "G3340", lemma: "μετανοέω", gloss: "arrepentirse, volverse" },
  μετάνοια: { strong: "G3341", lemma: "μετάνοια", gloss: "arrepentimiento" },
  πιστεύετε: { strong: "G4100", lemma: "πιστεύω", gloss: "creer, fiarse" },
  βασιλεία: { strong: "G932", lemma: "βασιλεία", gloss: "reino, reinado" },
  πεπλήρωται: { strong: "G4137", lemma: "πληρόω", gloss: "cumplirse, llenarse" },
  καιρός: { strong: "G2540", lemma: "καιρός", gloss: "tiempo señalado, sazón" },
  καιρῷ: { strong: "G2540", lemma: "καιρός", gloss: "tiempo señalado, sazón" },
  ἄνωθεν: { strong: "G509", lemma: "ἄνωθεν", gloss: "de lo alto; de nuevo" },
  γεννηθῇ: { strong: "G1080", lemma: "γεννάω", gloss: "nacer, engendrar" },
  ὕδατος: { strong: "G5204", lemma: "ὕδωρ", gloss: "agua" },
  πνεύματος: { strong: "G4151", lemma: "πνεῦμα", gloss: "Espíritu, viento, aliento" },
  πνεῦμα: { strong: "G4151", lemma: "πνεῦμα", gloss: "Espíritu, viento, aliento" },
  κατενύγησαν: { strong: "G2660", lemma: "κατανύσσω", gloss: "ser atravesado, compungirse" },
  καρδίαν: { strong: "G2588", lemma: "καρδία", gloss: "corazón" },
  βαπτισθήτω: { strong: "G907", lemma: "βαπτίζω", gloss: "bautizar, sumergir" },
  ἕκαστος: { strong: "G1538", lemma: "ἕκαστος", gloss: "cada uno" },
  ἄφεσιν: { strong: "G859", lemma: "ἄφεσις", gloss: "perdón, liberación" },
  ἁμαρτιῶν: { strong: "G266", lemma: "ἁμαρτία", gloss: "pecado" },
  ἁμαρτίαν: { strong: "G266", lemma: "ἁμαρτία", gloss: "pecado" },
  λόγος: { strong: "G3056", lemma: "λόγος", gloss: "Verbo, palabra, razón" },
  λόγου: { strong: "G3056", lemma: "λόγος", gloss: "Verbo, palabra, razón" },
  ἐσκήνωσεν: { strong: "G4637", lemma: "σκηνόω", gloss: "tabernacular, habitar" },
  ἐξηγήσατο: { strong: "G1834", lemma: "ἐξηγέομαι", gloss: "declarar, exponer" },
  μονογενής: { strong: "G3439", lemma: "μονογενής", gloss: "unigénito, único" },
  ἱλαστήριον: { strong: "G2435", lemma: "ἱλαστήριον", gloss: "propiciatorio, propiciación" },
  ἀπολύτρωσις: { strong: "G629", lemma: "ἀπολύτρωσις", gloss: "redención, manumisión" },
  πάρεσις: { strong: "G3929", lemma: "πάρεσις", gloss: "pasar por alto" },
  δικαιοῦντα: { strong: "G1344", lemma: "δικαιόω", gloss: "justificar" },
  Ἰησοῦ: { strong: "G2424", lemma: "Ἰησοῦς", gloss: "Jesús" },
  ἐπιχορηγήσατε: { strong: "G2023", lemma: "ἐπιχορηγέω", gloss: "suministrar, costear" },
  σπουδὴν: { strong: "G4710", lemma: "σπουδή", gloss: "diligencia, prisa" },
  μυωπάζων: { strong: "G3467", lemma: "μυωπάζω", gloss: "ser corto de vista" },
  βεβαίαν: { strong: "G949", lemma: "βέβαιος", gloss: "firme, seguro" },
  καινὴ: { strong: "G2537", lemma: "καινός", gloss: "nuevo" },
  κτίσις: { strong: "G2937", lemma: "κτίσις", gloss: "creación, criatura" },
  καταλλαγή: { strong: "G2643", lemma: "καταλλαγή", gloss: "reconciliación" },
  πρεσβεύομεν: { strong: "G4243", lemma: "πρεσβεύω", gloss: "ser embajador" },
  ἐποίησεν: { strong: "G4160", lemma: "ποιέω", gloss: "hacer" },
  μορφή: { strong: "G3444", lemma: "μορφή", gloss: "forma" },
  μορφὴ: { strong: "G3444", lemma: "μορφή", gloss: "forma" },
  δούλου: { strong: "G1401", lemma: "δοῦλος", gloss: "siervo, esclavo" },
  ἐκένωσεν: { strong: "G2758", lemma: "κενόω", gloss: "vaciar, despojar" },
  θανάτου: { strong: "G2288", lemma: "θάνατος", gloss: "muerte" },
  σταυροῦ: { strong: "G4716", lemma: "σταυρός", gloss: "cruz" },
  ὑπερύψωσεν: { strong: "G5251", lemma: "ὑπερυψόω", gloss: "sobreexaltar" },
  ποιηταὶ: { strong: "G4163", lemma: "ποιητής", gloss: "hacedor" },
  παραλογιζόμενοι: { strong: "G3884", lemma: "παραλογίζομαι", gloss: "engañarse, extraviarse" },
  ἑαυτούς: { strong: "G1438", lemma: "ἑαυτοῦ", gloss: "a sí mismos" },
  ἔσοπτρον: { strong: "G2072", lemma: "ἔσοπτρον", gloss: "espejo" },
  νόμον: { strong: "G3551", lemma: "νόμος", gloss: "ley" },
  τέλειον: { strong: "G5046", lemma: "τέλειος", gloss: "perfecto, cumplido" },
  ἐλευθερίας: { strong: "G1657", lemma: "ἐλευθερία", gloss: "libertad" },
  λογικὴν: { strong: "G3050", lemma: "λογικός", gloss: "razonable, de la Palabra" },
  λατρείαν: { strong: "G2999", lemma: "λατρεία", gloss: "culto, servicio sagrado" },
  συσχηματίζεσθε: { strong: "G4964", lemma: "συσχηματίζω", gloss: "amoldarse, ensamblarse" },
  μεταμορφοῦσθε: { strong: "G3339", lemma: "μεταμορφόω", gloss: "ser transformado" },
  ἀνακαινώσει: { strong: "G342", lemma: "ἀνακαίνωσις", gloss: "renovación" },
  νοός: { strong: "G3563", lemma: "νοῦς", gloss: "mente, entendimiento" },
  ἐγώ: { strong: "G1473", lemma: "ἐγώ", gloss: "yo" },
  εἰμι: { strong: "G1510", lemma: "εἰμί", gloss: "ser, estar" },
  ὁδός: { strong: "G3598", lemma: "ὁδός", gloss: "camino" },
  ἀλήθεια: { strong: "G225", lemma: "ἀλήθεια", gloss: "verdad" },
  ζωή: { strong: "G2222", lemma: "ζωή", gloss: "vida" },
  οὐδεὶς: { strong: "G3762", lemma: "οὐδείς", gloss: "nadie" },
  ἔρχεται: { strong: "G2064", lemma: "ἔρχομαι", gloss: "venir" },
  πατέρα: { strong: "G3962", lemma: "πατήρ", gloss: "Padre" },
  ἐμοῦ: { strong: "G1473", lemma: "ἐγώ", gloss: "de mí" },
  παράκλητος: { strong: "G3875", lemma: "παράκλητος", gloss: "abogado, consolador" },
  ποιμήν: { strong: "G4166", lemma: "ποιμήν", gloss: "pastor" },
  ἀρετή: { strong: "G703", lemma: "ἀρετή", gloss: "virtud, excelencia" },
  γνῶσις: { strong: "G1108", lemma: "γνῶσις", gloss: "conocimiento" },
  ἐγκράτεια: { strong: "G1466", lemma: "ἐγκράτεια", gloss: "dominio propio" },
  ὑπομονή: { strong: "G5281", lemma: "ὑπομονή", gloss: "perseverancia" },
  εὐσέβεια: { strong: "G2150", lemma: "εὐσέβεια", gloss: "piedad" },
  φιλαδελφία: { strong: "G5360", lemma: "φιλαδελφία", gloss: "amor fraternal" },
  ἀγάπη: { strong: "G26", lemma: "ἀγάπη", gloss: "amor" },
  φίλαυτοι: { strong: "G5367", lemma: "φίλαυτος", gloss: "amadores de sí mismos" },
  αὐτῷ: { strong: "G846", lemma: "αὐτός", gloss: "él, ello" },
  αὐτὸν: { strong: "G846", lemma: "αὐτός", gloss: "él" },
  αὐτός: { strong: "G846", lemma: "αὐτός", gloss: "él" },
  διὸ: { strong: "G1352", lemma: "διό", gloss: "por lo cual" },
  πᾶν: { strong: "G3956", lemma: "πᾶς", gloss: "todo" },
  πᾶσαν: { strong: "G3956", lemma: "πᾶς", gloss: "toda" },
  γόνυ: { strong: "G1119", lemma: "γόνυ", gloss: "rodilla" },
  κάμψῃ: { strong: "G2578", lemma: "κάμπτω", gloss: "doblar" },
  ἦν: { strong: "G1510", lemma: "εἰμί", gloss: "era, estaba" },
  πρὸς: { strong: "G4314", lemma: "πρός", gloss: "con, hacia" },
  ἐκ: { strong: "G1537", lemma: "ἐκ", gloss: "de, desde" },
  ἐξ: { strong: "G1537", lemma: "ἐκ", gloss: "de, desde" },
  εἰς: { strong: "G1519", lemma: "εἰς", gloss: "a, hacia, para" },
  ἐν: { strong: "G1722", lemma: "ἐν", gloss: "en" },
  οὐ: { strong: "G3756", lemma: "οὐ", gloss: "no" },
  γὰρ: { strong: "G1063", lemma: "γάρ", gloss: "porque, pues" },
  καὶ: { strong: "G2532", lemma: "καί", gloss: "y" },
  δὲ: { strong: "G1161", lemma: "δέ", gloss: "y, pero" },
  εἰ: { strong: "G1487", lemma: "εἰ", gloss: "si" },
  μὴ: { strong: "G3361", lemma: "μή", gloss: "no" },
  δι: { strong: "G1223", lemma: "διά", gloss: "por, a través de" },
  μέχρι: { strong: "G3360", lemma: "μέχρι", gloss: "hasta" },
  νῦν: { strong: "G3568", lemma: "νῦν", gloss: "ahora" },
  ὁ: { strong: "G3588", lemma: "ὁ", gloss: "el" },
  ἡ: { strong: "G3588", lemma: "ὁ", gloss: "la" },
  τὸν: { strong: "G3588", lemma: "ὁ", gloss: "el (acusativo)" },
  τὴν: { strong: "G3588", lemma: "ὁ", gloss: "la (acusativo)" },
  τοῦ: { strong: "G3588", lemma: "ὁ", gloss: "del" },
  τῶν: { strong: "G3588", lemma: "ὁ", gloss: "de los" },
  τῆς: { strong: "G3588", lemma: "ὁ", gloss: "de la" },
  τῷ: { strong: "G3588", lemma: "ὁ", gloss: "al" },
};

const H: Record<string, StrongEntry> = {
  אתפתח: { strong: "H6605", lemma: "פָּתַח", gloss: "ser abierto (arameo de Marcos 7:34)" },
  סָבַל: { strong: "H5445", lemma: "סָבַל", gloss: "soportar, cargar" },
  אָשָׁם: { strong: "H817", lemma: "אָשָׁם", gloss: "culpa; ofrenda por la culpa" },
  הַפְגִּיעַ: { strong: "H6293", lemma: "פָּגַע", gloss: "hacer encontrar; quebrantar" },
  צַדִּיק: { strong: "H6662", lemma: "צַדִּיק", gloss: "justo" },
  יְהוָה: { strong: "H3068", lemma: "יהוה", gloss: "YHWH, el Señor" },
  רֹעִי: { strong: "H7462", lemma: "רָעָה", gloss: "pastorear; mi pastor" },
  לֹא: { strong: "H3808", lemma: "לֹא", gloss: "no" },
  "לֹא־מוֹת": { strong: "H4191", lemma: "מוּת", gloss: "no morir de muerte" },
  אֶחְסָר: { strong: "H2637", lemma: "חָסֵר", gloss: "faltar, carecer" },
  גֵּיא: { strong: "H1516", lemma: "גַּיְא", gloss: "valle" },
  צַלְמָוֶת: { strong: "H6757", lemma: "צַלְמָוֶת", gloss: "sombra de muerte" },
  שֵׁבֶט: { strong: "H7626", lemma: "שֵׁבֶט", gloss: "vara, cetro" },
  שִׁבְטְךָ: { strong: "H7626", lemma: "שֵׁבֶט", gloss: "tu vara" },
  מִשְׁעֶנֶת: { strong: "H4938", lemma: "מִשְׁעֶנֶת", gloss: "cayado, bastón" },
  וּמִשְׁעַנְתֶּךָ: { strong: "H4938", lemma: "מִשְׁעֶנֶת", gloss: "y tu cayado" },
  אַךְ: { strong: "H389", lemma: "אַךְ", gloss: "ciertamente, solo" },
  טוֹב: { strong: "H2896", lemma: "טוֹב", gloss: "bueno, bien" },
  וָחֶסֶד: { strong: "H2617", lemma: "חֶסֶד", gloss: "misericordia, lealtad" },
  יִרְדְּפוּנִי: { strong: "H7291", lemma: "רָדַף", gloss: "perseguirán; me seguirán" },
  עֶבֶד: { strong: "H5650", lemma: "עֶבֶד", gloss: "siervo" },
  נָחָשׁ: { strong: "H5175", lemma: "נָחָשׁ", gloss: "serpiente" },
  עָרוּם: { strong: "H6175", lemma: "עָרוּם", gloss: "astuto, sagaz" },
  עֵירֻם: { strong: "H5903", lemma: "עֵירֹם", gloss: "desnudo" },
  עֲרוּמִּים: { strong: "H6174", lemma: "עָרוֹם", gloss: "desnudos" },
  אַף: { strong: "H637", lemma: "אַף", gloss: "también; conque" },
  מוֹת: { strong: "H4191", lemma: "מוּת", gloss: "morir; de muerte" },
  תָּמוּת: { strong: "H4191", lemma: "מוּת", gloss: "morirás" },
  תְּמֻתוּן: { strong: "H4191", lemma: "מוּת", gloss: "moriréis" },
  כֵּאלֹהִים: { strong: "H430", lemma: "אֱלֹהִים", gloss: "como Dios" },
  אֱלֹהִים: { strong: "H430", lemma: "אֱלֹהִים", gloss: "Dios" },
  חַוָּה: { strong: "H2332", lemma: "חַוָּה", gloss: "Eva, viviente" },
  עָפָר: { strong: "H6083", lemma: "עָפָר", gloss: "polvo" },
  זֶרַע: { strong: "H2233", lemma: "זֶרַע", gloss: "simiente, descendencia" },
  שׁוּף: { strong: "H7779", lemma: "שׁוּף", gloss: "herir, moler" },
  רֹאשׁ: { strong: "H7218", lemma: "רֹאשׁ", gloss: "cabeza" },
  עָקֵב: { strong: "H6119", lemma: "עָקֵב", gloss: "calcañar" },
};

const LEX: Record<string, StrongEntry> = { ...G, ...H };

export function strongDe(token: string): StrongEntry | undefined {
  const t = token.normalize("NFC").replace(/[’'·]/g, "");
  return LEX[t] ?? LEX[token];
}

export function tituloStrong(token: string): string {
  const e = strongDe(token);
  if (!e) {
    const he = /[\u0590-\u05FF]/.test(token);
    return he
      ? `${token} — hebreo (consultar Strong)`
      : `${token} — griego (consultar Strong)`;
  }
  return `${e.lemma} — ${e.gloss} (Strong ${e.strong})`;
}

export const ORIGINAL_RE = /[\u0370-\u03FF\u1F00-\u1FFF]+|[\u0590-\u05FF]+/g;
