/**
 * Glosas tomadas de la prosa de los tratados y estudios: «palabra (transliteración, Strong N, sentido)».
 * Solo entran las que el propio texto glosa; lo que no tiene glosa segura no lleva tooltip.
 */
export type GlosaProsa = { translit: string; gloss: string; strong?: string; lemma?: string };

export const PALABRAS_PROSA: Record<string, GlosaProsa> = {
  "Θρησκός": { translit: "thrēskós", gloss: "el que se tiene por religioso" },
  "Κατάκριμα": { translit: "katákrima", gloss: "condenación, la sentencia adversa que cae sobre el reo", strong: "G2631" },
  "Κληρονόμοι": { translit: "klēronómoi", gloss: "heredero, el que recibe la porción no como jornal de un día sino como lo que corresponde al hijo", strong: "G2818", lemma: "κληρονόμος" },
  "Κύριος": { translit: "Kyrios", gloss: "Señor" },
  "Μεμύημαι": { translit: "memýēmai", gloss: "he sido iniciado", strong: "G3453" },
  "Πέπεισμαι": { translit: "pépeismai", gloss: "estoy cierto, persuadido" },
  "Παραμείνας": { translit: "parameínas", gloss: "habiendo permanecido junto a ella" },
  "Συγκληρονόμοι": { translit: "synklēronómoi", gloss: "coheredero, el que hereda juntamente con otro", strong: "G4789", lemma: "συγκληρονόμος" },
  "Συκῆ": { translit: "sykē", gloss: "higuera" },
  "Συμμαρτυρεῖ": { translit: "symmartyreî", gloss: "da testimonio juntamente, confirma con su testimonio", strong: "G4828", lemma: "συμμαρτυρέω" },
  "Συμπάσχομεν": { translit: "sympáschomen", gloss: "padecer juntamente, sufrir con", strong: "G4841", lemma: "συμπάσχω" },
  "Συνδοξασθῶμεν": { translit: "syndoxasthômen", gloss: "ser glorificado juntamente", strong: "G4888", lemma: "συνδοξάζω" },
  "Υἱοθεσία": { translit: "huiothesía", gloss: "adopción, el acto por el que el que no tenía la condición de hijo es puesto por hijo", strong: "G5206" },
  "αὐτοῦ": { translit: "autou", gloss: "de él" },
  "βαπτίζω": { translit: "baptizo", gloss: "bautizar, sumergir en la incorporación que el versículo nombra", strong: "G907" },
  "βασιλείαν": { translit: "basileían", gloss: "reino, soberanía, reinado", strong: "G932" },
  "βιβλίον": { translit: "biblíon", gloss: "rollo, libro", strong: "G975" },
  "βλέπετε": { translit: "blépete", gloss: "mirad" },
  "βραδύς": { translit: "bradýs", gloss: "tardo, lento", strong: "G1021" },
  "γάρ": { translit: "gár", gloss: "porque" },
  "δέ": { translit: "dé", gloss: "pero, antes bien" },
  "δέσμιος": { translit: "désmios", gloss: "preso", strong: "G1198" },
  "δήσητε": { translit: "dḗsēte", gloss: "ligareis" },
  "δειλία": { translit: "deilía", gloss: "cobardía, encogimiento", strong: "G1167" },
  "δεσμός": { translit: "desmós", gloss: "atadura", strong: "G1199" },
  "δεῖ": { translit: "deî", gloss: "es necesario, le era necesario, la necesidad que no es capricho del ánimo ni accidente del mapa", strong: "G1163" },
  "διαίρεσις": { translit: "diairesis", gloss: "diversidad, distribución, reparto", strong: "G1243" },
  "διανοίγω": { translit: "dianoigō", gloss: "abrir de par en par, abrir por completo", strong: "G1272" },
  "δικαιοῖ": { translit: "dikaioî", gloss: "justifica" },
  "δόξα": { translit: "dóxa", gloss: "gloria, el peso de lo que se manifiesta y se honra", strong: "G1391" },
  "εἰρήνη": { translit: "eiréne", gloss: "paz", strong: "G1515" },
  "εὐδοκῶ": { translit: "eudoko", gloss: "me gozo, me complazco", strong: "G2106", lemma: "εὐδοκέω" },
  "εὐθέως": { translit: "euthéōs", gloss: "enseguida" },
  "ζητέω": { translit: "zētéō", gloss: "buscar, procurar", strong: "G2212" },
  "ζητεῖ": { translit: "zēteî", gloss: "busca" },
  "ζητεῖτε": { translit: "zēteîte", gloss: "buscad" },
  "θέλει": { translit: "thelei", gloss: "quiere", strong: "G2309", lemma: "θέλω" },
  "θεόπνευστος": { translit: "theópneustos", gloss: "exhalada por Dios", strong: "G2315" },
  "θλῖψις": { translit: "thlîpsis", gloss: "tribulación" },
  "θρησκεία": { translit: "thrēskeía", gloss: "culto, religión, el servicio externo que se ofrece como piedad", strong: "G2356" },
  "καρπός": { translit: "karpós", gloss: "fruto", strong: "G2590" },
  "κατακρίνειν": { translit: "katakrínein", gloss: "condenar" },
  "κατανοέω": { translit: "katanoéō", gloss: "considerar con atención", strong: "G2657" },
  "κατηχέω": { translit: "katēchéō", gloss: "instruir de viva voz, hacer resonar en el oído", strong: "G2727" },
  "καυχάομαι": { translit: "kaucháomai", gloss: "gloriarse, jactarse", strong: "G2744" },
  "κενοδοξία": { translit: "kenodoxía", gloss: "vanagloria, gloria vacía, opinión hinchada de nada", strong: "G2754" },
  "κενόω": { translit: "kenóo", gloss: "vaciar, despojar", strong: "G2758" },
  "κορβᾶν": { translit: "korbân", gloss: "ofrenda consagrada" },
  "κωφός": { translit: "kōphós", gloss: "sordo, embotado", strong: "G2974" },
  "κόπος": { translit: "kopos", gloss: "trabajo, fatiga que agota", strong: "G2873" },
  "λιμός": { translit: "limos", gloss: "hambre", strong: "G3042" },
  "λύσητε": { translit: "lýsēte", gloss: "desatareis" },
  "λῃστής": { translit: "lēstḗs", gloss: "salteador", strong: "G3027" },
  "μάταιος": { translit: "mátaios", gloss: "vana, vacía, sin fruto delante del Dios a quien pretendía honrar", strong: "G3152" },
  "μέριμνα": { translit: "merimna", gloss: "cuidado, preocupación que se agolpa", strong: "G3308" },
  "μακάριος": { translit: "makários", gloss: "bienaventurado" },
  "μακροθυμία": { translit: "makrothymía", gloss: "paciencia, longanimidad, el ánimo largo", strong: "G3115" },
  "μαρτύριον": { translit: "martýrion", gloss: "testimonio", strong: "G3142" },
  "ματαιότης": { translit: "mataiótēs", gloss: "vanidad, futilidad", strong: "G3153" },
  "μεριμνάω": { translit: "merimnáō", gloss: "dividir la mente, angustiarse" },
  "μογιλάλος": { translit: "mogilálos", gloss: "que habla con dificultad", strong: "G3424" },
  "μωρία": { translit: "mōría", gloss: "locura, necedad", strong: "G3472" },
  "οἰκοδομή": { translit: "oikodome", gloss: "edificación, la obra de levantar la casa", strong: "G3619" },
  "οἴδαμεν": { translit: "oídamen", gloss: "sabemos", strong: "G1492" },
  "πάθημα": { translit: "páthema", gloss: "padecimiento, pasión", strong: "G3804" },
  "παραθήκη": { translit: "parathḗkē", gloss: "lo confiado en custodia", strong: "G3866" },
  "παρακαλῶ": { translit: "parakalô", gloss: "rogar, exhortar, llamar al lado", strong: "G3870" },
  "παρακύψας": { translit: "parakýpsas", gloss: "habiéndose inclinado para mirar", strong: "G3879" },
  "παραμείνας": { translit: "parameínas", gloss: "perseverar, quedarse", strong: "G3887", lemma: "παραμένω" },
  "παρεκάλεσα": { translit: "parekalesa", gloss: "rogué", strong: "G3870", lemma: "παρακαλέω" },
  "περιπατεῖς": { translit: "peripateîs", gloss: "caminas" },
  "περιπατεῖτε": { translit: "peripateíte", gloss: "peripatéo, andar, conducir la vida", strong: "G4043", lemma: "περιπατέω" },
  "πληγή": { translit: "plēgē", gloss: "golpe, azote, herida", strong: "G4127" },
  "πραΰτης": { translit: "praýtes", gloss: "mansedumbre", strong: "G4240" },
  "προπέμψας": { translit: "propémpsas", gloss: "ayudar a seguir el viaje" },
  "προστεθήσεται": { translit: "prostethḗsetai", gloss: "será añadido", strong: "G4369" },
  "πρωτότοκος": { translit: "prōtótokos", gloss: "primogénito", strong: "G4416" },
  "πρόθεσις": { translit: "próthesis", gloss: "propósito puesto delante", strong: "G4286" },
  "πρῶτον": { translit: "prôton", gloss: "primeramente", strong: "G4412" },
  "σάρξ": { translit: "sarx", gloss: "carne", strong: "G4561" },
  "σκάνδαλον": { translit: "skándalon", gloss: "tropiezo, trampa, ocasión de caída", strong: "G4625" },
  "σκόλοψ": { translit: "skolops", gloss: "aguijón, estaca", strong: "G4647" },
  "σοφία": { translit: "sophía", gloss: "sabiduría", strong: "G4678" },
  "στίγματα": { translit: "stigmata", gloss: "marcas, cicatrices", strong: "G4742" },
  "σταυρός": { translit: "staurós", gloss: "cruz, madero", strong: "G4716" },
  "στενάζομεν": { translit: "stenázomen", gloss: "gemimos" },
  "στενάζω": { translit: "stenazō", gloss: "gemir, suspirar con peso", strong: "G4727" },
  "στοιχῶμεν": { translit: "stoichômen", gloss: "stoichéo, caminar en fila, guardar el paso, andar en línea", strong: "G4748", lemma: "στοιχέω" },
  "συμφωνήσωσιν": { translit: "symphōnḗsōsin", gloss: "se convinieren", strong: "G4856" },
  "συναντιλαμβάνεται": { translit: "synantilambánetai", gloss: "toma la carga juntamente", strong: "G4878" },
  "συνεργεῖ": { translit: "synergeî", gloss: "cooperan, trabajan juntamente", strong: "G4903" },
  "σχίσματα": { translit: "schísmata", gloss: "división, rasgadura, cisma", strong: "G4978", lemma: "σχίσμα" },
  "σωφρονισμός": { translit: "sōphronismós", gloss: "templanza, cordura, disciplina de la mente", strong: "G4995" },
  "ταχύς": { translit: "tachýs", gloss: "pronto, ligero para una cosa", strong: "G5036" },
  "ταῦτα": { translit: "taûta", gloss: "estas cosas" },
  "τελέω": { translit: "teléo", gloss: "llevar a cabo, completar, consumar", strong: "G5055" },
  "τελεῖται": { translit: "teleitai", gloss: "se perfecciona, se lleva a su fin", strong: "G5055", lemma: "τελέω" },
  "φανερά": { translit: "fanerá", gloss: "manifiestas, patentes" },
  "φρονεῖν": { translit: "phroneîn", gloss: "pensar, sentir, poner la mira, tener la mente puesta en", strong: "G5426", lemma: "φρονέω" },
  "φρονεῖτε": { translit: "phroneîte", gloss: "tened este sentir, pensad esto", strong: "G5426", lemma: "φρονέω" },
  "φύλλα": { translit: "phýlla", gloss: "hojas" },
  "χάρισμα": { translit: "charisma", gloss: "don de gracia", strong: "G5486" },
  "χαρά": { translit: "jará", gloss: "gozo", strong: "G5479" },
  "χρηστότης": { translit: "jrestótes", gloss: "benignidad, la bondad del trato, lo que es útil y suave sin ser cómplice", strong: "G5544" },
  "χωρίσαι": { translit: "chōrísai", gloss: "apartar, separar", strong: "G5563" },
  "ψυχή": { translit: "psychḗ", gloss: "alma, vida, el yo viviente", strong: "G5590" },
  "אֶפְתַּח": { translit: "eftáj", gloss: "patáj, abrir", strong: "H6605", lemma: "פָּתַח" },
  "בְּרָכָה": { translit: "berajá", gloss: "bendición", strong: "H1293" },
  "גֶּפֶן": { translit: "géfen", gloss: "la vid" },
  "הָאֹכֵל": { translit: "haojel", gloss: "ajál, comer", strong: "H398", lemma: "אָכַל" },
  "וְאֹהֲבֶיהָ": { translit: "ve'ohaveha", gloss: "y los que la aman" },
  "וַהֲרִיקֹתִי": { translit: "vaharigoti", gloss: "ruq, vaciar; en hiphil, vaciar, derramar hasta dejar vacío el recipiente", strong: "H7324", lemma: "רוּק" },
  "חָפֵץ": { translit: "jafets", gloss: "quiso, se complació" },
  "טֶרֶף": { translit: "téref", gloss: "alimento, lo que se desgarra para comer, la ración de la casa", strong: "H2964" },
  "יְשַׁעְיָהוּ": { translit: "Yeshayahu", gloss: "Jehová salva" },
  "יַשְׂכִּיל": { translit: "yaskil", gloss: "será prosperado, obrará sabiamente" },
  "יָד": { translit: "yad", gloss: "mano", strong: "H3027" },
  "כְּמִתְלַהֲמִים": { translit: "kemitlahamim", gloss: "como bocados golosos" },
  "מְדֻכָּא": { translit: "meduká", gloss: "molido, aplastado" },
  "מְחֹלָל": { translit: "mejolal", gloss: "traspasado, herido de muerte" },
  "מְפֹרָשׁ": { translit: "meforash", gloss: "claramente, distintamente", strong: "H6567" },
  "מִפְּשָׁעֵנוּ": { translit: "mipesha'enu", gloss: "a causa de nuestras rebeliones" },
  "מֵעֲוֹנֹתֵינוּ": { translit: "me'avonoteinu", gloss: "a causa de nuestras iniquidades" },
  "מַלְאָכִי": { translit: "Mal'akí", gloss: "mi mensajero, mal'ák, mensajero", strong: "H4397", lemma: "מַלְאָךְ" },
  "מַעֲשֵׂר": { translit: "maaser", gloss: "diezmo", strong: "H4643" },
  "מַשָּׂא": { translit: "masá", gloss: "carga, oráculo pesado", strong: "H4853" },
  "מָשָׁל": { translit: "mashal", gloss: "sentencia, proverbio", strong: "H4912" },
  "נִרְגָּן": { translit: "nirgan", gloss: "murmurador, chismoso" },
  "פְּרִי": { translit: "peri", gloss: "fruto", strong: "H6529" },
  "קָבַע": { translit: "qavá", gloss: "defraudar, despojar, quitar con engaño lo que es de otro", strong: "H6906" },
  "שָׁלוֹם": { translit: "shalom", gloss: "paz, integridad, bienestar" },
  "שָׂדֶה": { translit: "sadé", gloss: "el campo" },
  "שׁוּב": { translit: "shuv", gloss: "volver, retornar", strong: "H7725" },
  "תְּרוּמָה": { translit: "terumá", gloss: "ofrenda alzada, la porción que se levanta y se aparta", strong: "H8641" },
  "ἀγαθωσύνη": { translit: "agathosýne", gloss: "bondad, la rectitud que hace el bien", strong: "G19" },
  "ἀκωλύτως": { translit: "akōlytōs", gloss: "sin impedimento, sin estorbo", strong: "G209" },
  "ἀνάθεμα": { translit: "anáthema", gloss: "anatema, lo entregado a destrucción, maldición", strong: "G331" },
  "ἀναζωπυρεῖν": { translit: "anazōpyreîn", gloss: "reavivar la brasa, volver a encender", strong: "G329" },
  "ἀπαρχή": { translit: "aparchḗ", gloss: "primicias", strong: "G536" },
  "ἀπελήλυθε": { translit: "apelḗlythe", gloss: "se ha ido" },
  "ἀπόδειξις": { translit: "apódeixis", gloss: "demostración, exhibición que muestra", strong: "G585" },
  "ἀρκεῖ": { translit: "arkei", gloss: "basta, alcanza", strong: "G714", lemma: "ἀρκέω" },
  "ἀρνίον": { translit: "arníon", gloss: "cordero", strong: "G721" },
  "ἀσθένεια": { translit: "asthéneia", gloss: "debilidad, flaqueza", strong: "G769" },
  "ἀφίετε": { translit: "aphíete", gloss: "soltad, perdonad", strong: "G863" },
  "ἀφορμή": { translit: "aformḗ", gloss: "ocasión, punto de apoyo, base desde la cual se lanza una operación", strong: "G874" },
  "ἁγιασμός": { translit: "hagiasmós", gloss: "santificación", strong: "G38" },
  "ἄξιος": { translit: "áxios", gloss: "digno, el que alcanza el peso de lo que se pide", strong: "G514" },
  "Ἀνεθάλετε": { translit: "anethálete", gloss: "reflorecisteis" },
  "ἐγκαλεῖν": { translit: "enkaleîn", gloss: "acusar, presentar cargo", strong: "G1458" },
  "ἐκέρδησας": { translit: "ekérdēsas", gloss: "has ganado" },
  "ἐκκλησία": { translit: "ekklēsía", gloss: "asamblea convocada" },
  "ἐμώρανεν": { translit: "emṓranen", gloss: "volver necio, enloquecer", lemma: "μωραίνω" },
  "ἐντυγχάνει": { translit: "entynchánei", gloss: "intercede", strong: "G1793" },
  "ἐξελέξατο": { translit: "exeléxato", gloss: "escoger, elegir para sí", strong: "G1586", lemma: "ἐκλέγομαι" },
  "ἐπαισχύνομαι": { translit: "epaischýnomai", gloss: "avergonzarse", strong: "G1870" },
  "ἐπελάθετο": { translit: "epelátheto", gloss: "olvidó" },
  "ἐπιζητεῖ": { translit: "epizēteî", gloss: "persigue" },
  "ἐπιθυμία": { translit: "epithymía", gloss: "deseo", strong: "G1939" },
  "ἐπιθυμεῖ": { translit: "epithymeí", gloss: "epithyméo, desear", strong: "G1937", lemma: "ἐπιθυμέω" },
  "ἐπιστρέφω": { translit: "epistréphō", gloss: "volverse, convertirse", strong: "G1994" },
  "ἐριθεία": { translit: "eritheía", gloss: "contienda, ambición facciosa, el trabajo que se hace para el propio partido", strong: "G2052" },
  "ἐστέναξε": { translit: "estenaxe", gloss: "gemir desde adentro, suspirar con angustia", strong: "G4727", lemma: "στενάζω" },
  "ἐσταύρωσαν": { translit: "estaúrōsan", gloss: "stauróo, crucificar", strong: "G4717", lemma: "σταυρόω" },
  "ἐσταύρωται": { translit: "estaúrōtai", gloss: "ha sido crucificado" },
  "ἔδωκεν": { translit: "édōken", gloss: "dio" },
  "ἔλεγξον": { translit: "élenxon", gloss: "redargúyele", strong: "G1651" },
  "ἔμαθον": { translit: "émathon", gloss: "aprendí" },
  "ἔμφυτος": { translit: "émphytos", gloss: "implantada, innata en el sentido de metida, plantada dentro", strong: "G1721" },
  "ἔργα": { translit: "erga", gloss: "ergon, obra", strong: "G2041", lemma: "ἔργον" },
  "ἠκαιρεῖσθε": { translit: "ēkaireîsthe", gloss: "os faltaba la oportunidad" },
  "ἱερόν": { translit: "hierón", gloss: "el recinto sagrado entero y no solo el santuario interior", strong: "G2411" },
  "ὀργή": { translit: "orgḗ", gloss: "ira", strong: "G3709" },
  "ὀρθοτομοῦντα": { translit: "orthotomoûnta", gloss: "que corta en línea recta", strong: "G3718" },
  "ὀρθῶς": { translit: "orthōs", gloss: "rectamente, con rectitud, bien", strong: "G3723" },
  "ὑπερνικῶμεν": { translit: "hypernikômen", gloss: "hacemos más que vencer", strong: "G5245" },
  "Ὑγιαίνειν": { translit: "hygiaínein", gloss: "estar sano" },
};

export const FRASES_PROSA: Record<string, GlosaProsa> = {
  "Θεὸς ὁ δικαιῶν": { translit: "theòs ho dikaiôn", gloss: "Dios es el que justifica" },
  "Μὴ οὖν ἐπαισχυνθῇς": { translit: "mē oûn epaischynthês", gloss: "no te avergüences, pues" },
  "Νόμον τέλειον τὸν τῆς ἐλευθερίας": { translit: "nómon téleion tòn tês eleutherías", gloss: "la perfecta ley, la de la libertad" },
  "Οἶδα καὶ ταπεινοῦσθαι": { translit: "oîda kaì tapeinoûsthai", gloss: "sé estar humillado" },
  "Οὐχ ὅτι καθ᾽ ὑστέρησιν λέγω": { translit: "ouch hóti kath᾽ hystérēsin légō", gloss: "no lo digo en razón de indigencia" },
  "Παρέδωκεν αὐτόν": { translit: "parédōken autón", gloss: "le entregó" },
  "Τοῖς ἀγαπῶσι τὸν θεόν": { translit: "toîs agapôsi tòn theón", gloss: "a los que aman a Dios" },
  "Χορτάζεσθαι καὶ πεινᾶν": { translit: "chortázesthai kaì peinân", gloss: "estar harto y tener hambre" },
  "Χριστὸν ἐσταυρωμένον": { translit: "Christòn estaurōménon", gloss: "crucificar", strong: "G4717", lemma: "σταυρόω" },
  "διακριθῇ ἐν τῇ καρδίᾳ": { translit: "diakrithê en tê kardía", gloss: "dudar en el corazón" },
  "δικαιοσύνην αὐτοῦ": { translit: "dikaiosýnēn autoû", gloss: "la justicia / rectitud de él", strong: "G1343" },
  "διὰ τοῦ ἀγαπήσαντος ἡμᾶς": { translit: "dià toû agapḗsantos hēmâs", gloss: "por medio de aquel que nos amó" },
  "διὰ τοῦτο": { translit: "dià toûto", gloss: "por tanto" },
  "διὰ τῆς ἐπιθέσεως τῶν χειρῶν μου": { translit: "dià tês epithéseōs tôn cheirôn mou", gloss: "por la imposición de mis manos" },
  "εἰ ὁ θεὸς ὑπὲρ ἡμῶν": { translit: "ei ho theòs hypèr hēmôn", gloss: "si Dios por nosotros" },
  "θάνατος καὶ ζωὴ ἐν χειρὶ γλώσσης": { translit: "thánatos kaì zōē en cheirì glṓssēs", gloss: "muerte y vida en mano de lengua" },
  "θείας κοινωνοὶ φύσεως": { translit: "theías koinōnoì phýseōs", gloss: "participantes, co-partícipes, de la naturaleza divina" },
  "κατὰ δύναμιν θεοῦ": { translit: "katà dýnamin theoû", gloss: "según la virtud de Dios" },
  "κατ᾽ ἰδίαν": { translit: "kat᾽ idían", gloss: "a solas, fuera de la mirada de la gente" },
  "μὴ γένοιτο": { translit: "mē génoito", gloss: "llegar a ser, con la negación que la versión vierte en ninguna manera", strong: "G1096", lemma: "γίνομαι" },
  "οἶδα καὶ περισσεύειν": { translit: "oîda kaì perisseúein", gloss: "sé tener abundancia" },
  "οὐκ ἀκροατὴς ἐπιλησμονῆς γενόμενος ἀλλὰ ποιητὴς ἔργου": { translit: "ouk akroatēs epilēsmonês genómenos allà poiētēs érgou", gloss: "no hecho oidor de olvido, sino hacedor de obra" },
  "πάντα συνεργεῖ εἰς ἀγαθόν": { translit: "pánta synergeî eis agathón", gloss: "todas las cosas cooperan hacia bien" },
  "πάντα ἰσχύω ἐν τῷ ἐνδυναμοῦντί με Χριστῷ": { translit: "pánta ischýō en tō endynamoûntí me Christō", gloss: "todo lo puedo en el que me fortalece, Cristo" },
  "πίστις θεοῦ": { translit: "pístis theoû", gloss: "fe en Dios, fe cuyo objeto y cuya medida es Dios" },
  "πίστις ἀνυπόκριτος": { translit: "pístis anypókritos", gloss: "fe no fingida" },
  "παραλογιζόμενοι ἑαυτούς": { translit: "paralogizómenoi heautoús", gloss: "razonar al lado, defraudar con un cálculo interior", strong: "G3884", lemma: "παραλογίζομαι" },
  "περισσεύειν καὶ ὑστερεῖσθαι": { translit: "perisseúein kaì hystereîsthai", gloss: "abundar y padecer necesidad" },
  "ποιηταὶ λόγου": { translit: "poiētaì lógou", gloss: "hacedores de la palabra" },
  "πῶς οὐχὶ καὶ σὺν αὐτῷ τὰ πάντα ἡμῖν χαρίσεται": { translit: "pôs ouchì kaì sỳn autō tà pánta hēmîn charísetai", gloss: "cómo no nos dará también con él todas las cosas" },
  "σπουδὴν πᾶσαν": { translit: "spoudḕn pásan", gloss: "toda prisa santa, toda diligencia" },
  "στεναγμοῖς ἀλαλήτοις": { translit: "stenagmoîs alalḗtois", gloss: "con gemidos que no se articulan en palabras" },
  "συγκακοπάθησον τῷ εὐαγγελίῳ": { translit: "synkakopáthēson tō euangelíō", gloss: "padece juntamente el mal por el evangelio" },
  "συμμόρφους τῆς εἰκόνος τοῦ υἱοῦ αὐτοῦ": { translit: "symmórphous tês eikónos toû huioû autoû", gloss: "conformes a la imagen de su Hijo" },
  "τίς καθ᾽ ἡμῶν": { translit: "tís kath᾽ hēmôn", gloss: "quién contra nosotros" },
  "ταῦτα πάντα": { translit: "taûta pánta", gloss: "estas cosas todas" },
  "τοῖς δὲ σῳζομένοις": { translit: "toîs dè sōzoménois", gloss: "salvar; participio presente, los que se están salvando", strong: "G4982", lemma: "σῴζω" },
  "τοῖς κατὰ πρόθεσιν κλητοῖς οὖσι": { translit: "toîs katà próthesin klētoîs oûsi", gloss: "a los que son llamados conforme al propósito" },
  "τοῖς μὲν ἀπολλυμένοις": { translit: "toîs mèn apollyménois", gloss: "perder, destruir; aquí el participio presente, los que se están perdiendo", strong: "G622", lemma: "ἀπόλλυμι" },
  "τοῦ θεοῦ": { translit: "toû theoû", gloss: "de Dios" },
  "τοῦ νῦν καιροῦ": { translit: "toû nŷn kairoû", gloss: "del tiempo presente" },
  "τὸ πρόσωπον τῆς γενέσεως": { translit: "tò prósōpon tês genéseōs", gloss: "el rostro de su nacimiento, el rostro natural, lo que el hombre es y no la máscara que compone para el culto" },
  "τὸ πρόσωπον τῆς γενέσεως αὐτοῦ": { translit: "tò prósōpon tês genéseōs autoû", gloss: "el rostro de su nacimiento, el rostro natural, el que es y no el que finge" },
  "τὸ τέλειον": { translit: "to teleion", gloss: "lo perfecto, lo cumplido", strong: "G5046", lemma: "τέλειος" },
  "τῆς ἐν Χριστῷ Ἰησοῦ τῷ κυρίῳ ἡμῶν": { translit: "tês en Christō Iēsoû tō kyríō hēmôn", gloss: "que es en Cristo Jesús Señor nuestro" },
  "τῷ ὄρει τούτῳ": { translit: "tō órei toútō", gloss: "a este monte" },
  "אִם־לֹא": { translit: "im-lo", gloss: "si no" },
  "בֵּית־תְּפִלָּה": { translit: "beit-tefillah", gloss: "casa de oración" },
  "וְשׂוֹם שֶׂכֶל": { translit: "vesom sékhel", gloss: "poniendo el entendimiento" },
  "חֶרְדַּת אָדָם": { translit: "ḥerdat adam", gloss: "el temblor ante el hombre" },
  "כְּצֹאן טִבְחָה": { translit: "ketson tivjah", gloss: "como ovejas de matadero" },
  "כִּי־עָלֶיךָ הֹרַגְנוּ כָל־הַיּוֹם": { translit: "ki-aleikha horagnu khol-hayyom", gloss: "por tu causa nos matan cada día" },
  "לֹא שָׁנִיתִי": { translit: "lo shaníti", gloss: "shaná, cambiar", strong: "H8138", lemma: "שָׁנָה" },
  "מְעָרַת פָּרִצִים": { translit: "me'arat paritsim", gloss: "cueva de violentos" },
  "מָוֶת וְחַיִּים בְּיַד־לָשׁוֹן": { translit: "mavet vejayyim beyad-lashon", gloss: "muerte y vida en la mano de la lengua" },
  "ἀξίως τοῦ θεοῦ": { translit: "axíōs toû theoû", gloss: "como conviene según Dios, de manera digna de Dios" },
  "ἀπαρνησάσθω ἑαυτόν": { translit: "aparnēsásthō heautón", gloss: "negar del todo, renegar", strong: "G533", lemma: "ἀπαρνέομαι" },
  "ἀρκεῖ σοι ἡ χάρις μου": { translit: "arkei soi he charis mou", gloss: "bástate mi gracia" },
  "ἐγὼ γὰρ ἔμαθον ἐν οἷς εἰμι αὐτάρκης εἶναι": { translit: "egṑ gàr émathon en hoîs eimi autárkēs eînai", gloss: "porque yo aprendí a estar contento en lo que estoy" },
  "ἐκ ῥιζῶν": { translit: "ek rhizôn", gloss: "desde las raíces" },
  "ἐκλεκτοὺς θεοῦ": { translit: "eklektoùs theoû", gloss: "escogidos de Dios" },
  "ἐν Χριστῷ Ἰησοῦ": { translit: "en Christō Iēsoû", gloss: "en Cristo Jesús" },
  "ἐν τῇ ποιήσει αὐτοῦ": { translit: "en tê poiḗsei autoû", gloss: "en su hecho" },
  "ἐπ᾽ ἐλπίδι": { translit: "ep᾽ elpídi", gloss: "con esperanza" },
  "ἐὰν δὲ ἁμαρτήσῃ εἰς σὲ ὁ ἀδελφός σου": { translit: "eàn dè hamartḗsē eis sè ho adelphós sou", gloss: "si tu hermano pecare contra ti" },
  "ἔμφυτον λόγον": { translit: "émphyton lógon", gloss: "palabra implantada, ingerida, sembrada adentro", strong: "G1721" },
  "ἔχετε πίστιν θεοῦ": { translit: "échete pístin theoû", gloss: "tened fe en Dios" },
  "Ἐν τούτοις πᾶσιν": { translit: "en toútois pâsin", gloss: "en todas estas cosas" },
  "Ἐχάρην δὲ ἐν κυρίῳ μεγάλως": { translit: "echárēn dè en kyríō megálōs", gloss: "me gocé en gran manera en el Señor" },
  "ἡμεῖς δὲ κηρύσσομεν": { translit: "hēmeîs dè kērýssomen", gloss: "nosotros predicamos" },
  "ἰσότιμον πίστιν": { translit: "isótimon pístin", gloss: "fe de igual precio, de igual honor" },
  "ἵνα μὴ καυχήσηται πᾶσα σὰρξ ἐνώπιον τοῦ Θεοῦ": { translit: "hína mē kauchḗsētai pâsa sàrx enṓpion toû Theoû", gloss: "para que no se jacte toda carne delante de Dios" },
  "ἵνα ἐπισκηνώσῃ": { translit: "hina episkenose", gloss: "para que habite como en tienda, para que ponga tabernáculo", strong: "G1981", lemma: "ἐπισκηνόω" },
  "ὁ πρεσβύτερος": { translit: "ho presbýteros", gloss: "el anciano" },
  "Ὁ φιλοπρωτεύων": { translit: "ho philoprōteúōn", gloss: "el que ama ser el primero" },
  "Ὅς γε τοῦ ἰδίου υἱοῦ οὐκ ἐφείσατο": { translit: "hós ge toû idíou huioû ouk epheísato", gloss: "el que aun a su propio Hijo no perdonó" },
  "ὑπὲρ ἡμῶν": { translit: "hypèr hēmôn", gloss: "a favor de nosotros" },
  "ὑπὲρ ἡμῶν πάντων": { translit: "hypèr hēmôn pántōn", gloss: "por todos nosotros" },
  "ᾠδὴ καινή": { translit: "ōidḕ kainḗ", gloss: "cántico nuevo" },
};

export function textoProsa(token: string, g: GlosaProsa): string {
  const de = g.lemma ? `, de ${g.lemma}` : "";
  const num = g.strong ? ` (Strong ${g.strong})` : "";
  return `${token} (${g.translit})${de} — ${g.gloss}${num}`;
}

const FRASE_KEYS = Object.keys(FRASES_PROSA).sort((a, b) => b.length - a.length);
const LETRA_ORIGINAL = /[\u0370-\u03FF\u1F00-\u1FFF\u0590-\u05FF]/;

/** Frases griegas o hebreas glosadas por la prosa, con borde de palabra original. */
export function hallarFrasesProsa(text: string): { start: number; end: number; texto: string }[] {
  const out: { start: number; end: number; texto: string }[] = [];
  for (const key of FRASE_KEYS) {
    let from = 0;
    while (from <= text.length) {
      const i = text.indexOf(key, from);
      if (i < 0) break;
      const before = i === 0 ? "" : text[i - 1];
      const after = text[i + key.length] ?? "";
      if (!LETRA_ORIGINAL.test(before) && !LETRA_ORIGINAL.test(after)) {
        out.push({ start: i, end: i + key.length, texto: textoProsa(key, FRASES_PROSA[key]) });
      }
      from = i + key.length;
    }
  }
  return out;
}
