import { estudioSemanaSlug } from "@/lib/calendario";
import { ESTUDIOS_DRIVE, estudioTienePack } from "@/lib/catalogo";
import { LAB_SLUGS } from "@/lib/verdad";

export type Study = {
  slug: string;
  kicker: string;
  ref: string;
  title: string;
  passage: string;
  voz?: string;
  ver: string;
  entorno: string;
  revelacion: string;
  doctrina: string;
  argumento: string;
  decision: string;
  conclusion: string;
};

export const studies: Study[] = [
	{
		slug: "romanos-1",
		kicker: "Estudio",
		ref: "Romanos 1:16–17",
		title: "No me avergüenzo",
		passage: "Porque no me avergüenzo del evangelio, porque es poder de Dios para salvación a todo aquel que cree; al judío primeramente, y también al griego. Porque en el evangelio la justicia de Dios se revela por fe y para fe, como está escrito: Mas el justo por la fe vivirá.",
		ver: "Pablo no pide permiso para hablar ni abre con una disculpa por el escándalo de la cruz. Declara un evangelio del que no se avergüenza, y lo llama poder —δύναμις— de Dios, no consejo ni técnica de crecimiento. El alcance no es una etnia: todo aquel que cree. El orden, no obstante, no borra a Israel: pone al judío primero, y al griego después, porque la historia de la promesa no se recorta para que el imperio se sienta incluido. Quien cita el 16 como lema de valentía aún no ha visto el 17, donde se revela la justicia de Dios, ni el 18, donde se revela su ira.",
		entorno: "Romanos es carta, no lema. Pablo escribe hacia el 57, desde Corinto, a una iglesia que no fundó, en la capital del imperio, para preparar una visita y exponer el evangelio sin recorte. El versículo 16 no viaja solo: detrás está un siervo llamado a ser apóstol (1:1–15) y delante está la ira de Dios revelada contra toda impiedad (1:18). La tesis de la carta —justificación, santificación, Israel, culto del cuerpo— cuelga de este anuncio. Quien extrae el 16 para un cartel ya ha cortado el poder del que habla.",
		revelacion: "οὐ γὰρ ἐπαισχύνομαι: no me avergüenzo. El γάρ ata el anuncio a lo que precede: hay una deuda con griegos y bárbaros, y hay un eagerness de predicar en Roma. δύναμις θεοῦ: poder de Dios, no consejo. δικαιοσύνη θεοῦ: justicia de Dios, revelada ἐκ πίστεως εἰς πίστιν, por fe y para fe. Habacuc 2:4 entra en la carta: el justo por la fe vivirá. No es un lema de superación, ni una consigna de «visualiza tu victoria». Es el umbral de la justificación que 3:21–26 pondrá sobre el propiciatorio.",
		doctrina: "Dios salva con poder, no con mejora del yo. La justicia que salva no nace en el oyente: se revela en el evangelio, y se revela porque el Padre no deja de ser justo para poder perdonar. La fe no es un mérito; es el medio. El pueblo de Dios cruza judío y griego sin borrar la historia de Israel, y sin convertir al gentil en el nuevo centro. El Hijo declarado en 1:3–4 —nacido de la simiente de David, declarado Hijo de Dios con poder por la resurrección— es el contenido de ese poder. El que se avergüenza de este evangelio se avergüenza de Cristo.",
		argumento: "El texto te niega dos vergüenzas: la de recortar el evangelio para que no moleste, y la de convertirlo en una técnica. Si es poder de Dios, no se negocia. Si es para el que cree, no se hereda por sangre ni por aparato. Status quaestionis: ¿es el evangelio un consejo de vida mejor, o el poder de Dios para salvación? Distingo: hay ética en Romanos 12, y nace de las misericordias, no las sustituye. Reductio: si el 16 se cita sin el 18, se ha fabricado un evangelio sin ira, y por tanto sin cruz.",
		decision: "Esta semana, nombra delante de alguien de confianza de qué evangelio te has avergonzado —qué has recortado para no ofender, o qué has convertido en técnica— y cree en voz alta el que Pablo no recorta. Un acto. No una lista. El domingo, que te pregunten si todavía estás negociando el poder como si fuera consejo.",
		conclusion: "El evangelio no es un adorno de la casa, sino poder de Dios para salvación. Quien se avergüenza de él ya eligió otro señor, aunque conserve el vocabulario de la cruz. — Dr. Alejandro Sirit"
	},
	{
		slug: "marcos-1",
		kicker: "El mandato",
		ref: "Marcos 1:14–15",
		title: "Arrepentíos",
		passage: "Después que Juan fue encarcelado, Jesús vino a Galilea predicando el evangelio del reino de Dios, diciendo: El tiempo se ha cumplido, y el reino de Dios se ha acercado; arrepentíos, y creed en el evangelio.",
		voz: "El tiempo se ha cumplido, y el reino de Dios se ha acercado; arrepentíos, y creed en el evangelio.",
		ver: "Marcos no abre con un consuelo. Abre con un preso —Juan— y con un mandato. Jesús no pregunta cómo te sientes ni ofrece una técnica de estudio. Anuncia que el tiempo se ha cumplido y pide dos verbos: volveos y creed. El reino se acercó; no hay un tercer verbo, «más tarde». Quien se lleva solo «cambia tu mentalidad» aún no ha visto al Rey, ni al Bautista que sale de escena para que el Reino hable.",
		entorno: "Marcos escribe un evangelio corto, para oírse de una vez, en un clima de persecución, según el testimonio antiguo, como intérprete de Pedro. Juan el Bautista ya está en la cárcel: el precursor sale de escena para que el Reino hable. Galilea, no Jerusalén. El anuncio llega donde la gente trabaja, no donde se exhibe piedad. Detrás está el umbral de Isaías, el bautismo y el desierto (1:1–13). Delante, el llamado de los cuatro y la autoridad que enseña. El mandato no espera a que el lector se sienta listo.",
		revelacion: "μετανοεῖτε es presente imperativo: no un momento de lágrimas, una vuelta que se sostiene. πιστεύετε no es opinar que Dios existe; es fiarse del evangelio que se predica. βασιλεία τοῦ θεοῦ: el reinado de Dios se acercó; no una sensación interior ni un proyecto social. πεπλήρωται ὁ καιρός: el tiempo se ha cumplido. El perfecto de πληρόω cierra la puerta al aplazamiento. Los dos verbos van juntos: quien se vuelve sin creer no ha oído a Marcos; quien cree sin volverse ha fabricado un asentimiento.",
		doctrina: "Dios reina y llama. El pecado no se administra: se deja. Cristo no mejora el yo: exige fe en la buena noticia, y la buena noticia es él, el Hijo amado del bautismo (1:11). El pueblo de Dios empieza donde alguien se vuelve, no donde alguien se informa. Isaías 40:3 ya abrió el libro: preparad el camino del Señor. El Señor que llega no ofrece una técnica. En 7:34 dirá Éfata. Aquí, en Galilea, pide los dos verbos que el resto del evangelio no suaviza. Nadie se vuelve a un reino abstracto: se vuelve a este Jesús.",
		argumento: "El texto te niega el aplazamiento. Si el reino se acercó, no hay un tercer verbo. O te vuelves, o sigues de espaldas con un vocabulario piadoso. Status quaestionis: ¿es este anuncio una invitación blanda, o un decreto del Rey? Distingo: hay misericordia en el evangelio, y nace de que el tiempo se cumplió en Cristo, no de que el oyente esté listo. Reductio: si «más tarde» cabe, el καιρός no se ha cumplido, y Marcos ha mentido en el primer anuncio del Señor.",
		decision: "Esta semana, nombra delante de alguien de confianza de qué te estás volviendo —con nombre, no con niebla— y cree el evangelio en voz alta. Un paso. No una lista. El que añade un tercer verbo para aplazar el mandato todavía no ha oído a Galilea.",
		conclusion: "El evangelio no abre con un consuelo: abre con un mandato. El reino se acercó, y hay que volverse y creer. — Dr. Alejandro Sirit"
	},
	{
		slug: "juan-3",
		kicker: "De lo alto",
		ref: "Juan 3:1–8",
		title: "Nacer de nuevo",
		passage: "Había un hombre de los fariseos que se llamaba Nicodemo, un principal entre los judíos. Este vino a Jesús de noche, y le dijo: Rabí, sabemos que has venido de Dios como maestro; porque nadie puede hacer estas señales que tú haces, si no está Dios con él. Respondió Jesús y le dijo: De cierto, de cierto te digo, que el que no naciere de nuevo, no puede ver el reino de Dios.",
		voz: "De cierto, de cierto te digo, que el que no naciere de nuevo, no puede ver el reino de Dios.",
		ver: "Nicodemo ya sabe y ya enseña. Viene de noche, con el oficio intacto y la pregunta a medias. Jesús no le mejora el currículo: le pide nacer ἄνωθεν —de lo alto, de nuevo—. El reino no se ve por erudición. Hay que nacer. El diálogo no es un café teológico, sino el umbral, y el umbral no se negocia. Quien trata el nuevo nacimiento como metáfora de un cambio de hábitos todavía está de noche, aunque hable de Dios con soltura.",
		entorno: "Juan acaba de decir que Jesús conoce lo que hay en el hombre (2:24–25). Nicodemo es el caso. Fariseo, principal, maestro de Israel. El diálogo corre hasta 3:21, y luego Juan el Bautista cede: es menester que él crezca. El «de lo alto» de 3:3 no es un lema de enero, sino la condición para ver el reino. El evangelio se escribe a finales del siglo I, contra lecturas que recortan al Hijo, y el maestro que viene de noche es el espejo de todo oficio que sabe y aún no ha nacido.",
		revelacion: "ἄνωθεν carga los dos sentidos: de nuevo y de arriba. Ninguno es metáfora de hábitos. γεννηθῇ ἐξ ὕδατος καὶ πνεύματος: nacimiento que el hombre no se da. El viento πνεῦμα sopla donde quiere: la soberanía del Espíritu no se programa. Nicodemo oye «nacer» y pregunta por el vientre; Jesús oye a Ezequiel 36 y habla de agua y Espíritu. El malentendido no es torpeza, sino la carne intentando administrar lo que solo Dios da. El que no nace, no ve. El que no ve, enseña a ciegas.",
		doctrina: "El reino no se ve por erudición. Hay que nacer. Dios da vida; el pecado no se educa hasta la salvación. Cristo habla como quien está arriba y vino abajo: el que bajó del cielo (3:13) es el que exige el nacimiento, y el Hijo del hombre será levantado como la serpiente en el desierto (3:14–15; Nm. 21). Juan 3:16 no es un cartel suelto, sino la lógica del que debe nacer de lo alto porque el Hijo fue dado. La Iglesia no fabrica hijos: los recibe del Espíritu. El nuevo nacimiento no es un anexo de la cruz, sino lo que la cruz produce por el Espíritu.",
		argumento: "Si ya enseñas y todavía no has nacido, el texto te deja sin oficio. El problema no es que te falte un curso. Es que estás muerto y hablas de Dios. Status quaestionis: ¿es el nuevo nacimiento un hábito renovado, o una generación que el hombre no se da? Distingo: hay crecimiento, y hay nacimiento; el segundo no se improvisa con el primero. Reductio: si Nicodemo puede ver el reino por ser maestro de Israel, Jesús ha mentido, y Ezequiel 36 era un adorno.",
		decision: "Esta semana, deja de negociar el nuevo nacimiento como metáfora. Ora con alguien que ya cree, y pregunta en serio si has nacido de lo alto. Si la respuesta es niebla, no añadas un curso: pide el milagro que el viento da donde quiere, y no te administres un rito para no nacer.",
		conclusion: "Nicodemo ya sabe y ya enseña; de noche pregunta. Jesús no le mejora el oficio: le pide nacer de nuevo. — Dr. Alejandro Sirit"
	},
	{
		slug: "hechos-2",
		kicker: "La pregunta",
		ref: "Hechos 2:36–41",
		title: "¿Qué haremos?",
		passage: "Sepa, pues, ciertísimamente toda la casa de Israel, que a este Jesús a quien vosotros crucificasteis, Dios le ha hecho Señor y Cristo. Al oír esto, se compungieron de corazón, y dijeron a Pedro y a los otros apóstoles: Varones hermanos, ¿qué haremos?",
		ver: "El sermón atraviesa el corazón. No preguntan qué sentir: preguntan qué hacer. Pedro no suaviza: arrepentíos, bautícese cada uno en el nombre de Jesucristo para perdón de los pecados, y recibiréis el don del Espíritu Santo. La Iglesia no nace de un taller de autoestima. Nace de un corte, y el corte tiene nombre: a este Jesús a quien vosotros crucificasteis, Dios le ha hecho Señor y Cristo. Quien oye y no pregunta «qué haremos» aún no ha oído; ha asistido.",
		entorno: "Pentecostés. Jerusalén llena de oídos de muchas lenguas. Pedro interpreta a Joel y a David y clava el cargo. Hechos 1 espera la promesa; el 2 la recibe. El 42–47 muestra lo que nació: enseñanza, comunión, partimiento del pan, oraciones. Lucas escribe historia teológica para Teófilo, no un espectáculo. La Iglesia no sale de un retiro: sale de un corte. El que cite Pentecostés como clima de reunión ha cambiado de género.",
		revelacion: "κατενύγησαν τὴν καρδίαν: fueron atravesados el corazón. No un cosquilleo. μετανοήσατε —otra vez el imperativo, no un ánimo de grupo. βαπτισθήτω ἕκαστος: cada uno, no una muchedumbre que se emociona y se disuelve. εἰς ἄφεσιν τῶν ἁμαρτιῶν: hacia el perdón, no un rito vacío, ni un rito que salva por magia. El don del Espíritu no es premio de los avanzados: se recibe donde hay arrepentimiento y fe en el Señor que Dios ha hecho Cristo.",
		doctrina: "Cristo es Señor porque Dios lo hizo. El pecado tiene nombre y fecha: vosotros crucificasteis. La conversión se oye, se vuelve y se bautiza. El Espíritu es don, no premio. El sermón es cristología pública: el Jesús crucificado es el Señor del Salmo 110 y el Santo que no vio corrupción (Sal. 16). Pentecostés no desplaza a Cristo: lo declara. El Espíritu convence, como el Señor prometió en Juan 16:8. Los tres mil no recibieron un lema: recibieron al Señor y Cristo, el perdón y el don.",
		argumento: "Si oíste y no preguntas «qué haremos», no oíste. El texto no te deja en la emoción del sermón. Te pone en la calle hacia el agua. Status quaestionis: ¿es Pentecostés un espectáculo de poder, o el cumplimiento que produce arrepentimiento y bautismo? Distingo: hay poder, y hay corte; el segundo verifica al primero. Reductio: si el don se recibe sin μετανοήσατε, Pedro ha mentido, y Joel ha sido citado para un clima.",
		decision: "Si aún no has sido bautizado en el nombre de Jesucristo, habla esta semana con quien pueda administrarlo. Si ya lo fuiste, di a alguien el siguiente acto de obediencia, no un sentimiento. El que se queda en la emoción del sermón ha oído a Pedro como se oye un concierto.",
		conclusion: "Los que oyeron preguntaron qué debían hacer. Pedro no suaviza la respuesta. — Dr. Alejandro Sirit"
	},
	{
		slug: "juan-1",
		kicker: "Cristología",
		ref: "Juan 1:1–18",
		title: "El Verbo se hizo carne",
		passage: "En el principio era el Verbo, y el Verbo era con Dios, y el Verbo era Dios. Este era en el principio con Dios. Todas las cosas por él fueron hechas, y sin él nada de lo que ha sido hecho, fue hecho. En él estaba la vida, y la vida era la luz de los hombres. Y aquel Verbo fue hecho carne, y habitó entre nosotros (y vimos su gloria, gloria como del unigénito del Padre), lleno de gracia y de verdad.",
		ver: "El prólogo no es un villancico ni un poema para abrir el libro. Es la tesis: eternidad, creación, rechazo, tabernáculo y el Unigénito que declara al Padre. «En el principio» evoca Génesis 1, y no por casualidad. El Verbo no empieza en Belén. Los suyos no le recibieron: la cruz ya está en la apertura. Quien recorta 1:14 a diciembre no ha leído; ha celebrado un nacimiento sin oír al que era.",
		entorno: "Juan escribe contra lecturas que recortan al Hijo, a finales del siglo I. El 1:1–18 es el umbral de todo el evangelio. El testimonio del Bautista (1:6–8, 15) impide que el Verbo se vuelva una idea: hubo un hombre enviado. El 19 abre la narrativa. Colosenses 1 y Hebreos 1 leen el mismo Hijo. El que oye este prólogo como himno de fiesta y no como tesis ya ha elegido el calendario sobre el canon.",
		revelacion: "λόγος: no un lema. ἦν πρὸς τὸν θεόν: comunión, no soledad. θεὸς ἦν ὁ λόγος: identidad divina sin borrar la distinción. ἐσκήνωσεν: plantó tabernáculo; Éxodo 25 no era un museo. μονογενής: el Hijo único que ἐξηγήσατο —exegesó— al Padre. Nadie le ha visto. El Hijo le da a conocer. La carne no es disfraz. La deidad no se merma. El que niega uno de los dos no tiene al Cristo de este evangelio.",
		doctrina: "Cristo es Dios y está con Dios. La creación es suya. La encarnación es carne, no disfraz. La gloria se ve en el Unigénito. Nadie ha visto a Dios; el Hijo lo da a conocer. A los que le reciben, les da autoridad de ser hechos hijos de Dios, no de sangre ni de voluntad de varón, sino de Dios. El nuevo nacimiento de Juan 3 ya está aquí. El Verbo no mejora oficios. Da vida. El prólogo ya contiene la cruz: el rechazo. Y ya contiene la gloria: la del Unigénito.",
		argumento: "Quien recorta Juan 1:1 a un adorno de diciembre no ha leído. El texto no te deja un Jesús útil. Te deja al Verbo que te hizo y al que tus rechazos no deshacen. Status quaestionis: ¿es el Verbo un símbolo de iluminación, o Dios hecho carne? Distingo: hay luz, y hay Persona; la primera no sustituye a la segunda. Reductio: si 1:1 se suaviza para no ofender, ya se eligió otro señor, aunque se conserve el villancico.",
		decision: "Lee Juan 1:1–18 entero, en voz alta, dos veces esta semana. Escribe una frase: qué afirma de Cristo que tú habías dejado blando. El tratado del mes sostiene este mismo prólogo. El capítulo espera. No memorices el himno: óyelo hasta que el tabernáculo te deje sin un Jesús de diciembre.",
		conclusion: "Quien lo recorta a un versículo de diciembre no ha leído. Aquí hay eternidad, creación, rechazo, tabernáculo y el Unigénito que declara al Padre. — Dr. Alejandro Sirit"
	},
	{
		slug: "isaias-53",
		kicker: "Expiación · Siervo",
		ref: "Isaías 53",
		title: "Herido por nuestras rebeliones",
		passage: "Mas él herido fue por nuestras rebeliones, molido por nuestros pecados; el castigo de nuestra paz fue sobre él, y por su llaga fuimos nosotros curados. Todos nosotros nos descarriamos como ovejas, cada cual se apartó por su camino; mas Jehová cargó en él el pecado de todos nosotros.",
		ver: "El Siervo no es un poema de resiliencia. Carga lo que no es suyo. Hay herida, molido, cargo y resultado: paz, curación, justificación de muchos. Jehová quiso quebrantarlo. El silencio ante los trasquiladores no es estoicismo, sino obediencia. Quien recablea este canto como lección moral todavía no se ha puesto bajo la llaga. El «todos» no admite excepciones piadosas.",
		entorno: "Isaías 52:13–53:12 es el cuarto canto del Siervo. Israel esperaba un brazo visible. El texto pone un varón de dolores, despreciado, silencioso, sepultado con los ricos. El Gran Rollo de Isaías, copiado hacia el 125 a. C., ya trae estas líneas: Qumrán quita la coartada de un canto inventado después de Gólgota. Hechos 8 y 1 Pedro 2 no improvisan: leen esto en Cristo. El eunuco lee el rollo y Felipe le abre la boca.",
		revelacion: "נָשָׂא y סָבַל: llevar y soportar. אָשָׁם: ofrenda por la culpa. La sustitución no es un invento latino; está en el hebreo. הַפְגִּיעַ: Jehová quiso quebrantarlo. La cruz no es un accidente que Dios aprovechó. צַדִּיק: el justo siervo justificará a muchos. La curación nace de la herida ajena, no de la nuestra bien contada. El que llama «herida» a lo que el texto llama rebelión ha cambiado el vocabulario para no arrodillarse.",
		doctrina: "El pecado es rebelión y se carga. Dios no mira a otro lado: pone el pecado sobre el Siervo. Cristo justifica a muchos porque lleva iniquidades. El pueblo queda sano por llaga ajena, no por técnica interior. El cordero de Éxodo 12, el macho cabrío de Levítico 16, el justo de Isaías 53 y el Cordero de Apocalipsis 5 son un solo hilo. Jesús no cabe aquí como ejemplo de amor sin cargo. Cabe como el que fue hecho pecado por nosotros (2 Co. 5:21).",
		argumento: "Si tu cruz es un ejemplo de amor sin cargo, no es Isaías 53. El texto te quita el derecho de decir «yo me curo a mí mismo». Status quaestionis: ¿poema de resiliencia, o sustitución? Distingo: hay dolor, y hay cargo; el primero no agota al segundo. Reductio: si el Siervo no lleva iniquidades, el pueblo no queda sano, y Hechos 8 ha anunciado a otro Jesús.",
		decision: "Confiesa esta semana, a Dios y a una persona, un pecado que has llamado «herida» para no llamarlo rebelión. Nómbralo bajo la llaga del Siervo, sin eufemismo. Luego el capítulo entero. El tratado no sustituye a Isaías 53. Lo sirve, y se sienta atrás.",
		conclusion: "El Siervo carga lo que no es suyo. Hebreo, analogía de la fe y una cruz con nombre. — Dr. Alejandro Sirit"
	},
	{
		slug: "romanos-3",
		kicker: "Justificación",
		ref: "Romanos 3:21–26",
		title: "Justicia de Dios, sin la ley",
		passage: "Pero ahora, aparte de la ley, se ha manifestado la justicia de Dios, testificada por la ley y por los profetas; la justicia de Dios por medio de la fe en Jesucristo, para todos los que creen en él.",
		ver: "Toda boca se cerró (3:19). Entonces —pero ahora— se manifiesta δικαιοσύνη θεοῦ, sin la ley como escalera, en la sangre de Cristo, para que Dios sea justo y justificador. El «aparte» no despide a Moisés: lo pone a testificar. Habacuc 2:4 ya estaba en 1:17. Llega aquí a su claridad. El que mezcla su hoja de servicios con este párrafo todavía tiene la boca abierta.",
		entorno: "Pablo acaba de poner a judío y gentil bajo pecado. Nadie llega a 3:21 sin haber oído que no hay justo ni aun uno. El «pero ahora» no es un cambio de humor, sino el tiempo de la cruz. El 27–31 pregunta dónde está la jactancia. El 4 trae a Abraham, no como héroe de hábitos, sino como el que creyó a Dios y le fue contado por justicia. La carta entera cuelga de este ahora.",
		revelacion: "ἱλαστήριον: propiciatorio, el mueble de Éxodo 25 y de Levítico 16, el lugar de la sangre. Cristo es puesto por Dios como ese lugar. ἀπολύτρωσις: redención, manumisión. Hay precio. πάρεσις: Dios había pasado por alto pecados anteriores. ἐν τῷ νῦν καιρῷ: ahora demuestra su justicia. δικαιοῦντα τὸν ἐκ πίστεως Ἰησοῦ: justifica al que es de la fe de Jesús. El Padre no dejó de ser justo para poder perdonar.",
		doctrina: "La justicia de Dios no es un ánimo. Se manifiesta en Cristo. La fe no es meritoria: recibe. Dios no deja de ser justo para perdonar: justifica por la sangre. No hay distinción: todos pecaron. Romanos 3:26 impide dos herejías: la del perdón sin juicio, y la del juicio sin cruz. El Hijo es el lugar donde la ira y la misericordia se encuentran sin mentira. El evangelio que salva al que ya mejoró no es este evangelio.",
		argumento: "Si tu evangelio salva sin propiciatorio, no es Romanos 3. El texto cierra la boca que aún quiere aportar ley como moneda. Status quaestionis: ¿perdón barato, o justificación por la sangre? Distingo: hay ley que testifica, y hay ley que no justifica. Reductio: si la jactancia no se excluyó, 3:27 ha fallado, y Habacuc entra en vano.",
		decision: "Esta semana, deja de mezclar tu hoja de servicios con la justificación. Di a alguien: soy justificado por la fe en Jesús, sin la ley. Luego lee 3:21–26 dentro de 3:9–31. El tratado del mes sostiene este mismo párrafo. RevelatiO abre el capítulo.",
		conclusion: "Griego, Habacuc, el propiciatorio y un Dios que es justo y justifica. — Dr. Alejandro Sirit"
	},
	{
		slug: "2-pedro-1",
		kicker: "Permanecer",
		ref: "2 Pedro 1:1–11",
		title: "Añadid a vuestra fe",
		passage: "Simón Pedro, siervo y apóstol de Jesucristo, a los que habéis alcanzado, por la justicia de nuestro Dios y Salvador Jesucristo, una fe igualmente preciosa que la nuestra: Gracia y paz os sean multiplicadas, en el conocimiento de Dios y de nuestro Señor Jesús. Como todas las cosas que pertenecen a la vida y a la piedad nos han sido dadas por su divino poder, mediante el conocimiento de aquel que nos llamó por su gloria y excelencia, por medio de las cuales nos ha dado preciosas y grandísimas promesas, para que por ellas llegaseis a ser participantes de la naturaleza divina, habiendo huido de la corrupción que hay en el mundo a causa de la concupiscencia; vosotros también, poniendo toda diligencia por esto mismo, añadid a vuestra fe virtud; a la virtud, conocimiento; al conocimiento, dominio propio; al dominio propio, paciencia; a la paciencia, piedad; a la piedad, afecto fraternal; y al afecto fraternal, amor. Porque si estas cosas están en vosotros, y abundan, no os dejarán ociosos ni sin fruto en cuanto al conocimiento de nuestro Señor Jesucristo. Pero el que no tiene estas cosas tiene la vista muy corta; es ciego, habiendo olvidado la purificación de sus antiguos pecados. Por lo cual, hermanos, tanto más procurad hacer firme vuestra vocación y elección; porque haciendo estas cosas, no caeréis jamás. Porque de esta manera os será otorgada amplia y generosa entrada en el reino eterno de nuestro Señor y Salvador Jesucristo.",
		ver: "Pedro pide añadir a la fe, a costa propia, una cadena de siete eslabones. No es un cartel de virtudes. Es lo que el capítulo 2 va a exigir cuando desenmascare a quienes prometen libertad siendo esclavos de corrupción. Dios dio todo lo que concierne a la vida y a la piedad; ahora se suministra, se costea, se añade. El que no añade no es humilde. Es ciego, y se olvidó de la purificación de sus antiguos pecados. La fe que no se ejercita se vuelve estéril.",
		entorno: "Segunda carta. Pedro va a morir (1:14). Hay maestros que prometen libertad y son esclavos. El 1:3–11 es la pendiente; el 1:16–21, el origen de la profecía; el capítulo 2 espera con los falsos. El 1 no es un listado de hábitos, sino lo que evita caer en esa esclavitud. Se escribe a los que han recibido una fe igualmente preciosa: creyentes que pueden volverse ociosos y llamar a esa ociosidad gracia.",
		revelacion: "ἐπιχορηγήσατε: suministrad, costead. Añadir cuesta. σπουδὴν πᾶσαν: toda diligencia, toda prisa; no un ánimo vago. ἀρετή, γνῶσις, ἐγκράτεια, ὑπομονή, εὐσέβεια, φιλαδελφία, ἀγάπη: la cadena no es un menú. μυωπάζων: corto de vista el que no añade. βεβαίαν: hacer firme el llamamiento y la elección. Se confirma en el camino, no en el eslogan. Participar de la naturaleza divina no es fusión panteísta, sino huir de la corrupción.",
		doctrina: "Dios dio todo lo que concierne a la vida y a la piedad. El creyente no improvisa el carácter: lo suministra. La elección se confirma en el camino, no en el eslogan. El pueblo que no añade se vuelve estéril. Las virtudes no sustituyen a Cristo: las da el que ya nos dio todo. Santiago 2 y Judas 3 leen el mismo peligro: llamar fe a un asentimiento que no se mueve, y llamar libertad a la esclavitud. Este tomo, en la colección, se llama La fe no basta, y no discute a Pablo: desnuda al que cita a Pablo para no añadir.",
		argumento: "La fe que no se ejercita no es humildad. Es ceguera. El texto te niega el «ya creí, ya está». Status quaestionis: ¿ociosidad piadosa, o diligencia que costea? Distingo: hay descanso en Cristo, y hay suministro; el primero no anula al segundo. Reductio: si no añadir es gracia, el capítulo 2 no desenmascara a nadie, y Pedro ha escrito en vano.",
		decision: "Elige un eslabón para esta semana. Escríbelo en el cuaderno y dilo a alguien de confianza. Uno. Costealo. El que elige siete no ha elegido ninguno. El que no lo dice a un testigo lo ha dejado en el eslogan.",
		conclusion: "Siete eslabones y una sola pendiente. La fe que no añade se vuelve estéril. — Dr. Alejandro Sirit"
	},
	{
		slug: "2-corintios-5",
		kicker: "Estudio",
		ref: "2 Corintios 5:17–21",
		title: "Nueva criatura",
		passage: "De modo que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas. Y todo esto proviene de Dios, quien nos reconcilió consigo mismo por Cristo, y nos dio el ministerio de la reconciliación. Al que no conoció pecado, por nosotros lo hizo pecado, para que nosotros fuésemos hechos justicia de Dios en él.",
		ver: "Nueva criatura no es un yo recableado ni un tatuaje de conversión. Es reconciliación. Dios estaba en Cristo reconciliando al mundo a sí, no imputándole sus pecados, y nos hizo embajadores. Nadie llega al versículo 17 sin el 21. El que usa «nueva criatura» para sentirse otro sin haberse reconciliado ha tomado el lema y ha dejado el ministerio.",
		entorno: "Pablo defiende el ministerio, hacia el 55–56, ante una Corinto querida y herida que mide a los siervos por apariencia. El tribunal de Cristo está en 5:10. El amor de Cristo nos constriñe. La nueva creación aparece donde la muerte de uno es por todos. El 6:1 ruega que no se reciba en vano la gracia. El género es carta: apología que se vuelve evangelio, no un eslogan de enero.",
		revelacion: "καινὴ κτίσις: creación nueva, no un yo recableado. καταλλαγή: reconciliación. πρεσβεύομεν: somos embajadores; el mensaje no se improvisa. ἁμαρτίαν ἐποίησεν: al que no conoció pecado, por nosotros lo hizo pecado. δικαιοσύνη θεοῦ ἐν αὐτῷ: justicia de Dios en él. Isaías 53 está debajo. La nueva creación de Génesis 1 y de Apocalipsis 21 asoma aquí: si alguno está en Cristo. No es un tatuaje. Es el cambio de reino que la cruz compró.",
		doctrina: "Estar en Cristo es el umbral. El pecado de él no era suyo. Nuestra justicia no es nuestra. El pueblo no improvisó un mensaje: recibió uno de reconciliación. La justicia de Dios en él es Romanos 3 leído desde el ministerio. El embajador no recablea al enemigo: le ruega que se reconcilie. El tribunal de 5:10 impide que la nueva creación se vuelva un clima interior sin cuerpo y sin juicio.",
		argumento: "Si «nueva criatura» te deja igual de enemigo y solo más inspirado, no leíste el versículo 21. Status quaestionis: ¿recableado del yo, o reconciliación por el que fue hecho pecado? Distingo: hay novedad, y hay cargo; la primera nace del segundo. Reductio: si el 21 no está, el 17 es un lema, y el embajador no tiene nada que decir.",
		decision: "Esta semana, habla como embajador una vez: di a alguien concreto que Dios llama a reconciliarse, no a recablearse. Un nombre. Un ruego. No un hilo. El que se queda en el 17 sin el 21 ha convertido la nueva creación en un espejo.",
		conclusion: "No es un yo recableado, sino reconciliación, y somos embajadores. — Dr. Alejandro Sirit"
	},
	{
		slug: "filipenses-2",
		kicker: "Himno",
		ref: "Filipenses 2:5–11",
		title: "El himno del Siervo",
		passage: "Haya, pues, en vosotros este sentir que hubo también en Cristo Jesús, el cual, siendo en forma de Dios, no estimó el ser igual a Dios como cosa a que aferrarse, sino que se despojó a sí mismo, tomando forma de siervo, hecho semejante a los hombres; y estando en la condición de hombre, se humilló a sí mismo, haciéndose obediente hasta la muerte, y muerte de cruz. Por lo cual Dios también le exaltó hasta lo sumo, y le dio un nombre que es sobre todo nombre, para que en el nombre de Jesús se doble toda rodilla de los que están en los cielos, y en la tierra, y debajo de la tierra; y toda lengua confiese que Jesucristo es el Señor, para gloria de Dios Padre.",
		ver: "El himno humilla al yo antes de exaltarlo. Forma de siervo, muerte de cruz, el Nombre sobre todo nombre. Filipenses 2 no se escribió para que el seminario aplaudiera la kénosis. Se escribió para que Evodia y Síntique dejaran de pelearse el primer asiento. El credo está metido en la ética. Quien canta 2:9–11 sin 2:7 no ha leído: ha cantado.",
		entorno: "Filipos, iglesia querida con grietas de vanagloria (2:1–4). Pablo escribe desde la cárcel, hacia el 60–62. El himno no es adorno, sino la medida de la mente de la iglesia. El 2:12–18 pide ocupar la salvación con temor. Timoteo y Epafrodito encarnan el himno. El género es carta: el carmen Christi sirve a un pleito concreto, no a un tratado de cristología suelto.",
		revelacion: "μορφὴ θεοῦ / μορφὴ δούλου: forma de Dios, forma de siervo. No teatro: naturaleza y obediencia. ἐκένωσεν: se vació, no dejó de ser quién es; tomó lo que no debía. μέχρι θανάτου δὲ σταυροῦ: hasta la muerte, y muerte de cruz. La infamia es el punto, no un detalle. διὸ καὶ ὁ θεὸς αὐτὸν ὑπερύψωσεν. πᾶν γόνυ κάμψῃ: toda rodilla. Isaías 45:23 entra. Escatología, no eslogan.",
		doctrina: "Cristo es igual a Dios y se hizo siervo. La cruz es obediencia, no accidente. La exaltación es del Padre. Toda rodilla es escatología, no eslogan. El Nombre sobre todo nombre es YHWH dado al Hijo. El sentir que se pide a Filipos es este Cristo, no un talante amable. El himno no es un poema de autoayuda sobre bajar el ego. Es el camino del Hijo: igualdad no aferrada, siervo, cruz, exaltación.",
		argumento: "Si tu «sentir de Cristo» no baja, no es este himno. El texto no te pide una marca de siervo: te pide la forma. Status quaestionis: ¿himno de kénosis para el seminario, o medida de la mente de Filipos? Distingo: ἐκένωσεν no es dejar de ser quién es. Reductio: si se canta la exaltación y se evita la forma de siervo, se ha cambiado de señor.",
		decision: "Cede un derecho esta semana —uno que te estaba inflando— y no lo anuncies. Hazlo porque el himno manda. Evodia y Síntique no necesitan otro taller: necesitan este Cristo. El que anuncia el despojo ya lo ha convertido en teatro.",
		conclusion: "El himno que humilla al yo antes de exaltarlo. — Dr. Alejandro Sirit"
	},
	{
		slug: "santiago-1",
		kicker: "Espejo",
		ref: "Santiago 1:19–27",
		title: "Pronto para oír",
		passage: "Por esto, mis amados hermanos, todo hombre sea pronto para oír, tardo para hablar, tardo para airarse; porque la ira del hombre no obra la justicia de Dios. Por lo cual, desechando toda inmundicia y abundancia de malicia, recibid con mansedumbre la palabra implantada, la cual puede salvar vuestras almas. Pero sed hacedores de la palabra, y no tan solamente oidores, engañándoos a vosotros mismos. Porque si alguno es oidor de la palabra y no hacedor, este es semejante al hombre que considera en un espejo su rostro natural; porque él se considera a sí mismo, y se va, y luego olvida cómo era. Mas el que mira atentamente en la ley perfecta, la de la libertad, y persevera en ella, no siendo oidor olvidadizo, sino hacedor de la obra, este será bienaventurado en lo que hace. Si alguno se cree religioso entre vosotros, y no refrena su lengua, sino que engaña su corazón, la religión del tal es vana. La religión pura y sin mácula delante de Dios el Padre es esta: Visitar a los huérfanos y a las viudas en sus tribulaciones, y guardarse sin mancha del mundo.",
		ver: "El oyente que se mira y se va. Oír y no hacer es engaño de sí, no un retraso inocente. El altar no es el sentimiento de haber oído, ni la liturgia de un estudio bien anotado. Es el hombre que permanece en la ley perfecta, la de la libertad, y es hacedor de la obra. El que cierra el cuaderno sin acto ha vuelto a mirarse y se ha ido. Esta escuela, si no decide, es el hombre del espejo.",
		entorno: "Santiago, siervo de Dios y del Señor Jesucristo, escribe a las doce tribus en la dispersión, quizá en los años 40–50. Creyentes pobres y tentados, que oyen mucho y hacen poco. El 1:19–21 pide recibir con mansedumbre la palabra implantada. El 26–27 es la religión pura. La ira del hombre no obra la justicia. La lengua espera en el capítulo 3. El género es carta sapiencial: espejo, no consigna.",
		revelacion: "ποιηταὶ λόγου: hacedores de la palabra, no solamente oidores. παραλογιζόμενοι ἑαυτούς: engañándoos a vosotros mismos; el retraso no es inocente. ἔσοπτρον: espejo; el rostro natural se ve y se olvida. νόμον τέλειον τὸν τῆς ἐλευθερίας: la ley perfecta, la de la libertad, no antinomia. Permanecer, no huir. El Padre de las luces nos engendró por la palabra de verdad (1:18). El espejo no es un método, sino oír a Cristo y no irse.",
		doctrina: "La Palabra que se oye obliga. El autoengaño es liturgia de los que solo escuchan. La libertad no es huir de la ley, sino permanecer en ella y ser bienaventurado en el hacer. Mateo 7:24–27 está debajo: el que oye y no hace es casa sobre arena. El Señor que dijo Éfata no deja el oído abierto para el archivo. Lo deja abierto para el acto. C.R.I.S.O.L.™, expuesto en El Altar del Espejo, es la compuerta de este eslabón.",
		argumento: "El estudio que no decide es el hombre del espejo. Este sitio no te deja el pasaje en la cabeza. Status quaestionis: ¿retraso inocente, o engaño de sí? Distingo: hay oír, y hay hacer; el primero sin el segundo es παραλογισμός. Reductio: si el cuaderno basta, Santiago ha llamado bienaventuranza a lo que es olvido, y el espejo no era altar: era tocador.",
		decision: "Lo que este texto te mostró, hazlo antes de siete días. Anótalo. Dilo a un testigo. Si se queda en el cuaderno sin acto, volviste a mirarte y te fuiste. Queda prohibido un «hoy muero a…» que el pasaje no conjuga. El verbo aquí es hacer, no morir a un ego genérico.",
		conclusion: "Oír y no hacer es engaño de sí, no un retraso inocente. — Dr. Alejandro Sirit"
	},
	{
		slug: "romanos-12",
		kicker: "Culto",
		ref: "Romanos 12:1–2",
		title: "No os conforméis",
		passage: "Así que, hermanos, os ruego por las misericordias de Dios, que presentéis vuestros cuerpos en sacrificio vivo, santo, agradable a Dios, que es vuestro culto racional. No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento.",
		ver: "La mente nueva es culto a Dios, no un recableado interior de moda. El cuerpo se presenta. El siglo presiona. Hay un no y un sí. El «así que» no es un giro moralista, sino consecuencia de once capítulos de misericordia. Nadie presenta el cuerpo si aún discute la justificación como si fuera un taller. Las misericordias preceden al mandato. Quien convierte este párrafo en un manual de hábitos ha cortado el «por las misericordias».",
		entorno: "Romanos 9–11 acaba de tratar a Israel y la misericordia. El 12:1–2 es el umbral de la ética. Luego el cuerpo, los dones, el amor, las autoridades. El culto sale del templo y se pone sobre el cuerpo de los hermanos, en Roma, bajo imperio. El género es carta: exhortación que nace de la doctrina, no un anexo moralista pegado a once capítulos de teología.",
		revelacion: "λογικὴν λατρείαν: culto razonable, de la Palabra. El cuerpo es el altar. συσχηματίζεσθε: no os ensambléis al esquema de este siglo. μεταμορφοῦσθε: sed transformados; pasiva, Dios obra; presente, se sostiene. ἀνακαινώσει τοῦ νοός: renovación de la mente, no un recableado interior de moda. El sacrificio vivo es posible porque el Hijo se ofreció. El siglo tiene molde; Cristo tiene forma de siervo.",
		doctrina: "Las misericordias preceden al mandato. El culto es el cuerpo. El siglo tiene molde. Dios renueva la mente. El pueblo discernirá la voluntad cuando no se deje vaciar en el molde. El sacrificio vivo es posible porque el Hijo se ofreció (Ro. 3:25; 8:32; Ef. 5:2). La mente renovada discierne porque ha oído las misericordias, no porque haya leído un manual de hábitos. El pueblo no se conforma: se presenta.",
		argumento: "Si tu culto es emoción sin cuerpo y sin no al siglo, no es Romanos 12. Status quaestionis: ¿recableado interior, o presentación del cuerpo por las misericordias? Distingo: hay transformación, y hay molde; la primera no se fabrica ensamblándose al segundo. Reductio: si el «así que» se corta, el mandato nace de la voluntad, no de la misericordia, y se ha vuelto a la ley.",
		decision: "Nombra un molde de este siglo al que te estás adaptando. Preséntalo esta semana: un no concreto, dicho a alguien. El cuerpo es el altar. El que se queda en la emoción del culto sin un no ha oído Romanos 12 como se oye un himno, no como se oye un ruego.",
		conclusion: "La mente nueva es culto a Dios, no un recableado interior. — Dr. Alejandro Sirit"
	},
	{
		slug: "juan-14",
		kicker: "Camino",
		ref: "Juan 14:1–6",
		title: "El único camino",
		passage: "Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.",
		voz: "Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.",
		ver: "Jesús no señala un camino. Él es el camino, la verdad y la vida. Tomás pregunta y recibe una persona, no un mapa. «No se turbe vuestro corazón»: el Padre tiene casa, y ir al Padre es el asunto, no un atajo espiritual genérico. La exclusión no es un tono. Es la gramática: nadie viene al Padre sino por mí. Quien suaviza «nadie viene» para no ofender ya ha elegido ofender al que habla.",
		entorno:
      "Esto no se oye como un lema suelto. En el capítulo 13 Jesús lava los pies de los discípulos, Judas sale a la noche, y el Señor da el mandamiento nuevo: que os améis unos a otros. El 14 abre con un consuelo concreto: no se turbe vuestro corazón. Hay casa en el Padre, y Él va a prepararla. Tomás pregunta el camino porque no sabe a dónde va el Señor, y recibe una persona, no un diagrama: yo soy el camino, y la verdad, y la vida. Más adelante Jesús promete otro Paráclito, el Espíritu de verdad, y promete que ese Espíritu les enseñará y les recordará lo que Él ha dicho. Felipe pedirá ver al Padre. El discurso de despedida no es un mapa de caminos espirituales, sino el Señor hablando a once hombres que están a punto de verlo morir.",
		revelacion: "ἐγώ εἰμι: yo soy. No señala un camino. Él es el camino. ἡ ὁδός, ἡ ἀλήθεια, ἡ ζωή —artículos. El camino, la verdad, la vida. No un recurso entre otros. οὐδεὶς ἔρχεται πρὸς τὸν πατέρα εἰ μὴ δι’ ἐμοῦ: nadie viene al Padre sino por mí. Exclusión clara. παράκλητος: el Espíritu Santo, prometido en este mismo capítulo, no abre un segundo camino: glorifica a este (16:13–14).",
		doctrina: "El Padre se alcanza por el Hijo. Cristo es verdad, no un recurso. La vida no se añade al camino: es Él. El pueblo no inventa sendas paralelas. Hebreos 10:19–20 llama a su carne el velo recién abierto. Hechos 4:12 niega otro nombre. El Paráclito no es un atajo, sino el que toma de lo que es de Cristo y lo hace saber. Tomás recibió una persona, no un diagrama. «Muchos caminos» no sobrevive a Juan 14:6.",
		argumento: "«Muchos caminos» no sobrevive a Juan 14:6. El texto te obliga a ofender o a creer. Status quaestionis: ¿un recurso entre otros, o el único camino al Padre? Distingo: hay gentileza, y hay verdad; la primera no autoriza a recortar οὐδεὶς. Reductio: si hay otro camino, Tomás recibió un mapa, y el velo de Hebreos 10 era un adorno.",
		decision: "Esta semana, deja de suavizar «nadie viene». Di a una persona, sin grosería y sin rebaja, que el Padre se alcanza por Jesús. El que busca un mapa todavía no ha oído a Tomás. El que ha oído, habla, o sigue de noche con un vocabulario inclusivo.",
		conclusion: "Él es el camino, la verdad y la vida. — Dr. Alejandro Sirit"
	},
	{
		slug: "salmo-23",
		kicker: "Pastor",
		ref: "Salmo 23",
		title: "Nada me faltará",
		passage: "Jehová es mi pastor; nada me faltará. En lugares de delicados pastos me hará descansar; junto a aguas de reposo me pastoreará. Confortará mi alma; me guiará por sendas de justicia por amor de su nombre. Aunque ande en valle de sombra de muerte, no temeré mal alguno, porque tú estarás conmigo; tu vara y tu cayado me infundirán aliento. Aderezas mesa delante de mí en presencia de mis angustiadores; unges mi cabeza con aceite; mi copa está rebosando. Ciertamente el bien y la misericordia me seguirán todos los días de mi vida, y en la casa de Jehová moraré por largos días.",
		ver: "El valle se atraviesa con el Pastor, no se medita para que desaparezca. El «tú» llega en el valle: de tercera persona —Jehová es mi pastor— a segunda —tú estás conmigo—. La mesa es en presencia de enemigos. El bien y el hesed persiguen; no se coleccionan como frases. Quien usa este salmo para negar el valle lo invierte. El texto pone al Pastor dentro, no al valle fuera.",
		entorno: "Salmo de David. Pastoreo real, no postal. El 22 es el clamor del abandonado; el 23, el Pastor; el 24, el Rey de gloria. El pueblo que camina valles, no el que colecciona frases. Género: salmo de confianza. Poesía que se reza, no que se recorta para un funeral o un bordado. La vara y el cayado son disciplina y sostén, no solo caricia.",
		revelacion: "יְהוָה רֹעִי: YHWH es mi pastor. El Nombre, no un arquetipo. לֹא אֶחְסָר: nada me faltará. La falta se mide por Él, no por el siglo. גֵּיא צַלְמָוֶת: valle de sombra profunda. El valle está. El Pastor también. שֵׁבֶט y מִשְׁעֶנֶת: vara y cayado. אַךְ טוֹב וָחֶסֶד יִרְדְּפוּנִי: el bien y el hesed persiguen. El pueblo no es abandonado a su mindfulness. Es perseguido por la misericordia del pacto.",
		doctrina: "El Señor pastorea. La falta se mide por Él, no por el siglo. La muerte tiene valle y no tiene la última palabra. Juan 10: el Buen Pastor da la vida por las ovejas. Hebreos 13:20: el Dios de paz trajo de los muertos a nuestro Señor Jesucristo, el gran Pastor. Apocalipsis 7:17: el Cordero los pastoreará. El Salmo 23 no es mindfulness hebreo. Es el Nombre que pastorea, y el Hijo que entra al valle hasta la cruz, y sale.",
		argumento: "Si usas el Salmo 23 para negar el valle, lo invertiste. El texto pone al Pastor dentro, no al valle fuera. Status quaestionis: ¿postal de consuelo, o pastoreo del Nombre en la sombra? Distingo: hay descanso, y hay valle; el primero no evapora al segundo. Reductio: si el valle se medita hasta desaparecer, el «tú estás conmigo» sobra, y Juan 10 da la vida por un paisaje.",
		decision: "Donde ahora tienes miedo, nombra al Pastor en segunda persona esta semana: «tú estás conmigo». Dilo a alguien que camine el mismo valle. El que reza el salmo para que el valle se vaya aún no ha llegado al «tú». El que ha llegado, no niega la sombra: la atraviesa.",
		conclusion: "El valle se atraviesa con el Pastor, no se medita para que desaparezca. — Dr. Alejandro Sirit"
	},
	{
		slug: "genesis-3",
		kicker: "Laboratorio I",
		ref: "Génesis 3",
		title: "La primera hermenéutica invertida",
		passage: "Pero la serpiente era astuta, más que todos los animales del campo que Jehová Dios había hecho; la cual dijo a la mujer: ¿Conque Dios os ha dicho: No comáis de todo árbol del huerto?",
		voz: "No comáis de todo árbol del huerto",
		ver: "El capítulo no arranca con una caída: arranca con una conversación sobre un texto. Hay cuatro bocas —la serpiente, la mujer, el hombre y Jehová Dios— y el verbo decisivo del versículo 1 no es «comer», sino «dijo». La primera herida es hermenéutica.\n\nLa serpiente no niega: tuerce. Convierte el don en veto, y «De todo árbol del huerto podrás comer» se oye como «¿No comáis de todo?». El אַף —ʾap̄ kî, «conque»— no duda del Mandador; duda del tenor y pone el mandato entre comillas. Esa es la primera hermenéutica invertida.\n\nLa mujer no restaura lo oído. Resume mal, añade «ni le tocaréis» y suaviza la muerte: ya no es «ciertamente morirás». Luego la contradicción se instala, nítida: No moriréis. Tres gestos de glosa preceden a una sola mordedura.\n\nLos verbos de 3:6 caen en cadena: vio, tomó, comió, dio, comió. El hombre, durante la tentación, no dice nada; el silencio no es ausencia, es complicidad muda. El juicio sigue el orden de la transgresión —serpiente, mujer, hombre— y, después del veredicto, tres gestos que el capítulo no deja en suspenso: el hombre nombra a Eva, Dios viste con túnicas de pieles, y los querubines guardan el camino del árbol de la vida.",
		entorno: "El género es narración primordial: historia del pacto, no mito etiológico ni fábula de autoestima, y menos un Enuma Elish con nombres hebreos. En el Edén hay don, mandato y cabeza. Los personajes son personas; la serpiente es criatura hecha, del campo, que habla. Lo que no se elogia no está aprobado.\n\nEl Sitz inmediato es Génesis 2:16–17: dos infinitivos absolutos, don y muerte. «De todo árbol… ciertamente morirás». El oído que entre por 3:1 sin ese mandato no oye la glosa: oye un diálogo suelto. El 2:25 cose lo que el 3:1 va a rasgar: estaban desnudos —עֲרוּמִּים— y no se avergonzaban; la serpiente era עָרוּם. El hebreo no disimula el parentesco, y el que aplana esa costura ya interpretó.\n\nEl oficio se invierte. Génesis 1:28 da dominio sobre los animales; en 3:1 el animal habla y el hombre calla. Génesis 2:15 pone al hombre a guardar el huerto; en 3:24 los querubines guardan el camino. El «por tanto» de esta narración no es una moraleja extraída, sino el acto de Dios y la respuesta de los testigos.",
		revelacion: "El אַף es la primera hermenéutica de rebelión. No se ataca al que manda: se duda de lo mandado. נָחָשׁ es serpiente, criatura, no símbolo suelto; עָרוּם y עֵירֻם —astuta y desnudos— se oyen juntos antes de cualquier doctrina. La serpiente jamás pronuncia el Nombre: dice «Dios». La mujer, al responder, ya ha cedido el terreno: tampoco nombra a Jehová.\n\nלֹא־מוֹת תְּמֻתוּן no es una negación nueva, sino el mandato de 2:17 puesto del revés, con la misma raíz y el mismo infinitivo, de modo que la contradicción se viste de corrección. כֵּאלֹהִים no promete deidad ontológica: promete el oficio de legislar el bien y el mal. Eso es lo que se muerde.\n\nחַוָּה no nace de la hoja de higuera. El hombre la nombra después de oír 3:15, madre de todos los vivientes, porque la simiente —זֶרַע— ya ha sido anunciada, y el que herirá la cabeza —la LXX oye αὐτός— no empata con el calcañar. שׁוּף hiere; cabeza y calcañar no son el mismo golpe. עָפָר, el polvo, nombra la materia del juicio, no un ánimo.",
		doctrina: "De este párrafo, y no de un sistema traído de otra página, se oye qué se afirma de Dios, del pecado, de Cristo y del pueblo. Dios habla, viste, pone enemistad y anuncia la simiente. El pecado tuerce la Palabra antes de morder, cose hojas, se esconde y acusa. Cristo está en la simiente que herirá la cabeza. El pueblo es expulsado y cubierto.\n\nLa analogía antecedente oye solo Génesis 1–2: don, imagen, mandato, desnudez sin vergüenza, oficio de guardar. Eso basta para oír la transgresión. Quien llene esas cuatro voces con Calcedonia antes de oír a Moisés usa a Moisés como ventrílocuo.\n\nLa analogía plena se etiqueta y llega después: Romanos 5:12–19, 1 Corintios 15:21–22, Filipenses 2, Romanos 16:20, Apocalipsis 12:9. El protoevangelio se oye como promesa de simiente y de herida, no como folleto de soteriología. El que predica un ordo salutis en 3:6 aún no ha hecho Doctrina: ha hecho contrabando.",
		argumento: "La cuestión que hay que plantear es esta: ¿es Génesis 3 saga etiológica, mito de origen, o historia del pacto quebrantado?\n\nHay etiología literaria —el texto explica por qué hay dolor, tierra dura, querubines— y no hay mito ontológico. El género es narración, no reportaje moderno, y eso no la vuelve fábula. Mateo 19:4–6: Jesús toma Génesis 2 como Palabra del Creador, no como poema tribal. Oseas 6:7 nombra a Adán como transgresor del pacto.\n\nLa fuente es el texto. Wellhausen y Gunkel no legislan. Ireneo, Adversus Haereses III.23, oye la recapitulatio y no sustituye al párrafo. Calvino, Institución II.i, ata la caída a la cabeza. Hamilton sirve el hebreo; no legisla.\n\nSi la serpiente dice verdad, Dios miente. Si Adán no cayó, Cristo no es último Adán: Romanos 5 compara al Hijo con una alegoría. El criticismo que disuelve Génesis 3 disuelve el evangelio. La forma cultual de 3:1, hoy, no pregunta por el fruto: pregunta «¿Conque esto ocurrió?»",
		decision: "El indicativo no es «fuisteis informados». Dios cubre, pone enemistad y anuncia la simiente. Nadie mortifica para unirse: se mortifica porque ha sido hallado y vestido.\n\nQueda prohibido «hoy muero a la fruta», porque ese verbo no está. El verbo de 3:1 es la glosa: el אַף que puso el mandato entre comillas. Se toma un mandato de esta semana que se ha suavizado, y se le quita la partícula.\n\n«Hoy muero a las hojas de higuera» sí se conjuga: 3:7 las nombra. El escondite de 3:8 también, y la acusación de 3:12. Se leen y se nombran; no se importa un ego genérico.\n\nUn acto, no una lista: leer Génesis 3 entero, en voz alta; confesar delante de un testigo la negociación; quitar el אַף de un mandato que esta semana se ha puesto entre comillas. C.R.I.S.O.L.™, expuesto en El Altar del Espejo, guarda este eslabón: no es un método segundo.",
		conclusion: "Antes de que hubiera ídolo de madera, hubo glosa. El primer atentado contra la Palabra no fue un silencio: fue un comentario. — Dr. Alejandro Sirit"
	},
	{
		slug: "salmo-22",
		kicker: "Laboratorio II",
		ref: "Salmo 22",
		title: "El justo rodeado",
		passage: "Dios mío, Dios mío, ¿por qué me has desamparado? ¿Por qué estás tan lejos de mi salvación, y de las palabras de mi clamor?",
		voz: "Dios mío, Dios mío, ¿por qué me has desamparado? ¿Por qué estás tan lejos de mi salvación, y de las palabras de mi clamor?",
		ver: "Se oye el salmo entero: queja, confianza, proclamación. Cambio de persona. Inclusión. El «yo» no es un diario suelto. Hay abandono, manos y pies, sorteo de vestiduras, voto de alabanza ante la asamblea. Quien se lleva solo el versículo 1 aún no ha oído el 24: no me has despreciado ni abominado. El clamor no es el final. El abandonado promete anunciar el Nombre a sus hermanos, y Hebreos 2:12 oye eso en Cristo.",
		entorno: "Género de lamento real. Culto. No es crónica del Gólgota escrita por adelantado como reportaje, sino oración que el Espíritu destinó al Gólgota. David primero. El Hijo de David con autoridad canónica. El paralelismo hebreo es la gramática: el segundo miembro no rellena; estrecha, invierte o escala. El 22 no viaja solo: el 23 es el Pastor, el 24 el Rey. Mateo 27 no cita un adorno. El pueblo a quien se escribe es la asamblea, no el lector disfrazado de justo.",
		revelacion: "עֲזַבְתָּנִי: me has desamparado. El clamor va a Dios, no al vacío. כארי / כארו: como león, o han horadado —la variante se sirve, no se bautiza la duda. מְלַקְּקִים: se relamen. יַדַי וְרַגְלָי: mis manos y mis pies; el cuerpo está en el metro. אֲסַפְּרָה שִׁמְךָ: anunciaré tu nombre. Las casillas de este salmo: Dios es el abandonador y el oidor; el pecado rodea como toros y perros; Cristo está donde Mateo 27 clava el clamor; el pueblo es la asamblea a la que se anunciará.",
		doctrina: "Analogía antecedente: el justo perseguido ya conocido en la historia de David. Analogía plena: los evangelios de la Pasión. No se silencia el Mesías donde el Nuevo Testamento lo nombra. No se toma cada «yo» como autobiografía del lector. Juan 19 sortea las vestiduras. Hebreos 2:12 pone al Hijo en la asamblea. El salmo no es crónica del Gólgota escrita como reportaje, sino oración que el Espíritu destinó al Gólgota. Quien se vista con este clamor para no oír al Mesías hurta el salmo.",
		argumento: "La precisión no es coincidencia. El crítico que reduce el salmo a «relectura cristiana» miente contra Mateo 27. Status quaestionis: ¿oración de David, o del Hijo? Distingo: de David, y del Hijo con autoridad canónica. Reductio: si el clamor de la cruz es cita ornamental, Mateo testifica en vano, y el 24 —no me has despreciado— queda como un consuelo privado que la Pasión no puede sostener.",
		decision: "El indicativo es «me has oído». El imperativo es proclamar, no «hoy muero a mis sentimientos de abandono» sin el verbo del texto. Lee el salmo entero, en voz alta, y di a alguien la alabanza que el abandonado promete a la asamblea. Quien se quede en el versículo 1 como amuleto de abandono aún no ha llegado al 24.",
		conclusion: "David primero; el Hijo de David con autoridad canónica. El «yo» del salmo no es el lector disfrazado. — Dr. Alejandro Sirit"
	},
	{
		slug: "marcos-7",
		kicker: "Laboratorio IV",
		ref: "Marcos 7:31–37",
		title: "Éfata",
		passage: "Y mirando al cielo, suspiró, y le dijo: Efata, esto es: Sé abierto. Al momento fueron abiertos sus oídos, y se desató la ligadura de su lengua, y hablaba bien.",
		voz: "Efata, esto es: Sé abierto.",
		ver: "El párrafo entero, no el vocablo extraído como piedra preciosa. Lo toman aparte. Dedos en los oídos. Saliva. Gemido al cielo. Un mandato. Al momento: oídos abiertos, lengua desatada, hablaba bien. El oído precede a la lengua. El versículo 36 estropea el final feliz: les mandó que no lo dijesen, y cuanto más les mandaba, tanto más lo divulgaban. Se puede recitar Isaías y desobedecer a Jesús en la misma respiración. El sordo no es el agente. El agente queda fuera de la morfología.",
		entorno: "Decápolis: oído gentil. No es viñeta de Galilea judía. Antes, la sirofenicia oye una palabra dura y cree; el sordo no puede oír ninguna. Más atrás, fariseos con labios y corazón lejos (7:1–23). Después, panes en Decápolis. El horizonte es Isaías 35:5–6. El género es narración evangélica: el sordo es un sordo, la saliva es saliva. El sentido no se obtiene evaporando el cuerpo. 8:18 preguntará: ¿teniendo oídos no oís? El milagro no es una metáfora de «abrir el corazón a tus sueños».",
		revelacion: "ἐφφαθά: hapax. Arameo אתפתח, imperativo reflexivo-pasivo: no «abre tú», sino «sé abierto». Marcos traduce de inmediato: ὅ ἐστιν Διανοίχθητι. διανοίχθητι: aoristo pasivo, apertura a través; el mismo verbo de Lucas 24:45 y Hechos 16:14. ἐστέναξεν: gimió. μογιλάλον: tartamudo, la palabra de Isaías 35 en la Septuaginta. El sordo no es el agente. Calvino oye que Marcos insertó la palabra caldea para testificar el poder divino de Cristo. Vere Deus, vere homo: toca porque es hombre y ordena porque es Dios.",
		doctrina: "Dios abre. El hombre está cerrado. Cristo toca porque es hombre y ordena porque es Dios. El pueblo trae al sordo y luego desobedece. Analogía antecedente: Marcos 4, el que tiene oídos para oír. Canon pleno: el Shemá, Isaías 6, Isaías 35, Isaías 50, Emaús, Lidia, Romanos 10:17, las siete iglesias, el Cordero que abre el libro. Este tratado se llama Éfata porque el oído y el libro coinciden. No porque el vocablo sea hermoso. El oído abierto y el libro abierto son el mismo misterio: Dios no deja cerrado lo que ha decidido abrir.",
		argumento: "Objeción primera: «Éfata es un lema de marca». Respondeo: en Marcos 7:34 es palabra de Cristo a un sordo; como título, es sierva de esa palabra, no dueña. Si la marca va primero, el sordo sigue sordo. Objeción segunda: «el milagro es metáfora de inclusión». Reductio: si se evapora el cuerpo, se evapora Isaías 35 y se queda un eslogan. Si Éfata es técnica de escucha interior, el milagro ya no es del Hijo.",
		decision: "El sordo de Marcos 7 no «murió hoy a su sordera»: fue abierto. Esa es la gramática de la gracia. Un acto: lee Marcos 7 entero, en voz alta, y nombra delante de alguien lo que aún no oyes. Mañana se vuelve. El oído no se abre una sola vez. El que convierte Éfata en marca y deja al sordo cerrado ha tomado el nombre del milagro en vano.",
		conclusion: "Jesús no le explicó al sordo el método. Le metió los dedos en los oídos, tocó la lengua, miró al cielo, suspiró y habló. El método solo enseña a no usurparle el gesto. — Dr. Alejandro Sirit"
	},
	{
		slug: "apocalipsis-5",
		kicker: "Laboratorio VI",
		ref: "Apocalipsis 5",
		title: "El Cordero y el rollo",
		passage: "Y uno de los ancianos me dijo: No llores. He aquí que el León de la tribu de Judá, la raíz de David, ha vencido para abrir el libro y desatar sus siete sellos. Y miré, y vi que en medio del trono y de los cuatro seres vivientes, y en medio de los ancianos, estaba un Cordero como inmolado, que tenía siete cuernos, y siete ojos, los cuales son los siete espíritus de Dios enviados por toda la tierra. Y vino, y tomó el libro de la mano derecha del que estaba sentado en el trono.",
		ver: "Juan llora porque nadie es digno. El anciano manda: no llores. Se anuncia un León. Se ve un Cordero. En pie, como inmolado. Toma el libro. La creación entera canta. El observador registra la paradoja y no la resuelve antes de tiempo: el que vence es el que fue degollado. El cántico nuevo declara el porqué: porque fuiste inmolado, y con tu sangre nos has redimido para Dios. Quien lea el 5 como novela de rapto ha cambiado de género.",
		entorno: "Apocalipsis, no almanaque de la última guerra. Lenguaje saturado de alusiones: Génesis 49, Éxodo, Daniel 7, el go'el de Levítico 25 y Rut. Patmos, imperio, culto al César. El género prohíbe el literalismo occidental y el sensacionalismo de novela. Las visiones son retratos doctrinales, no diagramas de tecnología bélica. Apocalipsis 4: el trono. El 5: el libro cerrado y el llanto. El 6 abre sellos. El sello de esta casa —León, Cordero y Fuego— es este capítulo, no un adorno.",
		revelacion: "ἄξιος: digno, la balanza. Nadie equilibraba el rollo. ἀρνίον ἑστηκὸς ὡς ἐσφαγμένον: un Cordero en pie, como inmolado —las marcas del degüello visibles, el perfecto de estar de pie. ἠγοράσας: compraste. Sangre. Todo linaje, lengua, pueblo y nación. οὐ κλαῖε: no llores. El primer imperativo del laboratorio es al que llora porque el libro está cerrado. Las casillas: Dios sienta en el trono y tiene el libro; el pecado dejó el cosmos sin go'el; Cristo es León y Cordero, pariente de sangre que paga; el pueblo es comprado.",
		doctrina: "Génesis 49: el cetro de Judá. El go'el: ningún ángel es pariente de Adán; el Verbo toma carne para redimir (He. 2:14–15). El Cordero recibe adoración que el ángel de Apocalipsis 19 y 22 rechaza: no es criatura. Analogía plena: el que abre el libro es el que abre al sordo. León, Cordero y Fuego no son adorno del sello, sino este capítulo. Majestad sin cruz sería condenación; cruz sin majestad, tragedia. El que abre la historia es el que fue degollado.",
		argumento: "Contra el pánico profético: el cántico nuevo declara por qué es digno —porque fue inmolado— no porque un rapto futuro lo habilite. Contra el escepticismo: la literatura de resistencia judía quería un mesías militar; este rollo subvierte esa fantasía. Status quaestionis: ¿quién abre la historia? Distingo: se anuncia un León; se ve un Cordero. Reductio: si el Cordero no es Dios, el cielo comete idolatría. Si el cetro está en el César, Juan lloró con razón.",
		decision: "El indicativo es «ha vencido» y «tomó el libro». El imperativo del anciano es el nuestro: no llores. Un acto: cesa esta semana una lectura de la historia que pone el cetro en el César, y di a alguien que el rollo está en las manos atravesadas. El llanto por el libro cerrado termina cuando se adora al que lo tomó.",
		conclusion: "El llanto de Juan ha terminado. El rollo no está cerrado: ha sido tomado por el Redentor. — Dr. Alejandro Sirit"
	},
	{
		slug: "1-corintios-12-14",
		kicker: "Dones",
		ref: "1 Corintios 12–14",
		title: "Los dones del Espíritu",
		passage: "Porque a éste es dada por el Espíritu palabra de sabiduría; a otro, palabra de ciencia según el mismo Espíritu; a otro, fe por el mismo Espíritu; y a otro, dones de sanidades por el mismo Espíritu. Pero todas estas cosas las hace uno y el mismo Espíritu, repartiendo a cada uno en particular como él quiere. Ahora bien, hay diversidad de dones, pero el Espíritu es el mismo. Porque por un solo Espíritu fuimos todos bautizados en un cuerpo.",
		ver: "Pablo no abre un catálogo de poderes para que Corinto se exhiba. Abre un cuerpo. Hay diversidad de dones, y un solo Espíritu; diversidad de ministerios, y un solo Señor; diversidad de operaciones, y un solo Dios. El que se lleva un don como trofeo aún no ha oído el 12: el mismo Espíritu reparte como él quiere. El que se lleva el amor del 13 como poema de boda aún no ha oído el 14: procurad los dones, y que todo se haga para edificación, con orden.",
		entorno: "Corinto, iglesia carismática y partida, hacia el 54–55. Habían convertido el don en rango y la lengua en espectáculo. El 11 acaba de corregir la Cena. El 12–14 es un solo argumento: el cuerpo, el camino más excelente, y el culto que edifica. El género es carta: no un manual de técnicas espirituales, ni un vetusto recelo contra todo lo que no se entiende. El pueblo a quien se escribe ya tiene dones. Le falta el amor que no se envanece, y el orden que no apaga.",
		revelacion: "χαρίσματα: dones de gracia, no trofeos. ἓν πνεῦμα: un solo Espíritu. τὸ σῶμα: el cuerpo; el miembro no dice al otro «no te necesito». ἡ ἀγάπη: el camino más excelente no anula el don; impide que el don se vuelva cimbalo. οἰκοδομή: edificación. εὐσχημόνως καὶ κατὰ τάξιν: decentemente y con orden. El que extrae 13:4–7 y deja 14:40 ha fabricado un amor sin asamblea, o una asamblea sin amor.",
		doctrina: "El Espíritu reparte. El Hijo es el Señor de los ministerios. El Padre opera. El pueblo es un cuerpo, no un escenario. Los dones no miden santidad: miden servicio. El amor permanece cuando las lenguas cesen. Analogía plena: Hechos 2 no es un clima; Romanos 12 pide el cuerpo; Efesios 4 da apóstoles, profetas, evangelistas, pastores y maestros para la edificación. El que apaga el Espíritu para no desordenarse, y el que desordena para no apagar, han leído a medias.",
		argumento: "Status quaestionis: ¿son los dones un trofeo, o un servicio al cuerpo? Distingo: hay manifestación, y hay edificación; la primera sin la segunda es cimbalo. Reductio: si el don se exhibe y el hermano no se edifica, 14:26 ha fallado, y el Espíritu habría repartido para el yo. Si el 13 se cita para no desear dones, Pablo ha escrito en vano el 14.",
		decision: "Esta semana, nombra un don —el tuyo o el que envidias— y ponlo al servicio de un hermano concreto, no de un escenario. Un acto. El que busca lengua para ser visto, o silencio para no servir, todavía no ha oído a Corinto.",
		conclusion: "Un solo Espíritu, un solo cuerpo, y un amor que no deja que el don se vuelva cimbalo. — Dr. Alejandro Sirit"
	},
	{
		slug: "galatas-5",
		kicker: "Fruto",
		ref: "Gálatas 5:22–23",
		title: "El fruto del Espíritu",
		passage: "Mas el fruto del Espíritu es amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza; contra tales cosas no hay ley. Pero los que son de Cristo han crucificado la carne con sus pasiones y deseos. Si vivimos por el Espíritu, andemos también por el Espíritu.",
		ver: "Pablo no ofrece un cartel de virtudes para que el yo se mida y se apruebe. Ofrece un fruto. Singular. Nueve nombres, un solo árbol. El que se lleva «amor, gozo, paz» como lema de clima interior aún no ha visto el 16: andad en el Espíritu, y no satisfagáis los deseos de la carne. El que se lleva la lista y deja la crucifixión del 24 ha fabricado un carácter sin cruz.",
		entorno: "Gálatas, carta de urgencia, hacia el 48–55. Hay quienes quieren que los gentiles se circunciden para completar a Cristo. El 5:1 abre: estad, pues, firmes en la libertad. El 13 impide que esa libertad se vuelva ocasión para la carne. El 19–21 nombra las obras —plural— de la carne. El 22 nombra el fruto. El género es carta polémica: no un taller de hábitos, ni un contrapunto estoico. El pueblo a quien se escribe estaba a punto de cambiar de evangelio para parecer más serio.",
		revelacion: "καρπὸς τοῦ πνεύματος: fruto del Espíritu, no frutos que el hombre cultiva como huerto propio. ἀγάπη, χαρά, εἰρήνη, μακροθυμία, χρηστότης, ἀγαθωσύνη, πίστις, πραΰτης, ἐγκράτεια. Contra tales cosas no hay ley: la ley no se opone a lo que el Espíritu produce. οἱ δὲ τοῦ Χριστοῦ: los que son de Cristo han crucificado la carne. El verbo es perfecto. El andad del 25 es presente. El fruto no se decreta. Se da donde se anda.",
		doctrina: "El Espíritu produce lo que la ley pedía y la carne no podía. Cristo libertó; la libertad no es licencia. El pueblo no improvisa el carácter: lo recibe y lo anda. Juan 15 está debajo: el pámpano no da fruto separado de la vid. El que predica las nueve palabras como técnica de mejora ha vuelto a la carne con vocabulario santo. El que predica la libertad para no crucificar nada ha vuelto a la carne con vocabulario de gracia.",
		argumento: "Status quaestionis: ¿lista de hábitos, o fruto de un Señor? Distingo: hay ejercicio, y hay producción; el primero no fabrica al segundo. Reductio: si el fruto se administra sin la crucifixión del 24, Gálatas 3 ha sido en vano, y el Espíritu sería un entrenador, no el que da vida.",
		decision: "Elige un nombre del fruto que el texto ha desnudado —uno, no nueve— y nombra delante de un testigo dónde la carne lo estaba sustituyendo. Anda. El que elige los nueve no ha elegido ninguno. El que no lo dice lo ha dejado en el cartel.",
		conclusion: "Un fruto, no un cartel. El Espíritu produce; la carne no fabrica. — Dr. Alejandro Sirit"
	},
	{
		slug: "2-corintios-12",
		kicker: "Gracia",
		ref: "2 Corintios 12:1–10",
		title: "Bástate mi gracia",
		passage: "Y para que la grandeza de las revelaciones no me exaltase desmedidamente, me fue dado un aguijón en mi carne, un mensajero de Satanás que me abofetee, para que no me enaltezca; respecto a lo cual tres veces he rogado al Señor, que lo quite de mí. Y me ha dicho: Bástate mi gracia; porque mi poder se perfecciona en la debilidad. Por tanto, de buena gana me gloriaré más bien en mis debilidades, para que more en mí el poder de Cristo.",
		voz: "Bástate mi gracia; porque mi poder se perfecciona en la debilidad.",
		ver: "Pablo no exhibe un viaje al tercer cielo para que Corinto aplaudiera. Exhibe un aguijón que no se quita. Tres veces rogó. La respuesta no es la extracción, sino la palabra. Bástate mi gracia. El que se lleva el 9 como consuelo genérico aún no ha visto el 7: para que no me enaltezca. El que se lleva el aguijón como romance de sufrimiento aún no ha oído el poder que se perfecciona donde ya no se puede.",
		entorno: "Segunda a Corinto, hacia el 55–56. Hay superapóstoles que miden el ministerio por éxtasis y por apariencia. El 11–12 es una «locura» forzada: Pablo se gloria en lo que ellos despreciarían. El género es carta: apología que se vuelve teología de la flaqueza, no un manual de aguijones. El pueblo a quien se escribe quería un siervo impresionante. Recibe a un hombre abofeteado, y a un Señor que no quita el mensajero.",
		revelacion: "σκόλοψ τῇ σαρκί: aguijón en la carne. ἄγγελος σατανᾶ: mensajero de Satanás que abofetee. ἀρκεῖ σοι ἡ χάρις μου: bástate mi gracia. ἡ γὰρ δύναμις ἐν ἀσθενείᾳ τελεῖται: el poder se perfecciona en la debilidad. ἥδιστα οὖν μᾶλλον καυχήσομαι: de buena gana me gloriaré. El verbo de la respuesta es presente: me ha dicho, y la palabra permanece. El aguijón también.",
		doctrina: "La gracia no es un adorno del fuerte. Es el poder del que ya no puede. Cristo more en la flaqueza; no la evapora para que el ministerio luzca. El pueblo no despide al que tiene aguijón: oye en él al Señor. Este tomo, en la colección, se llama *Bástate*, y se lee en el tercer puesto: no es un satélite. Isaías 53 carga la rebelión; 2 Corintios 12 sostiene al cuerpo que todavía gime. El que predica una gracia que siempre quita el aguijón ha cambiado de Señor.",
		argumento: "Status quaestionis: ¿es el aguijón un fracaso de fe, o el lugar donde el poder se perfecciona? Distingo: hay sanidad, y hay palabra que no quita; la primera no anula a la segunda. Reductio: si el 9 se cita para extraer todo aguijón, Pablo habría desobedecido al rogar solo tres veces, y el poder de Cristo no moraría en la debilidad.",
		decision: "Nombra el aguijón que has tratado como prueba de que Dios no basta. Esta semana, deja de rogar solo para que se quite, y oye la palabra que permanece: bástate mi gracia. Dilo a alguien. El que convierte el 9 en un lema y niega la flaqueza aún no ha sido respondido: ha sido entretenido.",
		conclusion: "El aguijón permanece; el Señor también. La gracia basta donde el yo ya no puede. — Dr. Alejandro Sirit"
	},
	{
		slug: "viajes-de-pablo",
		kicker: "Misión",
		ref: "Hechos 13–14",
		title: "Los viajes de Pablo",
		passage: "Enviados ciertamente por el Espíritu Santo, descendieron a Seleucia, y de allí navegaron a Chipre. Y cuando llegaron a Salamina, anunciaban la palabra de Dios en las sinagogas de los judíos. Confirmando los ánimos de los discípulos, exhortándoles a que permaneciesen en la fe, y diciéndoles: Es necesario que a través de muchas tribulaciones entremos en el reino de Dios.",
		ver: "Lucas no escribe un itinerario de turismo apostólico. Escribe un envío. El Espíritu Santo habla en Antioquía; apartan a Bernabé y a Saulo; les imponen las manos; bajan a Seleucia. El que se lleva «viajes de Pablo» como mapa de éxito aún no ha oído 14:22: es necesario que a través de muchas tribulaciones entremos en el reino de Dios. El que se lleva Chipre y deja Listra ha fabricado una misión sin piedras.",
		entorno: "Hechos, historia teológica para Teófilo. El 13–14 es el primer viaje: Chipre, Pisidia, Licaonia. Hay sinagoga, hay mago, hay celos, hay lapidación, hay presbíteros. El género prohíbe el manual de crecimiento y el almanaque de anécdotas. El pueblo a quien se escribe necesita saber que el evangelio llegó a las naciones con hechos, no con rumores, y que el envío no evapora la tribulación.",
		revelacion: "ἀφορίσατε: apartadme a Bernabé y a Saulo. ἐκπεμφθέντες ὑπὸ τοῦ ἁγίου πνεύματος: enviados por el Espíritu Santo. διὰ πολλῶν θλίψεων: a través de muchas tribulaciones. χειροτονήσαντες: designaron ancianos. El viaje no es una marca personal. Es el Espíritu que aparta, la Palabra que se anuncia, la iglesia que se confirma, y el reino que se entra con θλῖψις. El que extrae el mapa y deja el 14:22 ha recortado el oficio.",
		doctrina: "El Espíritu envía. El Hijo es el contenido del anuncio —el que no vio corrupción, el que justifica—. El pueblo se confirma en la fe y recibe ancianos. La analogía plena oye Mateo 28 y Romanos 15: no hay misión que no pase por la Palabra, ni Palabra que prometa un camino sin tribulación. El que predica viajes como técnica de expansión ha cambiado de libro: ha leído un informe, no a Lucas.",
		argumento: "Status quaestionis: ¿itinerario de éxito, o envío con tribulación? Distingo: hay fruto, y hay piedras; el primero no anula a las segundas. Reductio: si el viaje se cita para prometernos un siglo sin θλῖψις, 14:22 ha mentido, y el reino se habría vuelto un destino turístico.",
		decision: "Esta semana, nombra un envío concreto —una Palabra que debías anunciar, un hermano que debías confirmar— y no lo midas por la facilidad. El que espera un mapa sin Listra todavía no ha sido apartado: ha sido entretenido.",
		conclusion: "El Espíritu aparta. La Palabra se anuncia. El reino se entra con muchas tribulaciones. — Dr. Alejandro Sirit"
	},
	{
		slug: "1-corintios-1-2",
		kicker: "Retórica",
		ref: "1 Corintios 1–2",
		title: "La retórica de Pablo",
		passage: "Pues no me envió Cristo a bautizar, sino a predicar el evangelio; no con sabiduría de palabras, para que no se haga vana la cruz de Cristo. Porque la palabra de la cruz es locura a los que se pierden; pero a los que se salvan, esto es, a nosotros, es poder de Dios. Y ni mi palabra ni mi predicación fue con palabras persuasivas de humana sabiduría, sino con demostración del Espíritu y de poder.",
		ver: "Pablo no desprecia las palabras. Desprecia la sabiduría de palabras que deja vana la cruz. Corinto se partía por nombres —Pablo, Apolos, Cefas, Cristo— y medía el púlpito por el brillo. El que se lleva «no con sabiduría» como disculpa de la ignorancia aún no ha oído el 2:6: hablamos sabiduría entre los que han alcanzado madurez. El que se lleva la retórica como adorno aún no ha oído el 1:17: para que no se haga vana la cruz.",
		entorno: "Primera a Corinto, hacia el 54–55. Ciudad de oradores, de patronazgo y de status. El 1:10–4:21 es un solo movimiento contra las bandas. El género es carta: no un tratado de elocuencia, ni un elogio de la tosquedad. El pueblo a quien se escribe quería un predicador que luciera en el ágora. Recibe a un apóstol que se plantó con temor y temblor, y a un Cristo crucificado que el siglo llama locura.",
		revelacion: "σοφία λόγου: sabiduría de palabras. κενωθῇ ὁ σταυρός: que no se vacíe la cruz. μωρία: locura, a los que se pierden. δύναμις θεοῦ: poder de Dios, a los que se salvan. ἀπόδειξις πνεύματος καὶ δυνάμεως: demostración del Espíritu y de poder. οὐκ ἐν πειθοῖς σοφίας λόγοις: no con palabras persuasivas de sabiduría. El léxico no prohíbe la claridad. Prohíbe el aparato que rivaliza con el madero.",
		doctrina: "Cristo no envió a bautizar facciones, sino a predicar. El Padre eligió lo necio del mundo. El Espíritu revela lo que el hombre natural no recibe. El pueblo no se gloria en el predicador: el que se gloria, gloríese en el Señor. Jeremías 9:24 está debajo. El que predica la cruz con el tono del ágora ha cambiado de poder. El que predica la tosquedad como virtud ha cambiado de oficio: Pablo no se niega a hablar; se niega a vaciar.",
		argumento: "Status quaestionis: ¿es la predicación un arte que convence, o un anuncio que el Espíritu demuestra? Distingo: hay palabras, y hay sabiduría de palabras; las primeras sirven, la segunda vacía. Reductio: si el 2:4 se cita para no estudiar, 2:6 ha sobrado. Si el 1:17 se cita para lucir, la cruz ya se vació.",
		decision: "Esta semana, nombra una frase tuya —en el púlpito, en la mesa, en la red— que estaba luciendo más que el madero. Quítala. El que se reforma el estilo y no se arrodilla ante la locura de la cruz todavía está en el ágora.",
		conclusion: "La cruz no se adorna para convencer. Se anuncia, y el Espíritu demuestra. — Dr. Alejandro Sirit"
	},
	{
		slug: "teologia-de-la-cruz",
		kicker: "Cruz",
		ref: "1 Corintios 1:18–31",
		title: "Teología de la cruz",
		passage: "Porque la palabra de la cruz es locura a los que se pierden; pero a los que se salvan, esto es, a nosotros, es poder de Dios. Pues ya que en la sabiduría de Dios, el mundo no conoció a Dios mediante la sabiduría, agradó a Dios salvar a los creyentes por la locura de la predicación. Mas Dios eligió lo necio del mundo, para avergonzar a los sabios.",
		ver: "Pablo no ofrece una «teología de la cruz» como lema de escuela. Ofrece un tajo. La palabra de la cruz parte a la humanidad: locura para los que se pierden, poder para los que se salvan. El que se lleva el 18 como consigna contra los intelectuales aún no ha visto el 21: el mundo no conoció a Dios mediante la sabiduría. El que se lleva lo necio como orgullo de ignorancia aún no ha visto el 30: Cristo nos ha sido hecho sabiduría, justificación, santificación y redención.",
		entorno: "El mismo Corinto del 1–2. Judíos piden señales. Griegos buscan sabiduría. Nosotros predicamos a Cristo crucificado: tropezadero y locura. El género es carta, no un tratado luterano suelto —aunque Lutero oirá esto con razón—. El pueblo a quien se escribe quería un Cristo que luciera. Recibe al que Dios eligió: lo vil, lo menospreciado, lo que no es, para deshacer lo que es.",
		revelacion: "ὁ λόγος ὁ τοῦ σταυροῦ: la palabra de la cruz, no un adorno. σκάνδαλον: tropiezo para judíos. μωρίαν: locura para gentiles. ἐξελέξατο ὁ θεός: Dios eligió. τὰ μὴ ὄντα: lo que no es. ἵνα μὴ καυχήσηται: para que nadie se jacte. ἐξ αὐτοῦ: de él sois en Cristo Jesús. El que extrae «locura» y deja «de él sois» ha fabricado un desprecio, no una teología.",
		doctrina: "Dios salva por lo que el siglo desprecia. El Hijo crucificado es el poder y la sabiduría de Dios. El pueblo no se jacta: el que se gloria, gloríese en el Señor. La analogía plena oye Isaías 29:14 y Jeremías 9:24. *El Siervo, no tú* lee el mismo tajo desde Isaías 53: el justo muere por los injustos, y el lector no se sube al madero como si fuera el Siervo. El que predica una cruz que no avergüenza al sabio ha cambiado de cruz.",
		argumento: "Status quaestionis: ¿es la cruz un tropiezo que Dios eligió, o un emblema que el siglo puede aplaudir? Distingo: hay sabiduría de Dios, y hay sabiduría del mundo; la primera se revela en lo necio. Reductio: si la cruz se adorna hasta que deje de ser locura, 1:21 ha fallado, y nadie se habría salvado por la predicación.",
		decision: "Esta semana, nombra una jactancia —oficio, púlpito, herida bien contada— que estabas usando para no quedar en «lo que no es». Déjala. Gloríate en el Señor. El que se queda en el desprecio de los sabios y no se queda en Cristo aún no ha oído el 30.",
		conclusion: "La cruz parte. Locura o poder. Nadie se jacta, sino en el Señor. — Dr. Alejandro Sirit"
	},
	{
		slug: "teologia-de-la-gloria",
		kicker: "Gloria",
		ref: "1 Corintios 4:8–13",
		title: "Teología de la gloria",
		passage: "Ya estáis saciados, ya estáis ricos, sin nosotros reináis. ¡Y ojalá reinaseis, para que nosotros reinásemos también juntamente con vosotros! Porque según pienso, Dios nos ha exhibido a nosotros los apóstoles como últimos, como a sentenciados a muerte; pues hemos llegado a ser espectáculo al mundo, a los ángeles y a los hombres.",
		ver: "Pablo no escribe un tratado contra el espectáculo: lo desnuda. Corinto ya se saciaba, ya era rica, ya reinaba —sin los apóstoles—. El que se lleva «teología de la gloria» como lema de combate aún no ha visto el 9: Dios exhibió a los apóstoles como últimos, como a sentenciados a muerte. El que se lleva el espectáculo como pecadillo de escenario aún no ha oído que el reinado adelantado es otra cruz: una cruz que no padece.",
		entorno: "Sigue 1 Corintios. El 4 cierra el argumento de las bandas: no juzguéis antes de tiempo; no os ensoberbezcáis. El género es ironía pastoral, no un slogan luterano suelto —aunque la casa oye aquí la misma advertencia: la gloria sin cruz es teatro—. El pueblo a quien se escribe quería un cristianismo que ya hubiera llegado. Recibe a apóstoles hambrientos, desnudos, abofeteados, y a un Señor que aún no ha entregado el reino visible.",
		revelacion: "ἤδη κεκορεσμένοι: ya estáis saciados. ἐβασιλεύσατε χωρὶς ἡμῶν: reinasteis sin nosotros. ἐσχάτους: últimos. ἐπιθανατίους: sentenciados a muerte. θέατρον: espectáculo. ἡμεῖς μωροὶ διὰ Χριστόν, ὑμεῖς δὲ φρόνιμοι: nosotros necios por Cristo, vosotros prudentes. El contraste no es un chiste. Es el juicio del apóstol contra una iglesia que adelantó la gloria y dejó la cruz.",
		doctrina: "La gloria es real, y es futura. El Hijo reinará; aún no se ve que todas las cosas le sean sujetas. El pueblo padece, espera y no se corona a sí mismo. Romanos 8:17 está debajo: herederos, si es que padecemos con él. *El Siervo, no tú* quita la autoexpiación; este estudio quita la autocoronación. El que predica un reino ya cobrado, sin padecimiento y sin apóstoles últimos, ha cambiado de tiempo: ha leído Apocalipsis 21 en 1 Corintios 4.",
		argumento: "Status quaestionis: ¿ya reinamos, o somos espectáculo? Distingo: hay primicias, y hay adelanto soberbio; las primeras gimen, el segundo se sacia. Reductio: si Corinto ya reina, los apóstoles son un anacronismo, y 4:8 es elogio, no ironía.",
		decision: "Nombra un «ya» que te estabas coronando —un ministerio que ya llegó, una herida que ya te hace rey, un escenario que ya te aplaude—. Esta semana, bájalo. El que se niega a ser último todavía está saciado. El texto pide espectáculo al mundo, no trono.",
		conclusion: "La gloria que se adelanta es teatro. Los apóstoles fueron exhibidos como últimos. — Dr. Alejandro Sirit"
	},
	{
		slug: "romanos-8-17",
		kicker: "Herencia",
		ref: "Romanos 8:17",
		title: "Herederos y padecimiento",
		passage: "Y si hijos, también herederos; herederos de Dios y coherederos con Cristo, si es que padecemos juntamente con él, para que juntamente con él seamos glorificados. Pues tengo por cierto que las aflicciones del tiempo presente no son comparables con la gloria venidera que en nosotros ha de manifestarse.",
		ver: "Pablo no ofrece una herencia sin cruz. Si hijos, también herederos; coherederos con Cristo, si es que padecemos juntamente con él. El que se lleva «hijos» como lema de identidad aún no ha oído el εἴπερ: si es que. El que se lleva el padecimiento como romanticismo aún no ha oído el 18: las aflicciones no se comparan con la gloria que ha de manifestarse. El capítulo gime. El heredero también.",
		entorno: "Romanos 8, después de «ninguna condenación» y del Espíritu de adopción que clama Abba. El 18–27 pone a la creación, a los que tienen las primicias y al Espíritu mismo a gemir. El género es carta: no un folleto de identidad, ni un manual de aguante. El pueblo a quien se escribe es justificado, y todavía no glorificado. El 8:28–39 espera; no se adelanta.",
		revelacion: "τέκνα: hijos. κληρονόμοι: herederos. συγκληρονόμοι Χριστοῦ: coherederos con Cristo. εἴπερ συμπάσχομεν: si es que padecemos con él. ἵνα καὶ συνδοξασθῶμεν: para que seamos glorificados con él. οὐκ ἄξια: no son comparables. El «si es que» no pone en duda la filiación para el que tiene el Espíritu. Ata la herencia a la forma del Hijo: padecer con él, no coronarse sin él.",
		doctrina: "El Padre adopta. El Hijo comparte herencia y padecimiento. El Espíritu es primicias, no consumación. El pueblo gime y espera. La analogía plena oye 2 Timoteo 2:12 y 1 Pedro 4:13. *Cuando el cielo se cae* enseña a llorar sin apostatar; este estudio enseña a heredar sin adelantar la gloria. El que predica filiación para no padecer ha recortado el εἴπερ. El que predica padecimiento para merecer la herencia ha recortado la adopción.",
		argumento: "Status quaestionis: ¿es la herencia un derecho sin cruz, o una co-herencia que padece? Distingo: hay filiación segura, y hay camino de Hijo; la primera no evapora al segundo. Reductio: si el 17 se cita sin συμπάσχομεν, el 18 sobra, y la creación gime en vano.",
		decision: "Esta semana, nombra un padecimiento que habías tratado como prueba de que no eres hijo. Somételo al εἴπερ: padece con él, no contra la adopción. Dilo a alguien que gima contigo. El que se corona sin gemir todavía no es coheredero, sino un espectador del 17.",
		conclusion: "Hijos, herederos, coherederos: si es que padecemos con él. La gloria espera. — Dr. Alejandro Sirit"
	}
];
export function studyBySlug(slug: string) {
  return studies.find((s) => s.slug === slug);
}

export function etiquetaEstudio(slug: string) {
  if (slug === "viajes-de-pablo") return "Estudio · pack · Hechos 13–14";
  if (slug === estudioSemanaSlug()) return "Estudio · esta semana";
  if (estudioTienePack(slug) && (LAB_SLUGS as readonly string[]).includes(slug)) {
    return "Estudio · pack · yunque";
  }
  if (estudioTienePack(slug)) return "Estudio · pack";
  if ((LAB_SLUGS as readonly string[]).includes(slug)) return "Laboratorio · próximamente";
  return "Próximamente";
}

export function estudiosPublicados() {
  return ESTUDIOS_DRIVE.map((slug) => studyBySlug(slug)).filter(
    (s): s is NonNullable<typeof s> => Boolean(s),
  );
}

export function estudiosProximos() {
  return studies.filter((s) => !estudioTienePack(s.slug));
}

export function siguienteEstudio(slug: string) {
  const i = ESTUDIOS_DRIVE.indexOf(slug as (typeof ESTUDIOS_DRIVE)[number]);
  if (i < 0 || i >= ESTUDIOS_DRIVE.length - 1) return undefined;
  return studyBySlug(ESTUDIOS_DRIVE[i + 1]);
}
