export const parrafos: readonly string[] = [
  "Convención tipográfica. Las palabras de la Escritura se citan según la Reina-Valera 1909, de dominio público. Los vocablos hebreos y griegos aparecen en su forma original, seguidos de su sentido en castellano la primera vez. Los títulos de cada sección han sido tomados del propio texto sagrado. Los intérpretes comparecen como siervos: ninguno sustituye a Mateo.",
  "© 2026 Alejandro Sirit. Todos los derechos reservados.",
  "«Buscad primeramente»",
  "«Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.»",
  "Mateo 6:33 · Reina-Valera 1909",
  "El presente tratado examina Mateo 6:33 con el rigor que el texto exige y con la claridad que el pueblo de Dios merece. No se pretende extraer del pasaje una técnica de prosperidad, ni convertirlo en instrumento de negociación con el Padre. Se pretende oírlo donde el Señor lo pronunció: en el Sermón del Monte, después de la prohibición de servir a dos señores, delante de discípulos que conocían la incertidumbre del pan cotidiano.",
  "El protocolo de lectura es el de Cielo Efata, V.E.R.D.A.D. —Ver, Entorno, Revelación, Doctrina, Argumento, Decisión—: ver el pasaje entero; situarlo; atender al original; extraer la doctrina; discernir el argumento; concluir en una decisión comprobable. Los intérpretes —Calvino, Henry, Crisóstomo, Spurgeon, MacArthur— comparecen como siervos. Ninguno sustituye a Mateo.",
  "Este tratado se ata al ciclo de la casa —Éfata, Cuando el cielo se cae, La fe no basta, El altar del espejo, Bástate mi gracia— y no lo sustituye. Quien lo tome por el libro entero ha vuelto a recortar.",
  "«El reino de los cielos se ha acercado»",
  "Contexto histórico y literario del Evangelio según Mateo",
  "Mateo no redacta una biografía al modo moderno. Redacta un evangelio: el anuncio de que el reinado de Dios se ha hecho próximo en Jesús de Nazaret, hijo de David, hijo de Abraham.",
  "«Libro de la generación de Jesucristo, hijo de David, hijo de Abraham.»",
  "Mateo 1:1",
  "El relato, compuesto en griego y saturado de la Escritura de Israel, está ordenado para que un lector formado en la Ley perciba que la Torá no queda abolida, sino cumplida. Por consiguiente, el sermón nace de un Mesías que afirma:",
  "«No penséis que he venido para abrogar la ley ó los profetas: no he venido para abrogar, sino á cumplir.»",
  "Mateo 5:17",
  "El autor no se nombra en el texto. La tradición de la Iglesia antigua atribuyó la obra al publicano llamado Leví, uno de los Doce. Ahora bien, lo que el documento mismo exige no es la firma, sino la autoridad de la voz que habla: el Maestro no enseña como los escribas.",
  "«Porque les enseñaba como quien tiene autoridad, y no como los escribas.»",
  "Mateo 7:29",
  "La datación más sobria sitúa la composición después de la destrucción de Jerusalén (70 d.C.) y antes de que Ignacio de Antioquía cite materiales mateanos (hacia 110). La comunidad destinataria parece judía y creyente en Jesús, probablemente en Siria o Galilea, en tensión con la sinagoga farisea tras la pérdida del Templo. El capítulo 23 no es, por tanto, un adorno polémico: es el acta de una ruptura entre hermanos de Escritura. El evangelio no concluye en Jerusalén, sino en Galilea, con el envío a todas las naciones.",
  "«Por tanto, id, y doctrinad á todos los Gentiles.»",
  "Mateo 28:19",
  "El Sermón del Monte (Mateo 5–7) es el primero de cinco bloques de enseñanza que articulan el libro. Jesús sube al monte; Moisés subió al Sinaí. La diferencia no es ornamental: en el Sinaí la voz procede de la nube; aquí la voz está sentada entre los discípulos. Las bienaventuranzas no premian a quienes ya poseían pan. Declaran dichosos a los pobres en espíritu, a los que tienen hambre y sed de justicia, a los perseguidos por causa de la justicia.",
  "«Bienaventurados los que tienen hambre y sed de justicia: porque ellos serán hartos.»",
  "Mateo 5:6",
  "La palabra griega δικαιοσύνη (dikaiosýnē, justicia, rectitud) recorre el sermón como un hilo conductor. Mateo 6:33 no nace de un vacío. Nace de esa hambre. El sermón se dirige primero a los discípulos y alcanza, al final, a las multitudes que se asombran. No es un código civil para el Imperio. Es la constitución del pueblo del Rey. Quien lo lea como manual de éxito ha cambiado de género literario.",
  "Galilea del primer siglo no era un retiro contemplativo: era campo, pesca, tributo y la sombra de Roma. Cuando el Señor dice «no os congojéis por vuestra vida, qué habéis de comer», se dirige a quienes conocen la tinaja vacía. Por ello el versículo 33 no es crueldad piadosa: es reordenación. El afán pagano coloca el pan en el trono; el discípulo coloca el Reino y deja el pan en las manos del Padre.",
  "Tampoco es un decreto según el cual al justo nunca le falte la cena. Job bendijo el Nombre con las manos vacías. El Hijo, en Getsemaní, pidió que pasara la copa y bebió. Mateo 6:33 no anula Mateo 10:28–31 ni Mateo 27. La providencia no es un contrato de suministros. Es la soberanía de un Padre que conoce la necesidad antes de que se la formulen.",
  "«Porque vuestro Padre sabe de qué cosas tenéis necesidad, antes que vosotros le pidáis.»",
  "Mateo 6:8",
  "«No os congojéis por vuestra vida»",
  "Entorno inmediato: Mateo 6:19–34",
  "El versículo 33 no se sostiene aislado. Procede de tres prohibiciones y de una alternativa, y el entorno inmediato es el dueño del verso.",
  "Primero: no atesorar en la tierra, donde polilla y herrumbre corrompen. El corazón sigue al tesoro, no a la inversa.",
  "«Porque donde estuviere vuestro tesoro, allí estará vuestro corazón.»",
  "Mateo 6:21",
  "Segundo: el ojo sencillo o el ojo maligno. La visión doble oscurece el cuerpo entero. Tercero: nadie puede servir a dos señores —Dios y Mamón (el dinero convertido en amo; no el dinero en cuanto tal)—. Donde las riquezas dominan el corazón, Dios ha perdido su autoridad, como oía Calvino en la armonía de los Evangelios.",
  "Sobre ese suelo se alza 6:25–34. La partícula διὰ τοῦτο (dià toûto, por tanto) introduce la consecuencia: puesto que no es posible servir a dos, no os afanéis. El verbo es μεριμνάω (merimnáō, dividir la mente, angustiarse); tres veces el Señor lo interrumpe (vv. 25, 31 y 34). El argumento no es estoico: es teológico. Vuestro Padre celestial las sabe; las aves son alimentadas; los lirios son vestidos; vosotros valéis más. El gentil persigue esas cosas como si Dios no existiera; vosotros tenéis Padre.",
  "«Porque los Gentiles buscan todas estas cosas: que vuestro Padre celestial sabe que de todas estas cosas habéis menester.»",
  "Mateo 6:32",
  "Entonces el δέ (dé, pero, antes bien) del versículo 33. No es un apéndice devocional. Es el reverso positivo de la prohibición. Dejad de afanaros por el pan; buscad primeramente otra realidad; y ταῦτα πάντα (taûta pánta, estas cosas todas) —las del contexto: alimento, bebida, vestido— serán añadidas. No «cuanto el corazón codicie». Estas.",
  "«La justicia suya»",
  "El texto griego que obliga",
  "Lectura de trabajo (Nestle-Aland 28 / SBL, con la variante entre corchetes):",
  "ζητεῖτε δὲ πρῶτον τὴν βασιλείαν [τοῦ θεοῦ] καὶ τὴν δικαιοσύνην αὐτοῦ, καὶ ταῦτα πάντα προστεθήσεται ὑμῖν.",
  "Traducción literal aproximada: «Buscad, pues, primeramente el reino y la justicia de él, y estas cosas todas serán añadidas a vosotros.»",
  "Los manuscritos no coinciden en la presencia de τοῦ θεοῦ (toû theoû, de Dios). El texto bizantino y el Textus Receptus leen «el reino de Dios y su justicia»; testigos alejandrinos tempranos, y con ellos las ediciones críticas, prefieren «el reino y la justicia de él», sin el genitivo explícito. La diferencia no altera el dueño. El posesivo αὐτοῦ (autou, de él) permanece anclado en el Padre del versículo 32. Quien emplee la variante para fabricar un reino impersonal ha leído mal ambas formas; quien la emplee para acusar de herejía a la otra familia ha convertido la crítica textual en contienda de partidos. El reino es de Dios. La justicia es suya.",
  "La morfología que obliga no predica en lugar del párrafo; sostiene lo que el párrafo ya dice.",
  "ζητεῖτε (zēteîte, buscad): presente de imperativo, segunda persona del plural, voz activa, de ζητέω (zētéō, G2212, buscar, procurar). No describe un instante. Describe una búsqueda que no se extingue. El plural importa: el Señor no diseña una piedad solitaria; habla a una comunidad de discípulos.",
  "πρῶτον (prôton, G4412, primeramente): adverbio de rango, no apenas de horario. No significa «buscad el reino a primera hora y el mercado a la siguiente». Significa que el reino ocupa el primer puesto; lo demás se ordena debajo o se desploma.",
  "βασιλείαν (basileían, G932, reino, soberanía, reinado). En Mateo no es solo un territorio futuro. Es el señorío que ya irrumpe en Jesús y que aún espera su consumación. Buscar el reino es buscar que Dios reine: en el oído, en la casa, en la asamblea, y anhelar que el Rey vuelva.",
  "δικαιοσύνην αὐτοῦ (dikaiosýnēn autoû, G1343, la justicia / rectitud de él). En el sermón, dikaiosýnē no es un certificado forense aislado ni una ética burguesa. Es la rectitud que Dios exige y que Dios concede: la que supera a la de escribas y fariseos, la que se practica en secreto delante del Padre, aquella de la cual se tiene hambre.",
  "«Que el reino de Dios no es comida ni bebida, sino justicia y paz y gozo por el Espíritu Santo.»",
  "Romanos 14:17",
  "προστεθήσεται (prostethḗsetai, G4369, será añadido): futuro pasivo de προστίθημι (prostíthēmi, poner encima, adjuntar). La voz pasiva es teológica: el sujeto que añade no es el discípulo. Es el Padre. El pan no es el bien mayor. Es el adjunto. Como oía Calvino: las cosas de la vida presente son apéndices favorables, y deben reputarse muy inferiores al reino de Dios.",
  "El testimonio de las versiones",
  "Se citan para oír, no para votar. Ninguna traducción es el original. Varias juntas impiden que una sola se dueña del oído.",
  "Reina-Valera 1909",
  "«Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.»",
  "Biblia de Jerusalén",
  "«Buscad primero el Reino de Dios y su justicia, y todas esas cosas se os darán por añadidura.»",
  "PDT",
  "«Lo más importante para ustedes debe ser el reino de Dios y hacer lo que él pide. Entonces él les dará todo lo que necesiten.»",
  "KJV",
  "«But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.»",
  "La Reina-Valera y la KJV explicitan «de Dios», siguiendo la línea bizantina. PDT parafrasea «hacer lo que él pide» y «todo lo que necesiten»: gana claridad pastoral y pierde el filo de dikaiosýnē y de taûta. «Todo lo que necesiten» ya no son necesariamente «estas cosas» del contexto. Cuando la paráfrasis se vuelve texto de cabecera, se fabrica un versículo que Mateo no escribió. La «añadidura» de la Biblia de Jerusalén acierta el sentido de prostethḗsetai: no es el plato principal.",
  "Regla de este tratado: se predica el griego; se cita la Reina-Valera 1909 por oído de la iglesia de habla hispana; se corrige la versión cuando el original lo exige. En este pasaje la Reina-Valera no traiciona el filo.",
  "Cinco lecturas del mismo mandato",
  "Lente léxica.",
  "ζητέω en Mateo cubre un espectro que el castellano «buscar» aplana. Se busca al niño (2:13), se busca señal (12:39; 16:4), se busca cómo prender a Jesús (21:46), se busca el reino (6:33; 13:45). El mismo verbo sirve al mago, al verdugo y al discípulo. Lo que distingue no es la intensidad del deseo: es el objeto. El pagano ἐπιζητεῖ (epizēteî, persigue) comida; el discípulo ζητεῖ (zēteî, busca) reino y justicia. Cambiar el objeto sin cambiar el verbo es idolatría con vocabulario piadoso.",
  "Lente literaria.",
  "El versículo 33 recoge dos notas del sermón: el Reino y la Justicia. No es un dicho huérfano; es clave de bóveda de 6:19–34 y, por extensión, de los capítulos 5 a 7. Quien extraiga 6:33 para un lema y deje atrás 5:20 y 6:1 ha cortado el hilo. La justicia que se busca en 6:33 no puede ser la que se pregona en la esquina.",
  "«Porque os digo, que si vuestra justicia no fuere mayor que la de los escribas y de los Fariseos, no entraréis en el reino de los cielos.»",
  "Mateo 5:20",
  "Lucas 12:31 ofrece el paralelo sin la mención explícita de «su justicia» en ese verso. Mateo la añade porque su sermón está tejido con dikaiosýnē. No son dos evangelios rivales. Son dos testigos. Mateo no permite, sin embargo, que el Reino se vuelva consigna sin rectitud.",
  "Lente teológica.",
  "Hay quien lee «su justicia» únicamente como la justicia imputada de Romanos 3. Hay quien la lee únicamente como conducta. El texto de Mateo no resuelve la disputa de escuelas; la precede. En el sermón, dikaiosýnē es la vida recta bajo el Reino, la que el Padre ve en secreto, la que supera la de los fariseos, aquella de la cual se tiene hambre. Esa hambre no contradice a Pablo: la confirma. Nadie busca con provecho la justicia de Dios si pretende fabricársela.",
  "«Porque ignorando la justicia de Dios, y procurando establecer la suya propia, no se han sujetado á la justicia de Dios.»",
  "Romanos 10:3",
  "El Reino en Mateo es ya y todavía no. Ya: Jesús expulsa demonios por el Espíritu de Dios y el reino ha llegado. Todavía no: «venga tu reino» se sigue orando. Buscar el reino es someterse al Rey que ya habla y anhelar al Rey que aún no se ha sentado visiblemente sobre las naciones. Reducirlo a un proyecto de vida con valores cristianos es coronar el yo con vocabulario del trono.",
  "Lente canónica.",
  "En 1 Reyes 17 el Señor manda provisión junto al arroyo Querit. El arroyo también se seca. Mateo 6:33 no promete que Querit no se seque: promete que el Padre no ignora. En Éxodo 16 el maná es del día; quien acumula para mañana encuentra corrupción. El versículo 34 —«no os congojéis por el día de mañana»— evoca el desierto. El pueblo que desea depósito de dos jornadas no ha oído al que da el pan cotidiano.",
  "«Danos hoy nuestro pan cotidiano.»",
  "Mateo 6:11",
  "El Salmo 37 afirma que el justo no es desamparado. Job habría levantado la mano. La Escritura no se anula a sí misma: sostiene juntos la providencia ordinaria y el sufrimiento del inocente. Mateo 6:33 vive en esa tensión; no la resuelve con un lema. Y en Mateo 27 el Hijo que pronunció 6:33 muere despojado. Si «estas cosas os serán añadidas» significara inmunidad material, la cruz sería la refutación del sermón. Como no lo es, el versículo no significaba eso.",
  "Lente pastoral.",
  "El afán no es la previsión. José almacenó trigo porque un sueño de Dios lo mandó. El afán es la mente dividida que no cree que el Padre ya sabe. Existe tesorería cristiana; existe planificación. Lo que 6:25–34 interrumpe es el culto al mañana: esa liturgia interior que se levanta antes que el Reino y dicta a Dios cómo ha de abastecer la casa.",
  "Una pastoral infiel emplea 6:33 para silenciar al pobre: si buscaras el reino, tendrías pan. El Señor no dijo eso. Dijo que el gentil persigue el pan como fin, y que el discípulo busca el reino, y que el Padre añade el pan. Cuando el pan no llega, el texto no autoriza a acusar la fe del hambriento. Autoriza a la iglesia a ser el medio de la añadidura.",
  "«Porque tuve hambre, y me disteis de comer.»",
  "Mateo 25:35",
  "Concordancias",
  "δικαιοσύνη en Mateo.",
  "5:6 — hambre y sed de justicia. 5:10 — perseguidos por causa de la justicia. 5:20 — justicia mayor que la de escribas y fariseos. 6:1 — no hacer la justicia delante de los hombres. 6:33 — buscar su justicia. 21:32 — Juan vino en camino de justicia. El mapa es coherente: la misma palabra recorre el hambre, la persecución, la superioridad respecto del fariseo, la ocultación piadosa y la búsqueda del versículo 33. Quien aísle 6:33 para «activar provisión» sin pasar por 5:20 y 6:1 está usando un hilo y dejando el tapiz.",
  "βασιλεία en Mateo.",
  "3:2 y 4:17 — arrepentíos, porque el reino se ha acercado. 5:3 y 5:10 — de ellos es el reino. 6:10 — venga tu reino. 6:33 — buscad el reino. 13 — parábolas: semilla, cizaña, tesoro, perla, red. 16:19 — llaves del reino. 25:34 — heredad el reino preparado. Buscar el reino no es cazar una sensación. Es arrepentirse porque se acercó, pedir que venga, hallarlo como quien vende todo por la perla, y esperar la herencia.",
  "ζητέω y ἐπιζητέω.",
  "6:32: los gentiles persiguen. 6:33: vosotros buscad. 7:7: buscad y hallaréis. 13:45: busca buenas perlas. 28:5: sé que buscáis a Jesús. Hay una búsqueda que halla al Crucificado y otra que halla solo pan. El verbo no salva. El objeto denuncia.",
  "μεριμνάω en 6:25–34.",
  "El afán es el adversario local del versículo 33. Se afanan la vida, la comida, la bebida, el vestido, el mañana. Filipenses 4:6 empleará el mismo verbo: por nada os afanéis; antes bien, orad. 1 Pedro 5:7: echando toda vuestra ansiedad sobre él. Mateo ofrece el objeto; Filipenses, la paz. No rivalizan.",
  "La Escritura interpreta la Escritura",
  "En 1 Reyes 3:11–13 Salomón pide sabiduría, no riqueza; se le añaden las otras cosas. El eco es antiguo. El añadido no canonizó, sin embargo, su corazón posterior. Mateo 6:33 no es un mecanismo para repetir a Salomón: es la orden de no ser gentil en el afán.",
  "Salmo 37:4–5 y 37:25; Salmo 34:9–10; Salmo 84:11; Proverbios 3:9–10 —que no se emplee para comprar a Dios—; Isaías 33:16; Jeremías 17:7–8; Mateo 5:6, 20; 6:8–11; 6:19–34; 7:7–11; 10:29–31; 13:44–46; Lucas 12:22–34.",
  "«Trabajad no por la comida que perece, mas por la comida que á vida eterna permanece.»",
  "Juan 6:27",
  "Romanos 14:17; 2 Corintios 9:8–11; Filipenses 3:9; 4:6–19; Colosenses 3:1–2; 1 Timoteo 6:6–10; Hebreos 13:5–6; Santiago 2:15–17; 4:13–15; 1 Pedro 5:7.",
  "Voces al servicio del texto",
  "Juan Calvino.",
  "«Hay la mayor inconsistencia en que hombres nacidos para una vida mejor se ocupen por entero de objetos terrenos. Quien asigna el primer rango al reino de Dios no llevará más allá de lo moderado su cuidado del alimento.» (Comentario a Mateo 6:33.) La justicia, según Calvino, puede entenderse como de Dios o como del reino, pues el reino consiste en justicia, esto es, en novedad de vida. Las demás cosas son apéndices. Hasta aquí el ginebrino. El tratado lo retiene: el versículo no hincha el apéndice hasta hacerlo fin.",
  "Matthew Henry.",
  "«Es la suma y la sustancia de todo nuestro deber: ocuparnos de la religión como de nuestra principal preocupación.» Henry oye un doble argumento: hay algo mayor —la vida del alma— y se manda buscar el reino. El objeto es doble: el cielo como fin, la santidad como camino. La promesa: estas cosas se dan por añadidura, como el papel y el hilo a quien compra la tela. No promete palacios; promete que la búsqueda sincera no vuelve vacía.",
  "Juan Crisóstomo.",
  "En las homilías sobre Mateo, Crisóstomo insiste en que Cristo no prohíbe el trabajo: prohíbe la esclavitud al mañana. Las aves no enseñan pereza; enseñan confianza. Quien oye 6:33 y abandona el oficio no ha oído 6:33: ha oído su propia gana de no sudar. El reino se busca trabajando sin adorar el trabajo.",
  "Charles Spurgeon.",
  "Spurgeon predica el versículo como liberación del corazón partido. El tesoro, el ojo y el amo de 6:19–24 desembocan aquí. Quien tiene dos fines tiene un alma oscura. Quien tiene un fin —el reino— recibe lo demás como sombra que sigue al cuerpo. No vende el versículo como garantía de confort. Lo usa para destronar el confort como fin.",
  "John MacArthur.",
  "MacArthur subraya prôton como prioridad, no como truco horario. Buscar el reino incluye anhelar que el Rey se manifieste y que su señorío se vea en una vida de justicia, paz y gozo. El tratado lo sigue en esto: 6:33 no es la puerta de un milenio privado de bienes. Es la puerta de un discípulo de un solo ojo.",
  "Ninguno de estos cinco escribe Mateo. Donde uno de ellos convierta el añadido en derecho exigible, el texto lo corrige. Donde uno de ellos ponga el reino debajo del pan, el texto lo depone.",
  "Lo que el mandato derriba",
  "Derrumba el evangelio de la permuta.",
  "«Yo busco el reino; Tú llenas la cuenta.» Eso es la religión que este mismo sermón condena cuando prohíbe orar como los gentiles, con muchas palabras, para ser oídos.",
  "«Y orando, no seáis prolijos, como los Gentiles; que piensan que por su parlería serán oídos.»",
  "Mateo 6:7",
  "Derrumba la pereza revestida de piedad.",
  "«Yo no trabajo; yo busco el reino.» Pablo manda que el que no quiera trabajar tampoco coma. Jesús no contradice a Pablo. El afán no es el trabajo; el afán es el culto al resultado del trabajo.",
  "«Si alguno no quisiere trabajar, tampoco coma.»",
  "2 Tesalonicenses 3:10",
  "Derrumba la acusación contra el pobre.",
  "«Te falta pan porque no buscaste.» El Siervo buscó el reino hasta la sangre y le despojaron hasta la túnica. La iglesia que usa 6:33 como diagnóstico del ajeno ha dejado de ser medio de la añadidura y se ha sentado en el tribunal de Job. Los amigos de Job también tenían versículos. Dios no los elogió.",
  "Derrumba el ojo doble.",
  "Un culto el día del Señor y un Mamón el resto de la semana, unidos por un versículo en la pared. Mateo 6:24 sigue vigente cuando se cita 6:33. No obstante, el lema en la pared no absuelve al corazón partido.",
  "Doctrina que el texto obliga",
  "Primero. Dios es Padre y Rey. Conoce la necesidad. Reina ahora y vendrá.",
  "Segundo. El discípulo tiene un solo primer objeto: el reino y la justicia de ese Dios. Todo lo demás es segundo, tercero o nada.",
  "Tercero. La justicia que se busca es suya. No se improvisa una rectitud de escaparate ni se recicla la de los fariseos.",
  "Cuarto. La providencia es real. El Padre alimenta y viste. No por eso la fe se mide en despensas.",
  "Quinto. «Estas cosas» son las del contexto. Ampliarlas a todos los antojos es otro evangelio.",
  "Sexto. La búsqueda es comunitaria, presente, perseverante. No es un decreto suelto ni un contrato de resultados.",
  "Un acto que pueda fecharse",
  "No se cierra un tratado con un lema. Se cierra con un acto que el texto pueda reconocer. El embudo pastoral de esta casa —conocer, convicción, arrepentimiento, ingreso al pueblo, conversión, firmeza— vive dentro del sermón, cuando el discípulo deja de servir a dos y el Padre añade lo que Él sabe.",
  "Tomemos Mateo 6:19–34. Ver: léase el bloque entero, en voz alta, sin saltar a 6:33 como talismán. Entorno: nómbrense por escrito las tres preocupaciones que dividen la mente y pónganse bajo 6:32. Revelación: prôton es rango, no horario; prostethḗsetai es pasiva del Padre; taûta son estas cosas, no los antojos. Doctrina: un solo primer objeto; la justicia es suya; el pan no es el Señor. Argumento: deríbese el contrato; si se ha usado 6:33 para exigirle a Dios una permuta, corresponda el arrepentimiento. Decisión: hoy —miércoles 23 de septiembre de 2026, America/Caracas— ceso de tratar Mateo 6:33 como instrumento de negociación y restauro el primer puesto al Reino.",
  "Esa decisión se confiesa delante de un testigo de carne: un nombre, una iglesia, un hermano o hermana que pueda preguntar mañana si Mamón volvió al trono. Órese 6:9–13. Recíbase el pan del día, si lo hay, como añadidura, no como prueba. Si al lado falta el pan, sea el lector el medio antes de predicar el versículo. El reino no se alquila. Se busca. Quien añade es Él. Permanecer es volver al bloque entero. Si el acto no puede fecharse ni nombrarse delante de alguien de carne, no se ha llegado a la última letra del protocolo.",
  "Si aún no crees, arrepiéntete, cree en el Señor Jesús, pide el agua, confiesa el Nombre. Busca una iglesia que anuncie el Reino sin convertirlo en lema de despensa. Este libro no sustituye el cuerpo de Cristo.",
  "Conclusión",
  "He leído este versículo en bocas que no lo merecían. Lo he leído en la mía. Lo he visto colocado sobre mesas de trabajo donde el primer pensamiento de la mañana no era el Reino, sino el saldo. La hoja estaba limpia, la tipografía era bella, y debajo de esa belleza el corazón ya había elegido señor. No era ateísmo. Era una fe que emplea al Padre como proveedor y al texto como instrumento de negociación. Por eso esta conclusión no consuela. Sella.",
  "Mateo 6:33 no es una llave que abre la despensa de Dios. Es una sentencia que revela qué rey gobierna. Quien busca primeramente el reino ha declarado, con los hechos y no con el lema, que hay un trono ocupado y que no es el suyo. Quien cita el versículo y permanece con la mente dividida ha declarado lo contrario: que el Reino le sirve de barniz y que Mamón le sirve de amo. Entre esas dos declaraciones no hay un término medio piadoso. Jesús lo cerró en el versículo 24. Dos señores no se turnan. Uno depone al otro.",
  "El afán que el Señor interrumpe en 6:25–34 no es la previsión del padre de familia, ni la tesorería de la iglesia, ni el sudor del oficio. Es la liturgia interior del incrédulo bautizado: esa procesión cotidiana en la cual el mañana entra primero, el pan se sienta a la derecha, el vestido a la izquierda, y el Padre —si acaso— permanece de pie junto a la puerta, esperando que le sobren cinco minutos. A eso se le llama responsabilidad. El texto lo llama gentilidad. «Porque los Gentiles buscan todas estas cosas.» No dijo: los ateos. Dijo: los que viven como si el Padre no supiera. Es posible ser miembro de iglesia y vivir, en el orden del estómago, como quien no tiene Padre.",
  "He visto a hombres honrados convertir este versículo en un contrato. «Yo pongo el Reino; Tú pones la casa, el remedio, el cierre de la venta.» Eso no es fe: es simonía del corazón, el mismo vicio de 6:7 vestido de negocio. El Padre de 6:8 y de 6:32 conoce la lista; lo que no soporta es que le robe el primer puesto. Cuando la necesidad ocupa ese puesto, la necesidad se ha vuelto ídolo —y un ídolo no es menos ídolo por ser urgente o razonable—.",
  "Tampoco es lícito —y hablo como quien ha conocido la pobreza y como quien ha sido tentado de predicar a los pobres con dureza prestada— emplear este versículo para herir al que no tiene pan. El Siervo buscó el Reino hasta el último aliento y lo despojaron hasta de la túnica. Si Mateo 6:33 significara que al justo nunca le falta la cena, el Gólgota sería la refutación pública del Sermón del Monte. Como el Gólgota no es esa refutación, el versículo no significaba eso. Quien mira la mesa vacía del hermano y diagnostica su fe ha dejado de ser discípulo y se ha sentado en el tribunal de Job.",
  "La justicia que se busca no es la propia, pulida para el retrato. Es la suya: la de 5:20, que deja pequeña la de los escribas; la de 6:1, que se oculta para que el Padre —no el pasillo— la vea; la de 5:6, que tiene hambre y no posee. He conocido la otra —fotografiada, anunciada, usada de credencial—: esa no se busca, se exhibe, y el sermón la declara pagada en esta tierra. Si la búsqueda del Reino necesita testigos humanos para existir, no se ha buscado el Reino: se ha buscado un nombre.",
  "Πρῶτον no es un horario. No es «primero el oficio, después el correo, después el Reino si queda lugar». Es rango. Es el orden del ser. O el Reino manda sobre el oficio, el matrimonio, el temor, la enfermedad, la reputación y la tumba, o esas realidades predican un evangelio más alto que el de Jesús. No hay neutralidad de agenda. El primer puesto siempre está ocupado. La única pregunta es quién lo ocupa cuando nadie ve.",
  "La añadidura —προστεθήσεται— es pasiva por misericordia y por juicio. Por misericordia: no se depende de una técnica para que el pan llegue. Por juicio: no puede atribuirse el pan cuando llega. Quien añade es Él. Quien retiene también es Él. Job lo supo en un mismo día. Pablo lo supo con el aguijón que no se quitó. El Hijo lo supo cuando pidió que pasara la copa y bebió. Una teología que solo sabe leer la añadidura cuando la despensa se llena no ha leído a Mateo. Ha leído su hambre y le ha puesto un versículo encima.",
  "Por eso hablo con severidad: no porque el Padre sea tacaño, sino porque el versículo ha sido violado —talismán de la clase acomodada, consigna de emprendedores ungidos, consuelo barato de quien no quiere arrepentirse del primer amor al mañana—. El Reino no se busca con la punta de los labios. Se busca como la perla: vendiéndolo todo, porque el ojo ya no admite dos tesoros. Quien no ha vendido nada no ha hallado nada: ha hallado un lema.",
  "Si este tratado deja al lector donde estaba, ha fracasado para él. No por falta de lentes. Por falta de quebranto. El texto no pedía que se entendiera el participio. Pedía que se dejara de servir a dos. Pedía que el afán bajara de categoría. Pedía que la justicia de Él diera hambre verdadera, no hambre de parecer. Pedía que, si el pan falta, no se haga de la falta un altar contra Dios, y si el pan sobra, no se haga de la abundancia una prueba de que ya se buscó bastante.",
  "Yo, Alejandro Sirit, no firmo pacto alguno de resultados. Firmo lo que el monte ya firmó. Buscad primeramente su reino y su justicia. No busquéis primeramente que os vaya bien. No busquéis primeramente que os comprendan. No busquéis primeramente que el aguijón se quite. Buscadlo a Él en el rango que le corresponde, y dejad que «estas cosas» —solo estas, las del hambre y del vestido, no las del capricho— caigan donde el Padre quiera que caigan.",
  "El día en que el Reino deje de ser primero, este versículo se volverá acusación. El día en que vuelva a ser primero, el mismo versículo se volverá descanso: no porque el mañana se haya vuelto blando, sino porque el trono ya no está vacío. El texto manda. El método sirve. La rodilla cierra.",
  "Decisión para esta semana",
  "Semana del 5 al 11 de octubre de 2026. Confieso delante de Dios que he usado Mateo 6:33 como contrato, poniendo el reino para que Dios ponga la añadidura, o que el afán ha sido mi primera liturgia de cada mañana. Esta semana leo Mateo 6:19–34 cada mañana antes de mirar cuentas o mensajes; antes del sábado 10 de octubre nombro el afán concreto que gobierna mi semana, lo pongo delante del Padre en oración y ordeno una decisión real de tiempo o de dinero según el reino y su justicia, no según el saldo. El domingo 11 de octubre cuento a un hermano de mi iglesia, que pueda pedirme cuentas, qué afán nombré y qué decisión ordené. Si aún no he creído ni he sido bautizado, esta semana me arrepiento, confieso a Cristo y pido el agua.",
  "Alejandro Sirit · Editorial Cielo Efata · 2026"
];
