/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanonRouteImport } from './routes/canon'
import { Route as CasaRouteImport } from './routes/casa'
import { Route as CrisolRouteImport } from './routes/crisol'
import { Route as CuadernoRouteImport } from './routes/cuaderno'
import { Route as EscrituraRouteImport } from './routes/escritura'
import { Route as GuiasRouteImport } from './routes/guias'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as PalabraRouteImport } from './routes/palabra'
import { Route as SelloRouteImport } from './routes/sello'
import { Route as TratadosRouteImport } from './routes/tratados'
import { Route as ApiVozRouteImport } from './routes/api/voz'
import { Route as EstudiosIndexRouteImport } from './routes/estudios/index'
import { Route as EstudiosSlugRouteImport } from './routes/estudios/$slug'
import { Route as TratadosSlugRouteImport } from './routes/tratados/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanonRoute = CanonRouteImport.update({
  id: '/canon',
  path: '/canon',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaRoute = CasaRouteImport.update({
  id: '/casa',
  path: '/casa',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisolRoute = CrisolRouteImport.update({
  id: '/crisol',
  path: '/crisol',
  getParentRoute: () => rootRouteImport,
} as any)
const CuadernoRoute = CuadernoRouteImport.update({
  id: '/cuaderno',
  path: '/cuaderno',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrituraRoute = EscrituraRouteImport.update({
  id: '/escritura',
  path: '/escritura',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasRoute = GuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const PalabraRoute = PalabraRouteImport.update({
  id: '/palabra',
  path: '/palabra',
  getParentRoute: () => rootRouteImport,
} as any)
const SelloRoute = SelloRouteImport.update({
  id: '/sello',
  path: '/sello',
  getParentRoute: () => rootRouteImport,
} as any)
const TratadosRoute = TratadosRouteImport.update({
  id: '/tratados',
  path: '/tratados',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVozRoute = ApiVozRouteImport.update({
  id: '/api/voz',
  path: '/api/voz',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiosIndexRoute = EstudiosIndexRouteImport.update({
  id: '/estudios/',
  path: '/estudios/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiosSlugRoute = EstudiosSlugRouteImport.update({
  id: '/estudios/$slug',
  path: '/estudios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TratadosSlugRoute = TratadosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TratadosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canon': typeof CanonRoute
  '/casa': typeof CasaRoute
  '/crisol': typeof CrisolRoute
  '/cuaderno': typeof CuadernoRoute
  '/escritura': typeof EscrituraRoute
  '/guias': typeof GuiasRoute
  '/metodo': typeof MetodoRoute
  '/obras': typeof ObrasRoute
  '/palabra': typeof PalabraRoute
  '/sello': typeof SelloRoute
  '/tratados': typeof TratadosRouteWithChildren
  '/api/voz': typeof ApiVozRoute
  '/estudios/$slug': typeof EstudiosSlugRoute
  '/tratados/$slug': typeof TratadosSlugRoute
  '/estudios/': typeof EstudiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canon': typeof CanonRoute
  '/casa': typeof CasaRoute
  '/crisol': typeof CrisolRoute
  '/cuaderno': typeof CuadernoRoute
  '/escritura': typeof EscrituraRoute
  '/guias': typeof GuiasRoute
  '/metodo': typeof MetodoRoute
  '/obras': typeof ObrasRoute
  '/palabra': typeof PalabraRoute
  '/sello': typeof SelloRoute
  '/tratados': typeof TratadosRouteWithChildren
  '/api/voz': typeof ApiVozRoute
  '/estudios/$slug': typeof EstudiosSlugRoute
  '/tratados/$slug': typeof TratadosSlugRoute
  '/estudios': typeof EstudiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canon': typeof CanonRoute
  '/casa': typeof CasaRoute
  '/crisol': typeof CrisolRoute
  '/cuaderno': typeof CuadernoRoute
  '/escritura': typeof EscrituraRoute
  '/guias': typeof GuiasRoute
  '/metodo': typeof MetodoRoute
  '/obras': typeof ObrasRoute
  '/palabra': typeof PalabraRoute
  '/sello': typeof SelloRoute
  '/tratados': typeof TratadosRouteWithChildren
  '/api/voz': typeof ApiVozRoute
  '/estudios/$slug': typeof EstudiosSlugRoute
  '/tratados/$slug': typeof TratadosSlugRoute
  '/estudios/': typeof EstudiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canon'
    | '/casa'
    | '/crisol'
    | '/cuaderno'
    | '/escritura'
    | '/guias'
    | '/metodo'
    | '/obras'
    | '/palabra'
    | '/sello'
    | '/tratados'
    | '/api/voz'
    | '/estudios/$slug'
    | '/tratados/$slug'
    | '/estudios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canon'
    | '/casa'
    | '/crisol'
    | '/cuaderno'
    | '/escritura'
    | '/guias'
    | '/metodo'
    | '/obras'
    | '/palabra'
    | '/sello'
    | '/tratados'
    | '/api/voz'
    | '/estudios/$slug'
    | '/tratados/$slug'
    | '/estudios'
  id:
    | '__root__'
    | '/'
    | '/canon'
    | '/casa'
    | '/crisol'
    | '/cuaderno'
    | '/escritura'
    | '/guias'
    | '/metodo'
    | '/obras'
    | '/palabra'
    | '/sello'
    | '/tratados'
    | '/api/voz'
    | '/estudios/$slug'
    | '/tratados/$slug'
    | '/estudios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanonRoute: typeof CanonRoute
  CasaRoute: typeof CasaRoute
  CrisolRoute: typeof CrisolRoute
  CuadernoRoute: typeof CuadernoRoute
  EscrituraRoute: typeof EscrituraRoute
  GuiasRoute: typeof GuiasRoute
  MetodoRoute: typeof MetodoRoute
  ObrasRoute: typeof ObrasRoute
  PalabraRoute: typeof PalabraRoute
  SelloRoute: typeof SelloRoute
  TratadosRoute: typeof TratadosRouteWithChildren
  ApiVozRoute: typeof ApiVozRoute
  EstudiosSlugRoute: typeof EstudiosSlugRoute
  EstudiosIndexRoute: typeof EstudiosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canon': {
      id: '/canon'
      path: '/canon'
      fullPath: '/canon'
      preLoaderRoute: typeof CanonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa': {
      id: '/casa'
      path: '/casa'
      fullPath: '/casa'
      preLoaderRoute: typeof CasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crisol': {
      id: '/crisol'
      path: '/crisol'
      fullPath: '/crisol'
      preLoaderRoute: typeof CrisolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuaderno': {
      id: '/cuaderno'
      path: '/cuaderno'
      fullPath: '/cuaderno'
      preLoaderRoute: typeof CuadernoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritura': {
      id: '/escritura'
      path: '/escritura'
      fullPath: '/escritura'
      preLoaderRoute: typeof EscrituraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias': {
      id: '/guias'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof GuiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palabra': {
      id: '/palabra'
      path: '/palabra'
      fullPath: '/palabra'
      preLoaderRoute: typeof PalabraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sello': {
      id: '/sello'
      path: '/sello'
      fullPath: '/sello'
      preLoaderRoute: typeof SelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratados': {
      id: '/tratados'
      path: '/tratados'
      fullPath: '/tratados'
      preLoaderRoute: typeof TratadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voz': {
      id: '/api/voz'
      path: '/api/voz'
      fullPath: '/api/voz'
      preLoaderRoute: typeof ApiVozRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudios/': {
      id: '/estudios/'
      path: '/estudios'
      fullPath: '/estudios/'
      preLoaderRoute: typeof EstudiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudios/$slug': {
      id: '/estudios/$slug'
      path: '/estudios/$slug'
      fullPath: '/estudios/$slug'
      preLoaderRoute: typeof EstudiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratados/$slug': {
      id: '/tratados/$slug'
      path: '/$slug'
      fullPath: '/tratados/$slug'
      preLoaderRoute: typeof TratadosSlugRouteImport
      parentRoute: typeof TratadosRoute
    }
  }
}

interface TratadosRouteChildren {
  TratadosSlugRoute: typeof TratadosSlugRoute
}

const TratadosRouteChildren: TratadosRouteChildren = {
  TratadosSlugRoute: TratadosSlugRoute,
}

const TratadosRouteWithChildren = TratadosRoute._addFileChildren(
  TratadosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanonRoute: CanonRoute,
  CasaRoute: CasaRoute,
  CrisolRoute: CrisolRoute,
  CuadernoRoute: CuadernoRoute,
  EscrituraRoute: EscrituraRoute,
  GuiasRoute: GuiasRoute,
  MetodoRoute: MetodoRoute,
  ObrasRoute: ObrasRoute,
  PalabraRoute: PalabraRoute,
  SelloRoute: SelloRoute,
  TratadosRoute: TratadosRouteWithChildren,
  ApiVozRoute: ApiVozRoute,
  EstudiosSlugRoute: EstudiosSlugRoute,
  EstudiosIndexRoute: EstudiosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
